"""
Seed the `profile_prompts_section` system options catalog for the AboutMe
prompt picker (50 prompts + 5 categories + dialog chrome).

Keys resolve as profile.prompts.{slug}, profile.prompts.cat.{cat},
profile.prompts.ui.*. Selection stores display text (no data migration).

Idempotent: upserts every value so re-running refreshes translations.
Run inside the backend container:
    docker exec -w /app redthread-backend python seed/seed_profile_prompts_section.py
"""

import asyncio
import os
import sys

# Add the project root to sys.path
sys.path.append(os.getcwd())

from src.core.database import init_db
from src.models.system_options import SystemOption

LANGS = [
    "es", "en", "pt", "fr", "de", "it", "ru", "sv", "nl", "zh",
    "hi", "bn", "ja", "ko", "ar", "sw", "ha", "am", "tl", "ms", "mi",
]


def L(**kw) -> dict:
    """Language-specific text. Raises if any supported language is missing."""
    missing = [lang for lang in LANGS if lang not in kw]
    if missing:
        raise ValueError(f"missing languages: {missing}")
    unknown = [key for key in kw if key not in LANGS]
    if unknown:
        raise ValueError(f"unknown languages: {unknown}")
    return kw


TEXTS = [
    {
        "value": "ui.title",
        "order": 0,
        "translations": L(
            es="Selecciona una frase divertida", en="Pick a fun prompt",
            pt="Escolha uma frase divertida", fr="Choisis une phrase amusante",
            de="Wähle eine lustige Frage", it="Scegli una frase divertente",
            ru="Выбери весёлый вопрос", sv="Välj en rolig fråga",
            nl="Kies een leuke prompt", zh="选一个有趣的话题",
            hi="मज़ेदार प्रश्न चुनें", bn="মজার প্রশ্ন বেছে নিন",
            ja="楽しいお題を選んでね", ko="재미있는 질문을 고르세요",
            ar="اختر عبارة مرحة", sw="Chagua swali la kufurahisha",
            ha="Zaɓi tambaya mai daɗi", am="አዝናኝ ጥያቄ ምረጥ",
            tl="Pumili ng nakakatuwang prompt", ms="Pilih gesaan yang menyeronokkan",
            mi="Kōwhiria tētahi pātai whakangahau",
        ),
    },
    {
        "value": "ui.search",
        "order": 1,
        "translations": L(
            es="Buscar frases...", en="Search prompts...",
            pt="Buscar frases...", fr="Rechercher...",
            de="Fragen suchen...", it="Cerca frasi...",
            ru="Найти вопросы...", sv="Sök frågor...",
            nl="Zoek prompts...", zh="搜索话题…",
            hi="प्रश्न खोजें...", bn="প্রশ্ন খুঁজুন...",
            ja="お題を検索…", ko="질문 검색…",
            ar="بحث عن عبارات...", sw="Tafuta maswali...",
            ha="Nemi tambayoyi...", am="ጥያቄዎች ፈልግ…",
            tl="Maghanap ng prompt...", ms="Cari gesaan...",
            mi="Rapua ngā pātai…",
        ),
    },
    {
        "value": "ui.save",
        "order": 2,
        "translations": L(
            es="Guardar", en="Save",
            pt="Salvar", fr="Enregistrer",
            de="Speichern", it="Salva",
            ru="Сохранить", sv="Spara",
            nl="Opslaan", zh="保存",
            hi="सहेजें", bn="সংরক্ষণ",
            ja="保存", ko="저장",
            ar="حفظ", sw="Hifadhi",
            ha="Ajiye", am="አስቀምጥ",
            tl="I-save", ms="Simpan",
            mi="Tiaki",
        ),
    },
    {
        "value": "ui.cancel",
        "order": 3,
        "translations": L(
            es="Cancelar", en="Cancel",
            pt="Cancelar", fr="Annuler",
            de="Abbrechen", it="Annulla",
            ru="Отмена", sv="Avbryt",
            nl="Annuleren", zh="取消",
            hi="रद्द करें", bn="বাতিল",
            ja="キャンセル", ko="취소",
            ar="إلغاء", sw="Ghairi",
            ha="Soke", am="ሰርዝ",
            tl="Kanselahin", ms="Batal",
            mi="Whakakore",
        ),
    },
    {
        "value": "ui.counter",
        "order": 4,
        "translations": L(
            es="{{n}}/5 seleccionadas", en="{{n}}/5 selected",
            pt="{{n}}/5 selecionadas", fr="{{n}}/5 sélectionnées",
            de="{{n}}/5 ausgewählt", it="{{n}}/5 selezionate",
            ru="Выбрано: {{n}}/5", sv="{{n}}/5 valda",
            nl="{{n}}/5 geselecteerd", zh="已选 {{n}}/5",
            hi="{{n}}/5 चयनित", bn="{{n}}/5টি নির্বাচিত",
            ja="{{n}}/5 選択中", ko="{{n}}/5 선택됨",
            ar="{{n}}/5 محددة", sw="{{n}}/5 vimechaguliwa",
            ha="{{n}}/5 aka zaɓa", am="{{n}}/5 ተመርጠዋል",
            tl="{{n}}/5 napili", ms="{{n}}/5 dipilih",
            mi="{{n}}/5 kua tīpakohia",
        ),
    },
    {
        "value": "ui.noresults",
        "order": 5,
        "translations": L(
            es="Sin resultados para tu búsqueda.",
            en="No results for your search.",
            pt="Sem resultados para sua busca.",
            fr="Aucun résultat pour ta recherche.",
            de="Keine Ergebnisse für deine Suche.",
            it="Nessun risultato per la tua ricerca.",
            ru="По вашему запросу ничего не найдено.",
            sv="Inga resultat för din sökning.",
            nl="Geen resultaten voor je zoekopdracht.",
            zh="没有符合的搜索结果。",
            hi="आपकी खोज हेतु कोई परिणाम नहीं।",
            bn="আপনার অনুসন্ধানের কোনো ফলাফল নেই।",
            ja="検索結果がありません。",
            ko="검색 결과가 없습니다.",
            ar="لا نتائج لبحثك.",
            sw="Hakuna matokeo ya utafutaji wako.",
            ha="Babu sakamako ga bincikenka.",
            am="ለፍለጋህ ምንም ውጤት የለም።",
            tl="Walang resulta para sa paghahanap mo.",
            ms="Tiada hasil untuk carian anda.",
            mi="Kāore he hua mō tāu rapunga.",
        ),
    },
    {
        "value": "ui.all",
        "order": 6,
        "translations": L(
            es="Todas", en="All",
            pt="Todas", fr="Toutes",
            de="Alle", it="Tutte",
            ru="Все", sv="Alla",
            nl="Alle", zh="全部",
            hi="सभी", bn="সব",
            ja="すべて", ko="전체",
            ar="الكل", sw="Zote",
            ha="Duka", am="ሁሉም",
            tl="Lahat", ms="Semua",
            mi="Katoa",
        ),
    },
    {
        "value": "cat.musica",
        "order": 7,
        "translations": L(
            es="Música", en="Music",
            pt="Música", fr="Musique",
            de="Musik", it="Musica",
            ru="Музыка", sv="Musik",
            nl="Muziek", zh="音乐",
            hi="संगीत", bn="সঙ্গীত",
            ja="音楽", ko="음악",
            ar="الموسيقى", sw="Muziki",
            ha="Kiɗa", am="ሙዚቃ",
            tl="Musika", ms="Muzik",
            mi="Puoro",
        ),
    },
    {
        "value": "cat.viajes",
        "order": 8,
        "translations": L(
            es="Viajes", en="Travel",
            pt="Viagens", fr="Voyages",
            de="Reisen", it="Viaggi",
            ru="Путешествия", sv="Resor",
            nl="Reizen", zh="旅行",
            hi="यात्रा", bn="ভ্রমণ",
            ja="旅行", ko="여행",
            ar="سفر", sw="Safari",
            ha="Tafiya", am="ጉዞ",
            tl="Paglalakbay", ms="Perjalanan",
            mi="Haereere",
        ),
    },
    {
        "value": "cat.comida",
        "order": 9,
        "translations": L(
            es="Comida", en="Food",
            pt="Comida", fr="Cuisine",
            de="Essen", it="Cibo",
            ru="Еда", sv="Mat",
            nl="Eten", zh="美食",
            hi="खाना", bn="খাবার",
            ja="グルメ", ko="음식",
            ar="طعام", sw="Chakula",
            ha="Abinci", am="ምግብ",
            tl="Pagkain", ms="Makanan",
            mi="Kai",
        ),
    },
    {
        "value": "cat.recuerdos",
        "order": 10,
        "translations": L(
            es="Recuerdos", en="Memories",
            pt="Memórias", fr="Souvenirs",
            de="Erinnerungen", it="Ricordi",
            ru="Воспоминания", sv="Minnen",
            nl="Herinneringen", zh="回忆",
            hi="यादें", bn="স্মৃতি",
            ja="思い出", ko="추억",
            ar="ذكريات", sw="Kumbukumbu",
            ha="Tunani", am="ትዝታዎች",
            tl="Alaala", ms="Kenangan",
            mi="Maharatanga",
        ),
    },
    {
        "value": "cat.hobbies",
        "order": 11,
        "translations": L(
            es="Hobbies", en="Hobbies",
            pt="Hobbies", fr="Loisirs",
            de="Hobbys", it="Hobby",
            ru="Хобби", sv="Hobbyer",
            nl="Hobby's", zh="爱好",
            hi="शौक", bn="শখ",
            ja="趣味", ko="취미",
            ar="هوايات", sw="Burudani",
            ha="Abubuwan shaʼawa", am="ትርፍ ጊዜ",
            tl="Mga libangan", ms="Hobi",
            mi="Nga mahi whakangahau",
        ),
    },
    {
        "value": "want_someone",
        "order": 12,
        "translations": L(
            es="Quiero alguien que…", en="I want someone who…",
            pt="Eu quero alguém que…", fr="Je veux quelqu'un qui…",
            de="Ich will jemanden, der…", it="Voglio qualcuno che…",
            ru="Хочу человека, который…", sv="Jag vill ha någon som…",
            nl="Ik wil iemand die…", zh="我想要一个…的人",
            hi="मुझे ऐसा कोई चाहिए जो…", bn="আমি এমন কাউকে চাই যে…",
            ja="こんな人がいいな…", ko="이런 사람을 원해…",
            ar="أريد شخصًا…", sw="Nataka mtu ambaye…",
            ha="Ina son mutumin da…", am="እንደዚህ ያለ ሰው እፈልጋለሁ…",
            tl="Gusto ko ng taong…", ms="Saya mahu seseorang yang…",
            mi="Kei te hiahia au i tētahi…",
        ),
    },
    {
        "value": "curious_thing",
        "order": 13,
        "translations": L(
            es="Una cosa curiosa sobre mí es…", en="A curious thing about me is…",
            pt="Uma coisa curiosa sobre mim é…", fr="Une chose curieuse à propos de moi est…",
            de="Etwas Kurioses an mir ist…", it="Una cosa curiosa di me è…",
            ru="Любопытный факт обо мне…", sv="En kul grej med mig är…",
            nl="Iets geks aan mij is…", zh="关于我的一件趣事是…",
            hi="मेरे बारे में एक मज़ेदार बात…", bn="আমার সম্পর্কে মজার বিষয়…",
            ja="私の面白いところは…", ko="나에 대한 재미있는 점은…",
            ar="شيء طريف عني هو…", sw="Jambo la kuchekesha kunihusu ni…",
            ha="Abin ban mamaki game da ni shi ne…", am="ስለ እኔ አስገራሚ ነገር…",
            tl="Isang nakakatuwang bagay tungkol sa akin ay…", ms="Perkara lucu tentang saya ialah…",
            mi="He mea rorirori mōku ko…",
        ),
    },
    {
        "value": "fav_playlist",
        "order": 14,
        "translations": L(
            es="Mi playlist favorita es…", en="My favorite playlist is…",
            pt="Minha playlist favorita é…", fr="Ma playlist préférée est…",
            de="Meine Lieblingsplaylist ist…", it="La mia playlist preferita è…",
            ru="Мой любимый плейлист…", sv="Min favoritspellista är…",
            nl="Mijn favoriete playlist is…", zh="我最喜欢的歌单是…",
            hi="मेरी पसंदीदा प्लेलिस्ट है…", bn="আমার প্রিয় প্লেলিস্ট…",
            ja="お気に入りのプレイリストは…", ko="내가 가장 좋아하는 플레이리스트는…",
            ar="قائمة التشغيل المفضلة لدي هي…", sw="Orodha yangu pendwa ya nyimbo ni…",
            ha="Jerin waƙoƙina da na fi so shi ne…", am="የምወደው የሙዚቃ ዝርዝር…",
            tl="Ang paborito kong playlist ay…", ms="Senarai main kegemaran saya ialah…",
            mi="Ko tāku rārangi puoro pai ko…",
        ),
    },
    {
        "value": "best_trip",
        "order": 15,
        "translations": L(
            es="El mejor viaje que he hecho fue…", en="The best trip I've taken was…",
            pt="A melhor viagem que fiz foi…", fr="Le meilleur voyage que j'ai fait était…",
            de="Die beste Reise, die ich gemacht habe, war…", it="Il miglior viaggio che ho fatto è stato…",
            ru="Лучшая поездка в моей жизни…", sv="Den bästa resan jag gjort var…",
            nl="De beste reis die ik maakte was…", zh="我经历过最棒的旅行是…",
            hi="मेरी सबसे अच्छी यात्रा थी…", bn="আমার সেরা ভ্রমণ ছিল…",
            ja="最高の旅行は…", ko="내가 해본 최고의 여행은…",
            ar="أفضل رحلة قمت بها كانت…", sw="Safari bora niliyowahi kufanya ni…",
            ha="Mafi kyawun tafiyar da na yi ita ce…", am="የሄድኩት ምርጥ ጉዞ…",
            tl="Ang pinakamagandang biyahe ko ay…", ms="Perjalanan terbaik saya ialah…",
            mi="Ko te haerenga pai rawa atu kua haere ahau ko…",
        ),
    },
    {
        "value": "fav_food",
        "order": 16,
        "translations": L(
            es="Mi comida favorita es…", en="My favorite food is…",
            pt="Minha comida favorita é…", fr="Mon plat préféré est…",
            de="Mein Lieblingsessen ist…", it="Il mio cibo preferito è…",
            ru="Моя любимая еда…", sv="Min favoritmat är…",
            nl="Mijn favoriete eten is…", zh="我最喜欢的食物是…",
            hi="मेरा पसंदीदा खाना है…", bn="আমার প্রিয় খাবার…",
            ja="好きな食べ物は…", ko="내가 가장 좋아하는 음식은…",
            ar="طعامي المفضل هو…", sw="Chakula changu pendwa ni…",
            ha="Abincin da na fi so shi ne…", am="የምወደው ምግብ…",
            tl="Ang paborito kong pagkain ay…", ms="Makanan kegemaran saya ialah…",
            mi="Ko tāku kai pai ko…",
        ),
    },
    {
        "value": "always_laugh",
        "order": 17,
        "translations": L(
            es="Algo que siempre me hace reír es…", en="Something that always makes me laugh is…",
            pt="Algo que sempre me faz rir é…", fr="Quelque chose qui me fait toujours rire est…",
            de="Etwas, das mich immer zum Lachen bringt, ist…", it="Qualcosa che mi fa sempre ridere è…",
            ru="Меня всегда смешит…", sv="Något som alltid får mig att skratta är…",
            nl="Iets wat me altijd aan het lachen maakt is…", zh="总能让我发笑的是…",
            hi="जो चीज़ मुझे हमेशा हंसाती है…", bn="যা সবসময় আমাকে হাসায়…",
            ja="いつも笑わせてくれるのは…", ko="날 항상 웃게 하는 것은…",
            ar="ما يضحكني دائمًا هو…", sw="Kitu kinachonichekesha kila wakati ni…",
            ha="Abin da kullum yake ba ni dariya shi ne…", am="ሁልጊዜ የሚያስቀኝ…",
            tl="Ang laging nagpapatawa sa akin ay…", ms="Perkara yang selalu membuat saya ketawa ialah…",
            mi="Ko te mea e whakakata ana i ahau i ngā wā katoa ko…",
        ),
    },
    {
        "value": "last_book",
        "order": 18,
        "translations": L(
            es="El último libro que leí fue…", en="The last book I read was…",
            pt="O último livro que li foi…", fr="Le dernier livre que j'ai lu était…",
            de="Das letzte Buch, das ich gelesen habe, war…", it="L'ultimo libro che ho letto è stato…",
            ru="Последняя книга, которую я прочитал…", sv="Den senaste boken jag läste var…",
            nl="Het laatste boek dat ik las was…", zh="我最近读的一本书是…",
            hi="आखिरी किताब जो मैंने पढ़ी…", bn="শেষ যে বইটি পড়েছি…",
            ja="最後に読んだ本は…", ko="최근에 읽은 책은…",
            ar="آخر كتاب قرأته كان…", sw="Kitabu cha mwisho nilichosoma ni…",
            ha="Littafin ƙarshe da na karanta shi ne…", am="ያነበብኩት የመጨረሻ መጽሐፍ…",
            tl="Ang huling librong nabasa ko ay…", ms="Buku terakhir yang saya baca ialah…",
            mi="Ko te pukapuka whakamutunga i pānuitia e au ko…",
        ),
    },
    {
        "value": "fav_series",
        "order": 19,
        "translations": L(
            es="Mi serie favorita es…", en="My favorite series is…",
            pt="Minha série favorita é…", fr="Ma série préférée est…",
            de="Meine Lieblingsserie ist…", it="La mia serie preferita è…",
            ru="Мой любимый сериал…", sv="Min favoritserie är…",
            nl="Mijn favoriete serie is…", zh="我最喜欢的剧集是…",
            hi="मेरी पसंदीदा सीरीज़ है…", bn="আমার প্রিয় সিরিজ…",
            ja="好きなドラマは…", ko="내가 가장 좋아하는 드라마는…",
            ar="مسلسلي المفضل هو…", sw="Mfululizo ninaoupenda ni…",
            ha="Jerin shirye-shiryen da na fi so shi ne…", am="የምወደው ተከታታይ ፊልም…",
            tl="Ang paborito kong serye ay…", ms="Siri kegemaran saya ialah…",
            mi="Ko tākuwhakaari pai ko…",
        ),
    },
    {
        "value": "fav_sport",
        "order": 20,
        "translations": L(
            es="El deporte que más disfruto es…", en="The sport I enjoy most is…",
            pt="O esporte que mais gosto é…", fr="Le sport que j'aime le plus est…",
            de="Der Sport, den ich am meisten genieße, ist…", it="Lo sport che preferisco è…",
            ru="Мой любимый вид спорта…", sv="Sporten jag gillar mest är…",
            nl="De sport waar ik het meest van geniet is…", zh="我最喜欢的运动是…",
            hi="जिस खेल का मैं सबसे ज़्यादा आनंद लेता हूँ…", bn="যে খেলাটি সবচেয়ে উপভোগ করি…",
            ja="一番楽しめるスポーツは…", ko="가장 즐기는 스포츠는…",
            ar="الرياضة التي أستمتع بها أكثر هي…", sw="Mchezo ninaoufurahia zaidi ni…",
            ha="Wasannin da na fi jin daɗi da shi shi ne…", am="በጣም የምደሰትበት ስፖርት…",
            tl="Ang sport na pinakanasisiyahan ako ay…", ms="Sukan yang paling saya nikmati ialah…",
            mi="Ko te hākinakina e tino pārekareka ana ki ahau ko…",
        ),
    },
    {
        "value": "happiest_place",
        "order": 21,
        "translations": L(
            es="El lugar donde me siento más feliz es…", en="The place where I feel happiest is…",
            pt="O lugar onde me sinto mais feliz é…", fr="L'endroit où je me sens le plus heureux est…",
            de="Der Ort, an dem ich mich am glücklichsten fühle, ist…", it="Il luogo dove mi sento più felice è…",
            ru="Место, где я счастливее всего…", sv="Platsen där jag känner mig lyckligast är…",
            nl="De plek waar ik me het gelukkigst voel is…", zh="让我感到最幸福的地方是…",
            hi="वह जगह जहाँ मैं सबसे खुश महसूस करता हूँ…", bn="যেখানে আমি সবচেয়ে সুখী বোধ করি…",
            ja="一番幸せを感じる場所は…", ko="가장 행복함을 느끼는 장소는…",
            ar="المكان الذي أشعر فيه بسعادة أكبر هو…", sw="Mahali ninapojisikia furaha zaidi ni…",
            ha="Wurin da na fi jin daɗin shi shi ne…", am="በጣም ደስተኛ የሚሰማኝ ቦታ…",
            tl="Ang lugar kung saan pinakamasaya ako ay…", ms="Tempat saya berasa paling gembira ialah…",
            mi="Ko te wāhi e tino harikoa ai ahau ko…",
        ),
    },
    {
        "value": "hidden_talent",
        "order": 22,
        "translations": L(
            es="Mi talento oculto es…", en="My hidden talent is…",
            pt="Meu talento oculto é…", fr="Mon talent caché est…",
            de="Mein verborgenes Talent ist…", it="Il mio talento nascosto è…",
            ru="Мой скрытый талант…", sv="Min dolda talang är…",
            nl="Mijn verborgen talent is…", zh="我隐藏的才艺是…",
            hi="मेरी छिपी प्रतिभा है…", bn="আমার লুকানো প্রতিভা…",
            ja="隠れた特技は…", ko="숨겨진 재능은…",
            ar="موهبتي الخفية هي…", sw="Kipaji changu cha siri ni…",
            ha="Ɓoyayyen baiwata shi ne…", am="የተደበቀ ችሎታዬ…",
            tl="Ang nakatago kong talento ay…", ms="Bakat tersembunyi saya ialah…",
            mi="Ko tāku pūkenga huna ko…",
        ),
    },
    {
        "value": "best_advice_got",
        "order": 23,
        "translations": L(
            es="El mejor consejo que me han dado es…", en="The best advice I've been given is…",
            pt="O melhor conselho que recebi é…", fr="Le meilleur conseil qu'on m'ait donné est…",
            de="Der beste Rat, den ich je bekam, ist…", it="Il miglior consiglio che ho ricevuto è…",
            ru="Лучший совет, который мне давали…", sv="Det bästa rådet jag fått är…",
            nl="Het beste advies dat ik kreeg is…", zh="别人给过我最好的建议是…",
            hi="मुझे मिला सबसे अच्छा सुझाव है…", bn="সেরা পরামর্শ যা পেয়েছি…",
            ja="もらった最高のアドバイスは…", ko="받아본 최고의 조언은…",
            ar="أفضل نصيحة تلقيتها هي…", sw="Ushauri bora niliowahi kupewa ni…",
            ha="Mafi kyawun shawarar da aka ba ni ita ce…", am="የተሰጠኝ ምርጥ ምክር…",
            tl="Ang pinakamagandang payong natanggap ko ay…", ms="Nasihat terbaik yang pernah saya terima ialah…",
            mi="Ko te tohutohu pai rawa atu kua tae mai ki ahau ko…",
        ),
    },
    {
        "value": "fav_drink",
        "order": 24,
        "translations": L(
            es="Mi bebida favorita es…", en="My favorite drink is…",
            pt="Minha bebida favorita é…", fr="Ma boisson préférée est…",
            de="Mein Lieblingsgetränk ist…", it="La mia bevanda preferita è…",
            ru="Мой любимый напиток…", sv="Min favoritdryck är…",
            nl="Mijn favoriete drankje is…", zh="我最喜欢的饮料是…",
            hi="मेरा पसंदीदा पेय है…", bn="আমার প্রিয় পানীয়…",
            ja="好きな飲み物は…", ko="가장 좋아하는 음료는…",
            ar="مشروبي المفضل هو…", sw="Kinywaji changu pendwa ni…",
            ha="Abin sha da na fi so shi ne…", am="የምወደው መጠጥ…",
            tl="Ang paborito kong inumin ay…", ms="Minuman kegemaran saya ialah…",
            mi="Ko tāku inu pai ko…",
        ),
    },
    {
        "value": "lang_to_learn",
        "order": 25,
        "translations": L(
            es="El idioma que me gustaría aprender es…", en="The language I'd like to learn is…",
            pt="O idioma que gostaria de aprender é…", fr="La langue que j'aimerais apprendre est…",
            de="Die Sprache, die ich gern lernen würde, ist…", it="La lingua che vorrei imparare è…",
            ru="Язык, который я хотел бы выучить…", sv="Språket jag skulle vilja lära mig är…",
            nl="De taal die ik zou willen leren is…", zh="我想学的语言是…",
            hi="जो भाषा सीखना चाहूंगा…", bn="যে ভাষাটি শিখতে চাই…",
            ja="学びたい言語は…", ko="배우고 싶은 언어는…",
            ar="اللغة التي أود تعلمها هي…", sw="Lugha ningependa kujifunza ni…",
            ha="Yaren da zan so in koya shi ne…", am="መማር የምፈልገው ቋንቋ…",
            tl="Ang wikang gusto kong matutuhan ay…", ms="Bahasa yang ingin saya pelajari ialah…",
            mi="Ko te reo e hiahia ana ahau ki te ako ko…",
        ),
    },
    {
        "value": "funniest_memory",
        "order": 26,
        "translations": L(
            es="Mi recuerdo más divertido es…", en="My funniest memory is…",
            pt="Minha memória mais engraçada é…", fr="Mon souvenir le plus drôle est…",
            de="Meine lustigste Erinnerung ist…", it="Il mio ricordo più divertente è…",
            ru="Моё самое смешное воспоминание…", sv="Mitt roligaste minne är…",
            nl="Mijn grappigste herinnering is…", zh="我最搞笑的回忆是…",
            hi="मेरी सबसे मज़ेदार याद है…", bn="আমার সবচেয়ে মজার স্মৃতি…",
            ja="一番面白い思い出は…", ko="가장 웃긴 추억은…",
            ar="أطرف ذكرى لدي هي…", sw="Kumbukumbu yangu ya kuchekesha zaidi ni…",
            ha="Tunawa mafi ban dariya a gareni shi ne…", am="በጣም አስቂኝ ትውስታዬ…",
            tl="Ang pinakanakakatawa kong alaala ay…", ms="Kenangan paling lucu saya ialah…",
            mi="Ko tāku maharatanga tino kata ko…",
        ),
    },
    {
        "value": "best_concert",
        "order": 27,
        "translations": L(
            es="El mejor concierto al que fui es…", en="The best concert I went to is…",
            pt="O melhor show que fui é…", fr="Le meilleur concert auquel j'ai assisté est…",
            de="Das beste Konzert, auf dem ich war, ist…", it="Il miglior concerto a cui sono andato è…",
            ru="Лучший концерт, на котором я был…", sv="Den bästa konserten jag varit på är…",
            nl="Het beste concert waar ik was is…", zh="我去过最棒的演唱会是…",
            hi="सबसे अच्छा कॉन्सर्ट जिसमें गया…", bn="সেরা কনসার্ট যেখানে গিয়েছি…",
            ja="行った最高のコンサートは…", ko="가본 최고의 콘서트는…",
            ar="أفضل حفل ذهبت إليه هو…", sw="Tamasha bora nililohudhuria ni…",
            ha="Mafi kyawun kide-kide da na je shi ne…", am="የሄድኩት ምርጥ ኮንሰርት…",
            tl="Ang pinakamagandang concert na pinuntahan ko ay…", ms="Konsert terbaik yang pernah saya pergi ialah…",
            mi="Ko te konohete pai rawa atu kua tae ahau ko…",
        ),
    },
    {
        "value": "fav_movie",
        "order": 28,
        "translations": L(
            es="Mi película favorita es…", en="My favorite movie is…",
            pt="Meu filme favorito é…", fr="Mon film préféré est…",
            de="Mein Lieblingsfilm ist…", it="Il mio film preferito è…",
            ru="Мой любимый фильм…", sv="Min favoritfilm är…",
            nl="Mijn favoriete film is…", zh="我最喜欢的电影是…",
            hi="मेरी पसंदीदा फिल्म है…", bn="আমার প্রিয় সিনেমা…",
            ja="好きな映画は…", ko="가장 좋아하는 영화는…",
            ar="فيلمي المفضل هو…", sw="Filamu yangu pendwa ni…",
            ha="Fim ɗin da na fi so shi ne…", am="የምወደው ፊልም…",
            tl="Ang paborito kong pelikula ay…", ms="Filem kegemaran saya ialah…",
            mi="Ko tāku kiriata pai ko…",
        ),
    },
    {
        "value": "hobby_never_quit",
        "order": 29,
        "translations": L(
            es="El hobby que nunca abandono es…", en="The hobby I never give up is…",
            pt="O hobby que nunca abandono é…", fr="Le passe-temps que je n'abandonne jamais est…",
            de="Das Hobby, das ich nie aufgebe, ist…", it="L'hobby che non abbandono mai è…",
            ru="Хобби, которое я никогда не брошу…", sv="Hobbyn jag aldrig ger upp är…",
            nl="De hobby die ik nooit opgeef is…", zh="我永远不会放弃的爱好是…",
            hi="वह शौक जो मैं कभी नहीं छोड़ता…", bn="যে শখ কখনো ছাড়ি না…",
            ja="ずっと続けている趣味は…", ko="절대 포기하지 않는 취미는…",
            ar="الهواية التي لا أتخلى عنها أبدًا هي…", sw="Burudani nisiyoiacha ni…",
            ha="Abin shaʼawa da ba zan taɓa dainawa ba shi ne…", am="በጭራሽ የማልተወው 취미…",
            tl="Ang libangang hindi ko sinusukuan ay…", ms="Hobi yang tidak pernah saya tinggalkan ialah…",
            mi="Ko te mahi whakangahau e kore rawa e whakarērea e au ko…",
        ),
    },
    {
        "value": "collect",
        "order": 30,
        "translations": L(
            es="Algo que colecciono es…", en="Something I collect is…",
            pt="Algo que coleciono é…", fr="Quelque chose que je collectionne est…",
            de="Etwas, das ich sammle, ist…", it="Qualcosa che colleziono è…",
            ru="Я коллекционирую…", sv="Något jag samlar på är…",
            nl="Iets wat ik verzamel is…", zh="我收藏的东西是…",
            hi="जो चीज़ मैं इकट्ठा करता हूँ…", bn="যা সংগ্রহ করি…",
            ja="集めているものは…", ko="수집하는 것은…",
            ar="شيء أجمعه هو…", sw="Kitu ninachokusanya ni…",
            ha="Abin da nake tarawa shi ne…", am="የምሰበስበው ነገር…",
            tl="Ang kinokolekta ko ay…", ms="Perkara yang saya kumpul ialah…",
            mi="Ko te mea e kohikohi ana ahau ko…",
        ),
    },
    {
        "value": "zodiac",
        "order": 31,
        "translations": L(
            es="Mi signo zodiacal es…", en="My zodiac sign is…",
            pt="Meu signo do zodíaco é…", fr="Mon signe du zodiaque est…",
            de="Mein Sternzeichen ist…", it="Il mio segno zodiacale è…",
            ru="Мой знак зодиака…", sv="Mitt stjärntecken är…",
            nl="Mijn sterrenbeeld is…", zh="我的星座是…",
            hi="मेरी राशि है…", bn="আমার রাশি…",
            ja="星座は…", ko="별자리는…",
            ar="برجي هو…", sw="Ishara yangu ya nyota ni…",
            ha="Alamar tauraro na shi ne…", am="የዞዲያክ ምልክቴ…",
            tl="Ang zodiac sign ko ay…", ms="Tanda zodiak saya ialah…",
            mi="Ko tāku tohu whetū ko…",
        ),
    },
    {
        "value": "top_emoji",
        "order": 32,
        "translations": L(
            es="El emoji que más uso es…", en="The emoji I use most is…",
            pt="O emoji que mais uso é…", fr="L'emoji que j'utilise le plus est…",
            de="Das Emoji, das ich am meisten nutze, ist…", it="L'emoji che uso di più è…",
            ru="Эмодзи, которое я использую чаще всего…", sv="Emojin jag använder mest är…",
            nl="De emoji die ik het meest gebruik is…", zh="我用得最多的表情是…",
            hi="जिस इमोजी का सबसे ज़्यादा इस्तेमाल करता हूँ…", bn="যে ইমোজি সবচেয়ে বেশি ব্যবহার করি…",
            ja="一番使う絵文字は…", ko="가장 많이 쓰는 이모지는…",
            ar="الإيموجي الذي أستخدمه أكثر هو…", sw="Emoji ninayotumia zaidi ni…",
            ha="Emoji da na fi amfani da shi shi ne…", am="በጣም የምጠቀመው ኢሞጂ…",
            tl="Ang emoji na madalas kong gamitin ay…", ms="Emoji yang paling saya guna ialah…",
            mi="Ko te karere-ahua e tino whakamahia ana e au ko…",
        ),
    },
    {
        "value": "comfort_food",
        "order": 33,
        "translations": L(
            es="Mi comida de confort es…", en="My comfort food is…",
            pt="Minha comida de conforto é…", fr="Mon aliment réconfortant est…",
            de="Mein Wohlfühlessen ist…", it="Il mio comfort food è…",
            ru="Моя еда для утешения…", sv="Min tröstmat är…",
            nl="Mijn comfortfood is…", zh="我的治愈系食物是…",
            hi="मेरा आरामदायक खाना है…", bn="আমার স্বস্তির খাবার…",
            ja="癒しの食べ物は…", ko="위로가 되는 음식은…",
            ar="طعامي المريح هو…", sw="Chakula changu cha faraja ni…",
            ha="Abincin da ke kwantar min da hankali shi ne…", am="የመጽናኛ ምግቤ…",
            tl="Ang comfort food ko ay…", ms="Makanan keselesaan saya ialah…",
            mi="Ko tāku kai whakamarie ko…",
        ),
    },
    {
        "value": "best_gift",
        "order": 34,
        "translations": L(
            es="El mejor regalo que recibí fue…", en="The best gift I received was…",
            pt="O melhor presente que recebi foi…", fr="Le meilleur cadeau que j'ai reçu était…",
            de="Das beste Geschenk, das ich bekam, war…", it="Il miglior regalo che ho ricevuto è stato…",
            ru="Лучший подарок, который я получал…", sv="Den bästa presenten jag fått var…",
            nl="Het beste cadeau dat ik kreeg was…", zh="收到过最好的礼物是…",
            hi="मिला सबसे अच्छा तोहफ़ा था…", bn="সেরা উপহার যা পেয়েছি…",
            ja="もらった最高のプレゼントは…", ko="받아본 최고의 선물은…",
            ar="أفضل هدية تلقيتها كانت…", sw="Zawadi bora niliyowahi kupokea ni…",
            ha="Mafi kyawun kyautar da na karɓa ita ce…", am="የተቀበልኩት ምርጥ ስጦታ…",
            tl="Ang pinakamagandang regalong natanggap ko ay…", ms="Hadiah terbaik yang pernah saya terima ialah…",
            mi="Ko te koha pai rawa atu kua tae mai ki ahau ko…",
        ),
    },
    {
        "value": "fav_season",
        "order": 35,
        "translations": L(
            es="Mi estación del año favorita es…", en="My favorite season is…",
            pt="Minha estação favorita é…", fr="Ma saison préférée est…",
            de="Meine Lieblingsjahreszeit ist…", it="La mia stagione preferita è…",
            ru="Моё любимое время года…", sv="Min favoritsäsong är…",
            nl="Mijn favoriete seizoen is…", zh="我最喜欢的季节是…",
            hi="मेरा पसंदीदा मौसम है…", bn="আমার প্রিয় ঋতু…",
            ja="好きな季節は…", ko="가장 좋아하는 계절은…",
            ar="فصلي المفضل هو…", sw="Msimu ninaoupenda ni…",
            ha="Lokacin da na fi so shi ne…", am="የምወደው ወቅት…",
            tl="Ang paborito kong panahon ay…", ms="Musim kegemaran saya ialah…",
            mi="Ko tāku wā pai ko…",
        ),
    },
    {
        "value": "place_to_visit",
        "order": 36,
        "translations": L(
            es="El lugar que quiero visitar es…", en="The place I want to visit is…",
            pt="O lugar que quero visitar é…", fr="L'endroit que je veux visiter est…",
            de="Der Ort, den ich besuchen will, ist…", it="Il luogo che voglio visitare è…",
            ru="Место, которое я хочу посетить…", sv="Platsen jag vill besöka är…",
            nl="De plek die ik wil bezoeken is…", zh="我想去的地方是…",
            hi="वह जगह जहाँ जाना चाहता हूँ…", bn="যে জায়গায় যেতে চাই…",
            ja="訪れたい場所は…", ko="방문하고 싶은 장소는…",
            ar="المكان الذي أريد زيارته هو…", sw="Mahali ninapotaka kutembelea ni…",
            ha="Wurin da nake son ziyarta shi ne…", am="መጎብኘት የምፈልገው ቦታ…",
            tl="Ang lugar na gusto kong puntahan ay…", ms="Tempat yang ingin saya lawati ialah…",
            mi="Ko te wāhi e hiahia ana ahau ki te toro ko…",
        ),
    },
    {
        "value": "song_never_tired",
        "order": 37,
        "translations": L(
            es="Mi canción que nunca me canso de escuchar es…", en="My song I never get tired of listening to is…",
            pt="Minha música que nunca canso de ouvir é…", fr="Ma chanson que je ne me lasse jamais d'écouter est…",
            de="Mein Song, den ich nie satt höre, ist…", it="La mia canzone che non mi stanco mai di ascoltare è…",
            ru="Песня, которая мне никогда не надоедает…", sv="Min låt jag aldrig tröttnar på är…",
            nl="Mijn nummer dat ik nooit beu word is…", zh="我百听不厌的歌是…",
            hi="वह गाना जिससे कभी नहीं थकता…", bn="যে গান কখনো শুনে ক্লান্ত হই না…",
            ja="何度聴いても飽きない曲は…", ko="아무리 들어도 질리지 않는 노래는…",
            ar="أغنيتي التي لا أمل من سماعها هي…", sw="Wimbo wangu nisiochoka kuusikiliza ni…",
            ha="Waƙata da ba na gaji da jin ta ita ce…", am="ማዳመጥ የማልሰለችበት ዘፈኔ…",
            tl="Ang kanta kong hindi nakakasawang pakinggan ay…", ms="Lagu saya yang tidak pernah jemu didengar ialah…",
            mi="Ko tāku waiata e kore rawa e hōhā ai ahau ko…",
        ),
    },
    {
        "value": "best_weekend",
        "order": 38,
        "translations": L(
            es="El mejor plan de fin de semana es…", en="The best weekend plan is…",
            pt="O melhor plano de fim de semana é…", fr="Le meilleur plan de week-end est…",
            de="Der beste Wochenendplan ist…", it="Il miglior piano per il weekend è…",
            ru="Лучший план на выходные…", sv="Den bästa helgplanen är…",
            nl="Het beste weekendplan is…", zh="最棒的周末计划是…",
            hi="सबसे अच्छा वीकेंड प्लान है…", bn="সেরা সাপ্তাহিক ছুটির পরিকল্পনা…",
            ja="最高の週末プランは…", ko="최고의 주말 계획은…",
            ar="أفضل خطة لعطلة نهاية الأسبوع هي…", sw="Mpango bora wa wikendi ni…",
            ha="Mafi kyawun shirin karshen mako shi ne…", am="ምርጥ የሳምንት መጨረሻ ዕቅድ…",
            tl="Ang pinakamagandang plano sa weekend ay…", ms="Rancangan hujung minggu terbaik ialah…",
            mi="Ko te mahere mutunga wiki pai rawa atu ko…",
        ),
    },
    {
        "value": "fav_videogame",
        "order": 39,
        "translations": L(
            es="Mi videojuego favorito es…", en="My favorite video game is…",
            pt="Meu videogame favorito é…", fr="Mon jeu vidéo préféré est…",
            de="Mein Lieblingsvideospiel ist…", it="Il mio videogioco preferito è…",
            ru="Моя любимая видеоигра…", sv="Mitt favoritspel är…",
            nl="Mijn favoriete videogame is…", zh="我最喜欢的电子游戏是…",
            hi="मेरा पसंदीदा वीडियो गेम है…", bn="আমার প্রিয় ভিডিও গেম…",
            ja="好きなゲームは…", ko="가장 좋아하는 비디오 게임은…",
            ar="لعبة الفيديو المفضلة لدي هي…", sw="Mchezo wangu pendwa wa video ni…",
            ha="Wasannin bidiyo da na fi so shi ne…", am="የምወደው የቪዲዮ ጨዋታ…",
            tl="Ang paborito kong video game ay…", ms="Permainan video kegemaran saya ialah…",
            mi="Ko tāku kēmu ataata pai ko…",
        ),
    },
    {
        "value": "animal_identify",
        "order": 40,
        "translations": L(
            es="El animal con el que más me identifico es…", en="The animal I identify with most is…",
            pt="O animal com que mais me identifico é…", fr="L'animal auquel je m'identifie le plus est…",
            de="Das Tier, mit dem ich mich am meisten identifiziere, ist…", it="L'animale con cui mi identifico di più è…",
            ru="Животное, с которым я себя ассоциирую…", sv="Djuret jag identifierar mig mest med är…",
            nl="Het dier waarmee ik me het meest identificeer is…", zh="最能代表我的动物是…",
            hi="वह जानवर जिससे सबसे ज़्यादा जुड़ाव महसूस करता हूँ…", bn="যে প্রাণীর সাথে সবচেয়ে বেশি একাত্ম বোধ করি…",
            ja="一番共感する動物は…", ko="가장 동일시하는 동물은…",
            ar="الحيوان الذي أتماهى معه أكثر هو…", sw="Mnyama ninayejihusisha naye zaidi ni…",
            ha="Dabbar da na fi gane kaina da ita ita ce…", am="እንስሳው እኔን የሚወክለው…",
            tl="Ang hayop na pinakakakilanlan ko ay…", ms="Haiwan yang paling saya rasai ialah…",
            mi="Ko te kararehe e tino piri ana ki ahau ko…",
        ),
    },
    {
        "value": "ideal_breakfast",
        "order": 41,
        "translations": L(
            es="Mi desayuno ideal es…", en="My ideal breakfast is…",
            pt="Meu café da manhã ideal é…", fr="Mon petit-déjeuner idéal est…",
            de="Mein ideales Frühstück ist…", it="La mia colazione ideale è…",
            ru="Мой идеальный завтрак…", sv="Min idealiska frukost är…",
            nl="Mijn ideale ontbijt is…", zh="我理想的早餐是…",
            hi="मेरा आदर्श नाश्ता है…", bn="আমার আদর্শ প্রাতঃরাশ…",
            ja="理想の朝食は…", ko="이상적인 아침 식사는…",
            ar="فطوري المثالي هو…", sw="Kifungua kinywa changu bora ni…",
            ha="Karin kumallo da ya fi dacewa a gare ni shi ne…", am="የእኔ ተስማሚ ቁርስ…",
            tl="Ang perpekto kong almusal ay…", ms="Sarapan ideal saya ialah…",
            mi="Ko tāku parakuihi tino pai ko…",
        ),
    },
    {
        "value": "best_language",
        "order": 42,
        "translations": L(
            es="El idioma que hablo mejor es…", en="The language I speak best is…",
            pt="O idioma que falo melhor é…", fr="La langue que je parle le mieux est…",
            de="Die Sprache, die ich am besten spreche, ist…", it="La lingua che parlo meglio è…",
            ru="Язык, на котором я говорю лучше всего…", sv="Språket jag talar bäst är…",
            nl="De taal die ik het best spreek is…", zh="我说得最好的语言是…",
            hi="जो भाषा सबसे अच्छी बोलता हूँ…", bn="যে ভাষাটি সবচেয়ে ভালো বলি…",
            ja="一番得意な言語は…", ko="가장 잘하는 언어는…",
            ar="اللغة التي أتحدثها بإتقان هي…", sw="Lugha ninayoizungumza vizuri ni…",
            ha="Yaren da na fi iya shi ne…", am="በጣም сайн የምናገረው ቋንቋ…",
            tl="Ang wikang pinakamahusay kong sinasalita ay…", ms="Bahasa yang paling saya fasih ialah…",
            mi="Ko te reo e tino matatau ana ahau ko…",
        ),
    },
    {
        "value": "fav_app",
        "order": 43,
        "translations": L(
            es="Mi aplicación favorita es…", en="My favorite app is…",
            pt="Meu aplicativo favorito é…", fr="Mon application préférée est…",
            de="Meine Lieblingsapp ist…", it="La mia app preferita è…",
            ru="Моё любимое приложение…", sv="Min favoritapp är…",
            nl="Mijn favoriete app is…", zh="我最喜欢的应用是…",
            hi="मेरा पसंदीदा ऐप है…", bn="আমার প্রিয় অ্যাপ…",
            ja="好きなアプリは…", ko="가장 좋아하는 앱은…",
            ar="تطبيقي المفضل هو…", sw="Programu yangu pendwa ni…",
            ha="Manajan da na fi so shi ne…", am="የምወደው መተግበሪያ…",
            tl="Ang paborito kong app ay…", ms="Aplikasi kegemaran saya ialah…",
            mi="Ko tāku taupānga pai ko…",
        ),
    },
    {
        "value": "best_childhood",
        "order": 44,
        "translations": L(
            es="El mejor recuerdo de la infancia es…", en="The best childhood memory is…",
            pt="A melhor memória da infância é…", fr="Le meilleur souvenir d'enfance est…",
            de="Die schönste Kindheitserinnerung ist…", it="Il miglior ricordo d'infanzia è…",
            ru="Лучшее детское воспоминание…", sv="Det bästa barndomsminnet är…",
            nl="Mijn mooiste jeugdherinnering is…", zh="最美好的童年回忆是…",
            hi="बचपन की सबसे अच्छी याद है…", bn="শৈশবের সেরা স্মৃতি…",
            ja="最高の子供時代の思い出は…", ko="가장 좋은 어린 시절 추억은…",
            ar="أجمل ذكرى طفولة هي…", sw="Kumbukumbu bora ya utotoni ni…",
            ha="Tunawa mafi kyau na kuruciya shi ne…", am="የልጅነት ምርጥ ትውስታ…",
            tl="Ang pinakamagandang alaala ng kabataan ay…", ms="Kenangan kanak-kanak terbaik ialah…",
            mi="Ko te maharatanga pai rawa atu o te tamarikitanga ko…",
        ),
    },
    {
        "value": "fav_dessert",
        "order": 45,
        "translations": L(
            es="Mi postre favorito es…", en="My favorite dessert is…",
            pt="Minha sobremesa favorita é…", fr="Mon dessert préféré est…",
            de="Mein Lieblingsdessert ist…", it="Il mio dolce preferito è…",
            ru="Мой любимый десерт…", sv="Min favoritefterrätt är…",
            nl="Mijn favoriete dessert is…", zh="我最喜欢的甜点是…",
            hi="मेरी पसंदीदा मिठाई है…", bn="আমার প্রিয় মিষ্টান্ন…",
            ja="好きなデザートは…", ko="가장 좋아하는 디저트는…",
            ar="الحلوى المفضلة لدي هي…", sw="Kitindamlo changu pendwa ni…",
            ha="Abin zaki da na fi so shi ne…", am="የምወደው ጣፋጭ ምግብ…",
            tl="Ang paborito kong panghimagas ay…", ms="Pencuci mulut kegemaran saya ialah…",
            mi="Ko tāku mea reka pai ko…",
        ),
    },
    {
        "value": "sport_to_try",
        "order": 46,
        "translations": L(
            es="El deporte que me gustaría probar es…", en="The sport I'd like to try is…",
            pt="O esporte que gostaria de experimentar é…", fr="Le sport que j'aimerais essayer est…",
            de="Die Sportart, die ich gern ausprobieren würde, ist…", it="Lo sport che vorrei provare è…",
            ru="Вид спорта, который я хотел бы попробовать…", sv="Sporten jag skulle vilja prova är…",
            nl="De sport die ik zou willen proberen is…", zh="我想尝试的运动是…",
            hi="जो खेल आज़माना चाहूंगा…", bn="যে খেলাটি চেষ্টা করতে চাই…",
            ja="試してみたいスポーツは…", ko="해보고 싶은 스포츠는…",
            ar="الرياضة التي أود تجربتها هي…", sw="Mchezo ningependa kujaribu ni…",
            ha="Wasannin da zan so in gwada shi ne…", am="መሞከር የምፈልገው ስፖርት…",
            tl="Ang sport na gusto kong subukan ay…", ms="Sukan yang ingin saya cuba ialah…",
            mi="Ko te hākinakina e hiahia ana ahau ki te whakamātau ko…",
        ),
    },
    {
        "value": "movie_recommend",
        "order": 47,
        "translations": L(
            es="Mi película que siempre recomiendo es…", en="My movie I always recommend is…",
            pt="Meu filme que sempre recomendo é…", fr="Mon film que je recommande toujours est…",
            de="Mein Film, den ich immer empfehle, ist…", it="Il mio film che consiglio sempre è…",
            ru="Фильм, который я всегда рекомендую…", sv="Min film jag alltid rekommenderar är…",
            nl="Mijn film die ik altijd aanraad is…", zh="我总会推荐的电影是…",
            hi="वह फिल्म जिसकी हमेशा सिफारिश करता हूँ…", bn="যে সিনেমাটি সবসময় সুপারিশ করি…",
            ja="いつもおすすめする映画は…", ko="항상 추천하는 영화는…",
            ar="فيلمي الذي أوصي به دائمًا هو…", sw="Filamu yangu ninayopendekeza kila wakati ni…",
            ha="Fim ɗin da kullum nake ba da shawara shi ne…", am="ሁልጊዜ የምመክረው ፊልሜ…",
            tl="Ang pelikula kong laging inirerekomenda ay…", ms="Filem saya yang selalu disyorkan ialah…",
            mi="Ko tāku kiriata e taunaki tonu ana ahau ko…",
        ),
    },
    {
        "value": "place_to_live",
        "order": 48,
        "translations": L(
            es="El lugar donde me gustaría vivir es…", en="The place I'd like to live is…",
            pt="O lugar onde gostaria de morar é…", fr="L'endroit où j'aimerais vivre est…",
            de="Der Ort, an dem ich gern leben würde, ist…", it="Il luogo dove mi piacerebbe vivere è…",
            ru="Место, где я хотел бы жить…", sv="Platsen där jag skulle vilja bo är…",
            nl="De plek waar ik zou willen wonen is…", zh="我想住的地方是…",
            hi="वह जगह जहाँ रहना चाहूंगा…", bn="যে জায়গায় থাকতে চাই…",
            ja="住んでみたい場所は…", ko="살고 싶은 장소는…",
            ar="المكان الذي أود العيش فيه هو…", sw="Mahali ningependa kuishi ni…",
            ha="Wurin da zan so in zauna shi ne…", am="መኖር የምፈልገው ቦታ…",
            tl="Ang lugar na gusto kong tirhan ay…", ms="Tempat yang ingin saya diami ialah…",
            mi="Ko te wāhi e hiahia ana ahau ki te noho ko…",
        ),
    },
    {
        "value": "best_dish_cook",
        "order": 49,
        "translations": L(
            es="Mi comida que sé cocinar mejor es…", en="My food I cook best is…",
            pt="Minha comida que sei cozinhar melhor é…", fr="Mon plat que je cuisine le mieux est…",
            de="Mein Gericht, das ich am besten koche, ist…", it="Il mio piatto che cucino meglio è…",
            ru="Блюдо, которое я готовлю лучше всего…", sv="Min maträtt jag lagar bäst är…",
            nl="Mijn gerecht dat ik het best kook is…", zh="我最拿手的菜是…",
            hi="वह खाना जो सबसे अच्छा बनाता हूँ…", bn="যে খাবার সবচেয়ে ভালো রাঁধতে পারি…",
            ja="一番得意な料理は…", ko="가장 잘 만드는 요리는…",
            ar="طبقي الذي أجيده أكثر هو…", sw="Chakula ninachopika vizuri ni…",
            ha="Abincin da na fi iya dafawa shi ne…", am="በጣም сайн የማበስለው ምግቤ…",
            tl="Ang pagkaing pinakamahusay kong lutuin ay…", ms="Masakan yang paling saya pandai ialah…",
            mi="Ko tāku kai e tino mohio ana ahau ki te tunu ko…",
        ),
    },
    {
        "value": "best_day",
        "order": 50,
        "translations": L(
            es="El mejor día de mi vida fue…", en="The best day of my life was…",
            pt="O melhor dia da minha vida foi…", fr="Le meilleur jour de ma vie était…",
            de="Der beste Tag meines Lebens war…", it="Il giorno più bello della mia vita è stato…",
            ru="Лучший день в моей жизни…", sv="Den bästa dagen i mitt liv var…",
            nl="De beste dag van mijn leven was…", zh="我人生中最棒的一天是…",
            hi="मेरे जीवन का सबसे अच्छा दिन था…", bn="আমার জীবনের সেরা দিন ছিল…",
            ja="人生最高の日は…", ko="인생 최고의 날은…",
            ar="أجمل يوم في حياتي كان…", sw="Siku bora ya maisha yangu ilikuwa…",
            ha="Rana mafi kyau a rayuwata ita ce…", am="የሕይወቴ ምርጥ ቀን…",
            tl="Ang pinakamagandang araw ng buhay ko ay…", ms="Hari terbaik dalam hidup saya ialah…",
            mi="Ko te rā pai rawa atu o tōku oranga ko…",
        ),
    },
    {
        "value": "cheers_up_song",
        "order": 51,
        "translations": L(
            es="Mi canción que me anima siempre es…", en="My song that always cheers me up is…",
            pt="Minha música que sempre me anima é…", fr="Ma chanson qui me remonte toujours le moral est…",
            de="Mein Song, der mich immer aufmuntert, ist…", it="La mia canzone che mi tira sempre su è…",
            ru="Песня, которая меня всегда бодрит…", sv="Min låt som alltid piggar upp mig är…",
            nl="Mijn nummer dat me altijd opvrolijkt is…", zh="总能让我振作的歌是…",
            hi="वह गाना जो हमेशा खुश कर देता है…", bn="যে গান সবসময় আমাকে উজ্জীবিত করে…",
            ja="いつも元気にしてくれる曲は…", ko="날 항상 기운 나게 하는 노래는…",
            ar="أغنيتي التي ترفع معنوياتي دائمًا هي…", sw="Wimbo wangu unaonichangamsha kila wakati ni…",
            ha="Waƙata da kullum take faranta mini rai ita ce…", am="ሁልጊዜ የሚያስደስተኝ ዘፈኔ…",
            tl="Ang kanta kong laging nagpapaganda ng loob ko ay…", ms="Lagu saya yang selalu menceriakan ialah…",
            mi="Ko tāku waiata e whakamanawa tonu ana i ahau ko…",
        ),
    },
    {
        "value": "habit_never_change",
        "order": 52,
        "translations": L(
            es="El hábito que nunca cambio es…", en="The habit I never change is…",
            pt="O hábito que nunca mudo é…", fr="L'habitude que je ne change jamais est…",
            de="Die Gewohnheit, die ich nie ändere, ist…", it="L'abitudine che non cambio mai è…",
            ru="Привычка, которую я никогда не меняю…", sv="Vanan jag aldrig ändrar är…",
            nl="De gewoonte die ik nooit verander is…", zh="我从不改变的习惯是…",
            hi="वह आदत जो कभी नहीं बदलता…", bn="যে অভ্যাস কখনো বদলাই না…",
            ja="絶対に変えない習慣は…", ko="절대 바꾸지 않는 습관은…",
            ar="العادة التي لا أغيرها أبدًا هي…", sw="Tabia nisiyoibadilisha ni…",
            ha="Al'adar da ba na canzawa ita ce…", am="በጭራሽ የማልቀይረው ልማድ…",
            tl="Ang gawi na hindi ko binabago ay…", ms="Tabiat yang tidak pernah saya ubah ialah…",
            mi="Ko te ritenga e kore rawa e hurihia e au ko…",
        ),
    },
    {
        "value": "series_rewatch",
        "order": 53,
        "translations": L(
            es="Mi serie que puedo ver mil veces es…", en="My series I can watch a thousand times is…",
            pt="Minha série que posso assistir mil vezes é…", fr="Ma série que je peux regarder mille fois est…",
            de="Meine Serie, die ich tausendmal sehen kann, ist…", it="La mia serie che posso guardare mille volte è…",
            ru="Сериал, который я могу смотреть тысячу раз…", sv="Min serie jag kan se tusen gånger är…",
            nl="Mijn serie die ik duizend keer kan kijken is…", zh="我能刷一千遍的剧是…",
            hi="वह सीरीज़ जिसे हज़ार बार देख सकता हूँ…", bn="যে সিরিজ হাজার বার দেখতে পারি…",
            ja="千回見られるドラマは…", ko="천 번 봐도 되는 드라마는…",
            ar="مسلسلي الذي يمكنني مشاهدته ألف مرة هو…", sw="Mfululizo ninaoweza kutazama mara elfu ni…",
            ha="Jerin shirye-shiryen da zan iya kallo sau dubu shi ne…", am="ሺህ ጊዜ መመልከት የምችለው ተከታታይ ፊልሜ…",
            tl="Ang serye kong kayang panoorin nang libong beses ay…", ms="Siri saya yang boleh ditonton seribu kali ialah…",
            mi="Ko tāku whakaari e taea ai te mātakitaki kotahi mano ngā wā ko…",
        ),
    },
    {
        "value": "disconnect_place",
        "order": 54,
        "translations": L(
            es="El lugar donde me desconecto es…", en="The place where I disconnect is…",
            pt="O lugar onde me desconecto é…", fr="L'endroit où je me déconnecte est…",
            de="Der Ort, an dem ich abschalte, ist…", it="Il luogo dove mi disconnetto è…",
            ru="Место, где я отключаюсь…", sv="Platsen där jag kopplar av är…",
            nl="De plek waar ik me afsluit is…", zh="让我断网放空的地方是…",
            hi="वह जगह जहाँ मैं कट जाता हूँ…", bn="যেখানে আমি বিচ্ছিন্ন হই…",
            ja="デジタルデトックスする場所は…", ko="나를 disconnect하는 장소는…",
            ar="المكان الذي أنفصل فيه هو…", sw="Mahali ninapojitenga ni…",
            ha="Wurin da nake keɓewa shi ne…", am="የምዘጋበት ቦታ…",
            tl="Ang lugar kung saan ako nagdi-disconnect ay…", ms="Tempat saya memutuskan hubungan ialah…",
            mi="Ko te wāhi e momotu ai ahau ko…",
        ),
    },
    {
        "value": "drink_always",
        "order": 55,
        "translations": L(
            es="Mi bebida que nunca falta es…", en="My drink that never runs out is…",
            pt="Minha bebida que nunca falta é…", fr="Ma boisson qui ne manque jamais est…",
            de="Mein Getränk, das nie ausgeht, ist…", it="La mia bevanda che non manca mai è…",
            ru="Напиток, который у меня не заканчивается…", sv="Min dryck som aldrig tar slut är…",
            nl="Mijn drankje dat nooit op is…", zh="我家从不断货的饮料是…",
            hi="वह पेय जो कभी खत्म नहीं होता…", bn="যে পানীয় কখনো শেষ হয় না…",
            ja="常備している飲み物は…", ko="절대 떨어지지 않는 음료는…",
            ar="مشروبي الذي لا ينفد أبدًا هو…", sw="Kinywaji changu kisichoisha ni…",
            ha="Abin sha da ba ya ƙarewa a gareni shi ne…", am="በጭራሽ የማያልቅ መጠθዬ…",
            tl="Ang inumin kong hindi nauubos ay…", ms="Minuman saya yang tidak pernah habis ialah…",
            mi="Ko tāku inu e kore rawa e pau ko…",
        ),
    },
    {
        "value": "advice_to_give",
        "order": 56,
        "translations": L(
            es="El mejor consejo que daría es…", en="The best advice I'd give is…",
            pt="O melhor conselho que daria é…", fr="Le meilleur conseil que je donnerais est…",
            de="Der beste Rat, den ich geben würde, ist…", it="Il miglior consiglio che darei è…",
            ru="Лучший совет, который я дал бы…", sv="Det bästa rådet jag skulle ge är…",
            nl="Het beste advies dat ik zou geven is…", zh="我会给出的最好建议是…",
            hi="सबसे अच्छी सलाह जो दूंगा…", bn="সেরা পরামর্শ যা দেব…",
            ja="あげたい最高のアドバイスは…", ko="해주고 싶은 최고의 조언은…",
            ar="أفضل نصيحة سأقدمها هي…", sw="Ushauri bora ningetoa ni…",
            ha="Mafi kyawun shawarar da zan bayar ita ce…", am="የምሰጠው ምርጥ ምክር…",
            tl="Ang pinakamagandang payong ibibigay ko ay…", ms="Nasihat terbaik yang akan saya berikan ialah…",
            mi="Ko te tohutohu pai rawa atu ka hoatu e au ko…",
        ),
    },
    {
        "value": "romantic_memory",
        "order": 57,
        "translations": L(
            es="Mi recuerdo más romántico es…", en="My most romantic memory is…",
            pt="Minha memória mais romântica é…", fr="Mon souvenir le plus romantique est…",
            de="Meine romantischste Erinnerung ist…", it="Il mio ricordo più romantico è…",
            ru="Моё самое романтичное воспоминание…", sv="Mitt mest romantiska minne är…",
            nl="Mijn meest romantische herinnering is…", zh="我最浪漫的回忆是…",
            hi="मेरी सबसे रोमांटिक याद है…", bn="আমার সবচেয়ে রোমান্টিক স্মৃতি…",
            ja="最もロマンチックな思い出は…", ko="가장 로맨틱한 추억은…",
            ar="أكثر ذكرى رومانسية لدي هي…", sw="Kumbukumbu yangu ya kimapenzi zaidi ni…",
            ha="Tunawa mafi soyayya a gareni shi ne…", am="በጣም የፍቅር ትውስታዬ…",
            tl="Ang pinakaromantikong alaala ko ay…", ms="Kenangan paling romantik saya ialah…",
            mi="Ko tāku maharatanga tino whaiāipo ko…",
        ),
    },
    {
        "value": "hobby_to_learn",
        "order": 58,
        "translations": L(
            es="El hobby que quiero aprender es…", en="The hobby I want to learn is…",
            pt="O hobby que quero aprender é…", fr="Le passe-temps que je veux apprendre est…",
            de="Das Hobby, das ich lernen will, ist…", it="L'hobby che voglio imparare è…",
            ru="Хобби, которому я хочу научиться…", sv="Hobbyn jag vill lära mig är…",
            nl="De hobby die ik wil leren is…", zh="我想学的爱好是…",
            hi="वह शौक जो सीखना चाहता हूँ…", bn="যে শখ শিখতে চাই…",
            ja="学びたい趣味は…", ko="배우고 싶은 취미는…",
            ar="الهواية التي أريد تعلمها هي…", sw="Burudani ninayotaka kujifunza ni…",
            ha="Abin shaʼawa da nake son koya shi ne…", am="መማር የምፈልገው 취미…",
            tl="Ang libangang gusto kong matutuhan ay…", ms="Hobi yang ingin saya pelajari ialah…",
            mi="Ko te mahi whakangahau e hiahia ana ahau ki te ako ko…",
        ),
    },
    {
        "value": "dance_song",
        "order": 59,
        "translations": L(
            es="Mi canción que me hace bailar es…", en="My song that makes me dance is…",
            pt="Minha música que me faz dançar é…", fr="Ma chanson qui me fait danser est…",
            de="Mein Song, der mich tanzen lässt, ist…", it="La mia canzone che mi fa ballare è…",
            ru="Песня, под которую я танцую…", sv="Min låt som får mig att dansa är…",
            nl="Mijn nummer waarop ik dan is…", zh="让我忍不住跳舞的歌是…",
            hi="वह गाना जिस पर नाच उठता हूँ…", bn="যে গানে নেচে উঠি…",
            ja="踊りだしたくなる曲は…", ko="나를 춤추게 하는 노래는…",
            ar="أغنيتي التي تجعلني أرقص هي…", sw="Wimbo wangu unaonichezesha ni…",
            ha="Waƙata da take sa ni rawa ita ce…", am="የሚያጨፈርኝ ዘፈኔ…",
            tl="Ang kanta kong nakapagpapasayaw sa akin ay…", ms="Lagu saya yang membuat saya menari ialah…",
            mi="Ko tāku waiata e whakakanikani ana i ahau ko…",
        ),
    },
    {
        "value": "inspiring_place",
        "order": 60,
        "translations": L(
            es="El lugar que me inspira es…", en="The place that inspires me is…",
            pt="O lugar que me inspira é…", fr="L'endroit qui m'inspire est…",
            de="Der Ort, der mich inspiriert, ist…", it="Il luogo che mi ispira è…",
            ru="Место, которое меня вдохновляет…", sv="Platsen som inspirerar mig är…",
            nl="De plek die me inspireert is…", zh="给我灵感的地方是…",
            hi="वह जगह जो मुझे प्रेरित करती है…", bn="যে জায়গা আমাকে অনুপ্রাণিত করে…",
            ja="インスピレーションをもらう場所は…", ko="영감을 주는 장소는…",
            ar="المكان الذي يلهمني هو…", sw="Mahali panaponihamasisha ni…",
            ha="Wurin da ke ba ni kwarin gwiwa shi ne…", am="የሚያነሳሳኝ ቦታ…",
            tl="Ang lugar na nagbibigay-inspirasyon sa akin ay…", ms="Tempat yang memberi inspirasi kepada saya ialah…",
            mi="Ko te wāhi e whakaohooho ana i ahau ko…",
        ),
    },
    {
        "value": "food_never_refuse",
        "order": 61,
        "translations": L(
            es="Mi comida que nunca rechazo es…", en="My food I never refuse is…",
            pt="Minha comida que nunca recuso é…", fr="Mon plat que je ne refuse jamais est…",
            de="Mein Essen, das ich nie ablehne, ist…", it="Il mio cibo che non rifiuto mai è…",
            ru="Еда, от которой я никогда не отказываюсь…", sv="Min mat jag aldrig tackar nej till är…",
            nl="Mijn eten dat ik nooit afsla is…", zh="我从不拒绝的食物是…",
            hi="वह खाना जिसे कभी मना नहीं करता…", bn="যে খাবার কখনো ফিরিয়ে দিই না…",
            ja="絶対に断らない食べ物は…", ko="절대 거절하지 않는 음식은…",
            ar="طعامي الذي لا أرفضه أبدًا هو…", sw="Chakula nisichokataa ni…",
            ha="Abincin da ba na ƙi shi ne…", am="በጭራሽ የማልቀበለው ምግብ…",
            tl="Ang pagkaing hindi ko tinatanggihan ay…", ms="Makanan saya yang tidak pernah ditolak ialah…",
            mi="Ko tāku kai e kore rawa e paopao ai ahau ko…",
        ),
    },
]

# Typo guard for accidental non-keyword arguments
for _item in TEXTS:
    assert set(_item["translations"]) == set(LANGS), _item["value"]

_VALUES = [item["value"] for item in TEXTS]
assert len(_VALUES) == len(set(_VALUES)), "duplicate seed values"
assert len(TEXTS) == 62, f"expected 62 texts, got {len(TEXTS)}"


async def main() -> None:
    await init_db()
    created = 0
    updated = 0
    for item in TEXTS:
        value = item["value"]
        order = item["order"]
        translations = item["translations"]

        existing = await SystemOption.find_one(
            SystemOption.category == "profile_prompts_section",
            SystemOption.value == value,
        )

        doc_data = {
            "category": "profile_prompts_section",
            "value": value,
            "label": translations["es"],
            "order": order,
            "is_active": True,
        }
        for lang in LANGS:
            doc_data[f"label_{lang}"] = translations.get(lang, "")

        if existing:
            for key, val in doc_data.items():
                setattr(existing, key, val)
            await existing.save()
            updated += 1
        else:
            await SystemOption(**doc_data).insert()
            created += 1

    print(
        f"seed_profile_prompts_section: created {created}, "
        f"updated {updated}, total {len(TEXTS)}"
    )


if __name__ == "__main__":
    asyncio.run(main())
