"""
Seed the `profile_location_section` system options catalog for UI texts in the
Location & Scope section.

Keys resolve as profile.location.* (flat + badge.* nested via dots).

Idempotent: upserts every value so re-running refreshes translations.
Run inside the backend container:
    docker exec -w /app redthread-backend python seed/seed_profile_location_section.py
"""

import asyncio
import os
import sys

# Add the project root to sys.path
sys.path.append(os.getcwd())

from src.core.database import init_db
from src.models.system_options import SystemOption

LANGS = [
    "es", "en", "pt", "fr", "de", "it", "ru", "sv", "nl", "zh",
    "hi", "bn", "ja", "ko", "ar", "sw", "ha", "am", "tl", "ms", "mi",
]


def L(**kw) -> dict:
    """Language-specific text. Raises if any supported language is missing."""
    missing = [lang for lang in LANGS if lang not in kw]
    if missing:
        raise ValueError(f"missing languages: {missing}")
    unknown = [key for key in kw if key not in LANGS]
    if unknown:
        raise ValueError(f"unknown languages: {unknown}")
    return kw


TEXTS = [
    {
        "value": "title",
        "order": 0,
        "translations": L(
            es="Ubicación y Alcance", en="Location & Scope",
            pt="Localização e Alcance", fr="Localisation et portée",
            de="Standort & Reichweite", it="Posizione e portata",
            ru="Местоположение и охват", sv="Plats & räckvidd",
            nl="Locatie & bereik", zh="位置与范围",
            hi="स्थान और दायरा", bn="অবস্থান ও পরিধি",
            ja="位置情報と範囲", ko="위치 및 범위",
            ar="الموقع والنطاق", sw="Mahali na wigo",
            ha="Wuri da iyaka", am="አካባቢ እና ወሰን",
            tl="Lokasyon at Saklaw", ms="Lokasi & Skop",
            mi="Wāhi me te korahi",
        ),
    },
    {
        "value": "baseTitle",
        "order": 1,
        "translations": L(
            es="📍 Tu ubicación base", en="📍 Your base location",
            pt="📍 Sua localização base", fr="📍 Votre position de base",
            de="📍 Dein Hauptstandort", it="📍 La tua posizione base",
            ru="📍 Ваше основное местоположение", sv="📍 Din basplats",
            nl="📍 Je basislocatie", zh="📍 你的常驻地",
            hi="📍 आपका मुख्य स्थान", bn="📍 আপনার মূল অবস্থান",
            ja="📍 あなたの拠点", ko="📍 내 기본 위치",
            ar="📍 موقعك الأساسي", sw="📍 Mahali pako pa msingi",
            ha="📍 Babban wurinka", am="📍 የእርስዎ መነሻ አካባቢ",
            tl="📍 Ang iyong base na lokasyon", ms="📍 Lokasi asas anda",
            mi="📍 Tō wāhi taketake",
        ),
    },
    {
        "value": "badge.curious",
        "order": 2,
        "translations": L(
            es="Curioso", en="Curious",
            pt="Curioso", fr="Curieux",
            de="Neugierig", it="Curioso",
            ru="Любопытный", sv="Nyfiken",
            nl="Nieuwsgierig", zh="好奇型",
            hi="जिज्ञासु", bn="কৌতূহলী",
            ja="好奇心型", ko="호기심형",
            ar="فضولي", sw="Mdadisi",
            ha="Mai son sani", am="ጉጉት ያለው",
            tl="Mausisa", ms="Ingin tahu",
            mi="Māhirahira",
        ),
    },
    {
        "value": "badge.adventurer",
        "order": 3,
        "translations": L(
            es="Aventurero", en="Adventurer",
            pt="Aventureiro", fr="Aventurier",
            de="Abenteurer", it="Avventuriero",
            ru="Искатель приключений", sv="Äventyrare",
            nl="Avonturier", zh="冒险家",
            hi="रोमांचप्रेमी", bn="দুঃসাহসী",
            ja="冒険家", ko="모험가",
            ar="مغامر", sw="Msafiri",
            ha="Mai kasada", am="ጀብደኛ",
            tl="Mapagsapalaran", ms="Pengembara",
            mi="Kaimōrearea",
        ),
    },
    {
        "value": "badge.explorer",
        "order": 4,
        "translations": L(
            es="Explorador", en="Explorer",
            pt="Explorador", fr="Explorateur",
            de="Entdecker", it="Esploratore",
            ru="Исследователь", sv="Utforskare",
            nl="Ontdekker", zh="探索者",
            hi="खोजकर्ता", bn="অভিযাত্রী",
            ja="探検家", ko="탐험가",
            ar="مستكشف", sw="Mpelelezi",
            ha="Mai bincike", am="አሳሽ",
            tl="Eksplorador", ms="Penjelajah",
            mi="Kaitūhura",
        ),
    },
    {
        "value": "badge.backpacker",
        "order": 5,
        "translations": L(
            es="Mochilero", en="Backpacker",
            pt="Mochileiro", fr="Routard",
            de="Rucksackreisender", it="Zaino in spalla",
            ru="Путешественник", sv="Ryggsäcksresenär",
            nl="Backpacker", zh="背包客",
            hi="बैकपैकर", bn="ব্যাকপ্যাকার",
            ja="バックパッカー", ko="배낭여행가",
            ar="رحالة", sw="Msafiri wa mgongoni",
            ha="Mai jakar baya", am="ቦርሳ ተጓዥ",
            tl="Backpacker", ms="Pengembara beg galas",
            mi="Kaihaere pēke",
        ),
    },
    {
        "value": "statesTitle",
        "order": 6,
        "translations": L(
            es="🌎 Estados", en="🌎 States",
            pt="🌎 Estados", fr="🌎 États",
            de="🌎 Bundesstaaten", it="🌎 Stati",
            ru="🌎 Штаты", sv="🌎 Delstater",
            nl="🌎 Staten", zh="🌎 州/省",
            hi="🌎 राज्य", bn="🌎 রাজ্য",
            ja="🌎 州", ko="🌎 주",
            ar="🌎 ولايات", sw="🌎 Majimbo",
            ha="🌎 Jihohi", am="🌎 ግዛቶች",
            tl="🌎 Mga estado", ms="🌎 Negeri",
            mi="🌎 Ngā wehenga",
        ),
    },
    {
        "value": "countriesTitle",
        "order": 7,
        "translations": L(
            es="🌍 Países", en="🌍 Countries",
            pt="🌍 Países", fr="🌍 Pays",
            de="🌍 Länder", it="🌍 Paesi",
            ru="🌍 Страны", sv="🌍 Länder",
            nl="🌍 Landen", zh="🌍 国家",
            hi="🌍 देश", bn="🌍 দেশ",
            ja="🌍 国", ko="🌍 국가",
            ar="🌍 دول", sw="🌍 Nchi",
            ha="🌍 Ƙasashe", am="🌍 ሀገራት",
            tl="🌍 Mga bansa", ms="🌍 Negara",
            mi="🌍 Ngā whenua",
        ),
    },
    {
        "value": "searchStates",
        "order": 8,
        "translations": L(
            es="Buscar en estados", en="Search states",
            pt="Buscar em estados", fr="Rechercher des États",
            de="Staaten suchen", it="Cerca stati",
            ru="Найти штаты", sv="Sök delstater",
            nl="Staten zoeken", zh="搜索州/省",
            hi="राज्य खोजें", bn="রাজ্য খুঁজুন",
            ja="州を検索", ko="주 검색",
            ar="بحث في الولايات", sw="Tafuta majimbo",
            ha="Nemi jihohi", am="ግዛቶች ፈልግ",
            tl="Maghanap ng estado", ms="Cari negeri",
            mi="Rapua ngā wehenga",
        ),
    },
    {
        "value": "searchCountries",
        "order": 9,
        "translations": L(
            es="Buscar en países", en="Search countries",
            pt="Buscar em países", fr="Rechercher des pays",
            de="Länder suchen", it="Cerca paesi",
            ru="Найти страны", sv="Sök länder",
            nl="Landen zoeken", zh="搜索国家",
            hi="देश खोजें", bn="দেশ খুঁজুন",
            ja="国を検索", ko="국가 검색",
            ar="بحث في الدول", sw="Tafuta nchi",
            ha="Nemi ƙasashe", am="ሀገራት ፈልግ",
            tl="Maghanap ng bansa", ms="Cari negara",
            mi="Rapua ngā whenua",
        ),
    },
    {
        "value": "radiusLabel",
        "order": 10,
        "translations": L(
            es="Radio de exploración", en="Exploration radius",
            pt="Raio de exploração", fr="Rayon d'exploration",
            de="Erkundungsradius", it="Raggio di esplorazione",
            ru="Радиус поиска", sv="Utforskningsradie",
            nl="Verkenningsradius", zh="探索半径",
            hi="खोज त्रिज्या", bn="অন্বেষণ ব্যাসার্ধ",
            ja="探索範囲", ko="탐색 반경",
            ar="نطاق الاستكشاف", sw="Kipenyo cha utafutaji",
            ha="Faɗin bincike", am="የፍለጋ ራዲየስ",
            tl="Radius ng paggalugad", ms="Jejari penerokaan",
            mi="Rēhi tūhura",
        ),
    },
    {
        "value": "tone.close.label",
        "order": 11,
        "translations": L(
            es="Cercanos", en="Nearby",
            pt="Próximos", fr="Proches",
            de="Nahe", it="Vicini",
            ru="Рядом", sv="Nära",
            nl="Dichtbij", zh="附近",
            hi="आस-पास", bn="কাছাকাছি",
            ja="近所", ko="가까운",
            ar="قريب", sw="Karibu",
            ha="Kusa", am="ቅርብ",
            tl="Malapit", ms="Berdekatan",
            mi="Tatahi",
        ),
    },
    {
        "value": "tone.close.desc",
        "order": 12,
        "translations": L(
            es="Tono íntimo, encuentros presenciales.",
            en="Intimate tone, in-person meetups.",
            pt="Tom íntimo, encontros presenciais.",
            fr="Ton intime, rencontres en personne.",
            de="Intimer Ton, persönliche Treffen.",
            it="Tono intimo, incontri di persona.",
            ru="Интимный тон, личные встречи.",
            sv="Intim ton, möten ansikte mot ansikte.",
            nl="Intieme toon, ontmoetingen in persoon.",
            zh="亲密氛围，线下见面。",
            hi="घनिष्ठ माहौल, आमने-सामने मुलाकात।",
            bn="ঘনিষ্ঠ সুর, সামনাসামনি সাক্ষাৎ।",
            ja="親密な雰囲気、対面での出会い。",
            ko="친밀한 분위기, 대면 만남。",
            ar="نبرة حميمة ولقاءات شخصية.",
            sw="Toni ya karibu, mikutano ana kwa ana.",
            ha="Sauti na kusanci, haɗuwa fuska da fuska.",
            am="የቅርብ ድምጽ, ፊት ለፊት መገናኛዎች።",
            tl="Malapit na tono, personal na pagkikita.",
            ms="Nada intim, pertemuan bersemuka.",
            mi="Reo pātata, hui kanohi ki te kanohi.",
        ),
    },
    {
        "value": "tone.local.label",
        "order": 13,
        "translations": L(
            es="Local", en="Local",
            pt="Local", fr="Local",
            de="Lokal", it="Locale",
            ru="Местный", sv="Lokal",
            nl="Lokaal", zh="本地",
            hi="स्थानीय", bn="স্থানীয়",
            ja="ローカル", ko="로컬",
            ar="محلي", sw="Mtaa",
            ha="Na gida", am="አካባቢያዊ",
            tl="Lokal", ms="Tempatan",
            mi="Tāwāhi",
        ),
    },
    {
        "value": "tone.local.desc",
        "order": 14,
        "translations": L(
            es="Tono cotidiano, encuentros espontáneos.",
            en="Everyday tone, spontaneous meetups.",
            pt="Tom cotidiano, encontros espontâneos.",
            fr="Ton quotidien, rencontres spontanées.",
            de="Alltäglicher Ton, spontane Treffen.",
            it="Tono quotidiano, incontri spontanei.",
            ru="Повседневный тон, спонтанные встречи.",
            sv="Vardaglig ton, spontana möten.",
            nl="Alledaagse toon, spontane ontmoetingen.",
            zh="日常氛围，随性见面。",
            hi="रोज़मर्रा का माहौल, सहज मुलाकात।",
            bn="দৈনন্দিন সুর, স্বতঃস্ফূর্ত সাক্ষাৎ।",
            ja="日常的な雰囲気、気軽な出会い。",
            ko="일상적인 분위기, 즉흥 만남。",
            ar="نبرة يومية ولقاءات عفوية.",
            sw="Toni ya kila siku, mikutano ya ghafla.",
            ha="Sautin yau da kullum, haɗuwa ba tare da shiri ba.",
            am="ዕለታዊ ድምጽ፣ ድንገተኛ መገናኛዎች።",
            tl="Araw-araw na tono, kusang pagkikita.",
            ms="Nada harian, pertemuan spontan.",
            mi="Reo o ia rā, hui noa.",
        ),
    },
    {
        "value": "tone.regional.label",
        "order": 15,
        "translations": L(
            es="Regional", en="Regional",
            pt="Regional", fr="Régional",
            de="Regional", it="Regionale",
            ru="Региональный", sv="Regional",
            nl="Regionaal", zh="区域",
            hi="क्षेत्रीय", bn="আঞ্চলিক",
            ja="リージョナル", ko="지역",
            ar="إقليمي", sw="Kikanda",
            ha="Yanki", am="ክልላዊ",
            tl="Panrehiyon", ms="Serantau",
            mi="Rohe",
        ),
    },
    {
        "value": "tone.regional.desc",
        "order": 16,
        "translations": L(
            es="Tono exploratorio, sugerencias culturales.",
            en="Exploratory tone, cultural suggestions.",
            pt="Tom exploratório, sugestões culturais.",
            fr="Ton exploratoire, suggestions culturelles.",
            de="Erkundender Ton, kulturelle Vorschläge.",
            it="Tono esplorativo, suggerimenti culturali.",
            ru="Исследовательский тон, культурные идеи.",
            sv="Utforskande ton, kulturella förslag.",
            nl="Verkennende toon, culturele suggesties.",
            zh="探索氛围，文化推荐。",
            hi="खोजी माहौल, सांस्कृतिक सुझाव।",
            bn="অন্বেষণমূলক সুর, সাংস্কৃতিক পরামর্শ।",
            ja="探検的な雰囲気、文化的な提案。",
            ko="탐험적 분위기, 문화 제안。",
            ar="نبرة استكشافية واقتراحات ثقافية.",
            sw="Toni ya utafutaji, mapendekezo ya kitamaduni.",
            ha="Sautin bincike, shawarwarin al'adu.",
            am="የአሰሳ ድምጽ፣ የባህል ұсыныстар።",
            tl="Mapaggalugad na tono, mga mungkahing kultural.",
            ms="Nada penerokaan, cadangan budaya.",
            mi="Reo tūhura, marohi ahurea.",
        ),
    },
    {
        "value": "tone.adventure.label",
        "order": 17,
        "translations": L(
            es="Aventura", en="Adventure",
            pt="Aventura", fr="Aventure",
            de="Abenteuer", it="Avventura",
            ru="Приключение", sv="Äventyr",
            nl="Avontuur", zh="冒险",
            hi="रोमांच", bn="দুঃসাহস",
            ja="冒険", ko="모험",
            ar="مغامرة", sw="Adaventura",
            ha="Kasada", am="ጀብዱ",
            tl="Pakikipagsapalaran", ms="Pengembaraan",
            mi="Mōrearea",
        ),
    },
    {
        "value": "tone.adventure.desc",
        "order": 18,
        "translations": L(
            es="Tono curioso, progresión lenta.",
            en="Curious tone, slow progression.",
            pt="Tom curioso, progressão lenta.",
            fr="Ton curieux, progression lente.",
            de="Neugieriger Ton, langsamer Fortschritt.",
            it="Tono curioso, progressione lenta.",
            ru="Любопытный тон, медленное развитие.",
            sv="Nyfiken ton, långsam utveckling.",
            nl="Nieuwsgierige toon, langzame voortgang.",
            zh="好奇氛围，慢慢来。",
            hi="जिज्ञासु माहौल, धीमी प्रगति।",
            bn="কৌতূহলী সুর, ধীর অগ্রগতি।",
            ja="好奇心旺盛な雰囲気、ゆっくりと。",
            ko="호기심 많은 분위기, 느린 진행。",
            ar="نبرة فضولية وتقدم بطيء.",
            sw="Toni ya udadisi, mwendo wa taratibu.",
            ha="Sautin bincike, ci gaba a hankali.",
            am="ጉጉት ድምጽ፣ ዝግ ያለ እድገት።",
            tl="Mausisang tono, mabagal na pag-usad.",
            ms="Nada ingin tahu, kemajuan perlahan.",
            mi="Reo māhirahira, kokenga pōturi.",
        ),
    },
    {
        "value": "deselectAll",
        "order": 19,
        "translations": L(
            es="Deseleccionar todos", en="Deselect all",
            pt="Desmarcar todos", fr="Tout désélectionner",
            de="Alle abwählen", it="Deseleziona tutto",
            ru="Снять все", sv="Avmarkera alla",
            nl="Alles deselecteren", zh="取消全选",
            hi="सभी अचयनित करें", bn="সব অনির্বাচন",
            ja="すべて選択解除", ko="전체 해제",
            ar="إلغاء تحديد الكل", sw="Ondoa zote",
            ha="Cire zaɓaɓɓu", am="ሁሉንም አ Annulla ምርጫ",
            tl="Alisin lahat ng napili", ms="Nyahpilih semua",
            mi="Wetekina katoa",
        ),
    },
    {
        "value": "allStates",
        "order": 20,
        "translations": L(
            es="Todos los estados", en="All states",
            pt="Todos os estados", fr="Tous les États",
            de="Alle Bundesstaaten", it="Tutti gli stati",
            ru="Все штаты", sv="Alla delstater",
            nl="Alle staten", zh="所有州/省",
            hi="सभी राज्य", bn="সমস্ত রাজ্য",
            ja="すべての州", ko="모든 주",
            ar="كل الولايات", sw="Majimbo yote",
            ha="Duk jihohi", am="ሁሉም ግዛቶች",
            tl="Lahat ng estado", ms="Semua negeri",
            mi="Ngā wehenga katoa",
        ),
    },
    {
        "value": "allWorld",
        "order": 21,
        "translations": L(
            es="Todo el mundo", en="Whole world",
            pt="Mundo todo", fr="Monde entier",
            de="Ganze Welt", it="Mondo intero",
            ru="Весь мир", sv="Hela världen",
            nl="Hele wereld", zh="全世界",
            hi="पूरी दुनिया", bn="সমগ্র বিশ্ব",
            ja="全世界", ko="전 세계",
            ar="العالم كله", sw="Dunia nzima",
            ha="Duniya baki ɗaya", am="መላው ዓለም",
            tl="Buong mundo", ms="Seluruh dunia",
            mi="Te ao katoa",
        ),
    },
    {
        "value": "statesOf",
        "order": 22,
        "translations": L(
            es="Estados de {{country}}...", en="States of {{country}}...",
            pt="Estados de {{country}}...", fr="États de {{country}}...",
            de="Staaten von {{country}}...", it="Stati di {{country}}...",
            ru="Штаты: {{country}}...", sv="Delstater i {{country}}...",
            nl="Staten van {{country}}...", zh="{{country}}的州/省…",
            hi="{{country}} के राज्य...", bn="{{country}}-এর রাজ্য...",
            ja="{{country}}の州…", ko="{{country}}의 주…",
            ar="ولايات {{country}}...", sw="Majimbo ya {{country}}...",
            ha="Jihohin {{country}}...", am="የ{{country}} ግዛቶች…",
            tl="Mga estado ng {{country}}...", ms="Negeri-negeri {{country}}...",
            mi="Ngā wehenga o {{country}}…",
        ),
    },
    {
        "value": "excludeCountries",
        "order": 23,
        "translations": L(
            es="Excluir países", en="Exclude countries",
            pt="Excluir países", fr="Exclure des pays",
            de="Länder ausschließen", it="Escludi paesi",
            ru="Исключить страны", sv="Exkludera länder",
            nl="Landen uitsluiten", zh="排除国家",
            hi="देश बाहर करें", bn="দেশ বাদ দিন",
            ja="国を除外", ko="국가 제외",
            ar="استبعاد الدول", sw="Ondoa nchi",
            ha="Cire ƙasashe", am="ሀገራት አግልል",
            tl="Ibukod ang mga bansa", ms="Kecualikan negara",
            mi="Whakakore whenua",
        ),
    },
    {
        "value": "countryPlaceholder",
        "order": 24,
        "translations": L(
            es="Escribe un país o continente...",
            en="Type a country or continent...",
            pt="Digite um país ou continente...",
            fr="Tapez un pays ou un continent...",
            de="Land oder Kontinent eingeben...",
            it="Digita un paese o un continente...",
            ru="Введите страну или континент...",
            sv="Skriv ett land eller en kontinent...",
            nl="Typ een land of continent...",
            zh="输入国家或大洲…",
            hi="देश या महाद्वीप लिखें...",
            bn="দেশ বা মহাদেশ লিখুন...",
            ja="国または大陸を入力…",
            ko="국가 또는 대륙 입력…",
            ar="اكتب دولة أو قارة...",
            sw="Andika nchi au bara...",
            ha="Rubuta ƙasa ko nahiya...",
            am="ሀገር ወይም አህጉር ጻፍ…",
            tl="Mag-type ng bansa o kontinente...",
            ms="Taip negara atau benua...",
            mi="Tāuru whenua, paparahi rānei…",
        ),
    },
    {
        "value": "addedCountries",
        "order": 25,
        "translations": L(
            es="Se agregaron {{count}} países de {{name}}",
            en="{{count}} countries from {{name}} added",
            pt="{{count}} países de {{name}} adicionados",
            fr="{{count}} pays de {{name}} ajoutés",
            de="{{count}} Länder aus {{name}} hinzugefügt",
            it="{{count}} paesi di {{name}} aggiunti",
            ru="Добавлено стран ({{count}}) из {{name}}",
            sv="{{count}} länder från {{name}} tillagda",
            nl="{{count}} landen uit {{name}} toegevoegd",
            zh="已添加{{name}}的{{count}}个国家",
            hi="{{name}} के {{count}} देश जोड़े गए",
            bn="{{name}}-এর {{count}}টি দেশ যোগ হয়েছে",
            ja="{{name}}の{{count}}か国を追加",
            ko="{{name}}의 국가 {{count}}개 추가됨",
            ar="تمت إضافة {{count}} دول من {{name}}",
            sw="Nchi {{count}} za {{name}} zimeongezwa",
            ha="An ƙara ƙasashe {{count}} na {{name}}",
            am="{{count}} ሀገራት ከ{{name}} ታክለዋል",
            tl="Nadagdag ang {{count}} bansa mula sa {{name}}",
            ms="{{count}} negara dari {{name}} ditambah",
            mi="Kua tāpiritia {{count}} whenua mai i {{name}}",
        ),
    },
    {
        "value": "allExcept",
        "order": 26,
        "translations": L(
            es="Todos excepto {{first}}{{rest}}",
            en="All except {{first}}{{rest}}",
            pt="Todos exceto {{first}}{{rest}}",
            fr="Tous sauf {{first}}{{rest}}",
            de="Alle außer {{first}}{{rest}}",
            it="Tutti tranne {{first}}{{rest}}",
            ru="Все кроме {{first}}{{rest}}",
            sv="Alla utom {{first}}{{rest}}",
            nl="Alle behalve {{first}}{{rest}}",
            zh="除{{first}}{{rest}}外的全部",
            hi="{{first}}{{rest}} को छोड़कर सभी",
            bn="{{first}}{{rest}} ছাড়া সব",
            ja="{{first}}{{rest}}以外すべて",
            ko="{{first}}{{rest}} 제외하고 전부",
            ar="الكل باستثناء {{first}}{{rest}}",
            sw="Zote isipokuwa {{first}}{{rest}}",
            ha="Duka sai {{first}}{{rest}}",
            am="ሁሉም ከ{{first}}{{rest}} በስተቀር",
            tl="Lahat maliban sa {{first}}{{rest}}",
            ms="Semua kecuali {{first}}{{rest}}",
            mi="Katoa haunga a {{first}}{{rest}}",
        ),
    },
    {
        "value": "allWorldExcept",
        "order": 27,
        "translations": L(
            es="Todo el mundo excepto {{first}}{{rest}}",
            en="Whole world except {{first}}{{rest}}",
            pt="Mundo todo exceto {{first}}{{rest}}",
            fr="Monde entier sauf {{first}}{{rest}}",
            de="Ganze Welt außer {{first}}{{rest}}",
            it="Mondo intero tranne {{first}}{{rest}}",
            ru="Весь мир кроме {{first}}{{rest}}",
            sv="Hela världen utom {{first}}{{rest}}",
            nl="Hele wereld behalve {{first}}{{rest}}",
            zh="除{{first}}{{rest}}外的全世界",
            hi="{{first}}{{rest}} को छोड़कर पूरी दुनिया",
            bn="{{first}}{{rest}} ছাড়া সমগ্র বিশ্ব",
            ja="{{first}}{{rest}}を除く全世界",
            ko="{{first}}{{rest}} 제외한 전 세계",
            ar="العالم كله باستثناء {{first}}{{rest}}",
            sw="Dunia nzima isipokuwa {{first}}{{rest}}",
            ha="Duniya baki ɗaya sai {{first}}{{rest}}",
            am="መላው ዓለም ከ{{first}}{{rest}} በስተቀር",
            tl="Buong mundo maliban sa {{first}}{{rest}}",
            ms="Seluruh dunia kecuali {{first}}{{rest}}",
            mi="Te ao katoa haunga a {{first}}{{rest}}",
        ),
    },
    {
        "value": "andMore",
        "order": 28,
        "translations": L(
            es=" y {{count}} más", en=" and {{count}} more",
            pt=" e mais {{count}}", fr=" et {{count}} de plus",
            de=" und {{count}} weitere", it=" e altri {{count}}",
            ru=" и ещё {{count}}", sv=" och {{count}} till",
            nl=" en {{count}} meer", zh="另有{{count}}个",
            hi=" और {{count}} अन्य", bn=" এবং আরও {{count}}টি",
            ja="ほか{{count}}件", ko=" 외 {{count}}개",
            ar=" و{{count}} أخرى", sw=" na {{count}} zaidi",
            ha=" da wasu {{count}}", am=" እና {{count}} ተጨማሪ",
            tl=" at {{count}} pa", ms=" dan {{count}} lagi",
            mi=" me {{count}} anō",
        ),
    },
    {
        "value": "cityPlaceholder",
        "order": 29,
        "translations": L(
            es="¿En qué ciudad vives?", en="Which city do you live in?",
            pt="Em que cidade você mora?", fr="Dans quelle ville vis-tu ?",
            de="In welcher Stadt wohnst du?", it="In che città vivi?",
            ru="В каком городе вы живёте?", sv="I vilken stad bor du?",
            nl="In welke stad woon je?", zh="你住在哪个城市？",
            hi="आप किस शहर में रहते हैं?", bn="আপনি কোন শহরে থাকেন?",
            ja="どの都市に住んでいますか？", ko="어느 도시에 사나요?",
            ar="في أي مدينة تعيش؟", sw="Unaishi mji gani?",
            ha="A wane birni kake zama?", am="በየት ከተማ ትኖራለህ?",
            tl="Saang lungsod ka nakatira?", ms="Di bandar mana anda tinggal?",
            mi="E noho ana koe ki tēhea tāone?",
        ),
    },
    {
        "value": "careSuggests",
        "order": 30,
        "translations": L(
            es="\"CARE sugiere vínculos con tono {{tone}}.\"",
            en="\"CARE suggests bonds with {{tone}} tone.\"",
            pt="\"CARE sugere vínculos com tom {{tone}}.\"",
            fr="\"CARE suggère des liens sur un ton {{tone}}.\"",
            de="\"CARE schlägt Verbindungen im {{tone}}-Ton vor.\"",
            it="\"CARE suggerisce legami con tono {{tone}}.\"",
            ru="\"CARE предлагает связи в тоне {{tone}}.\"",
            sv="\"CARE föreslår band med {{tone}} ton.\"",
            nl="\"CARE stelt banden met {{tone}}-toon voor.\"",
            zh="\"CARE 建议{{tone}}风格的联结。\"",
            hi="\"CARE {{tone}} लहजे वाले रिश्तों का सुझाव देता है।\"",
            bn="\"CARE {{tone}} সুরে সম্পর্কের পরামর্শ দেয়।\"",
            ja="\"CAREは{{tone}}なトーンのつながりを提案します。\"",
            ko="\"CARE는 {{tone}} 톤의 인연을 제안합니다.\"",
            ar="\"يقترح CARE روابط بنبرة {{tone}}.\"",
            sw="\"CARE inapendekeza uhusiano wenye toni ya {{tone}}.\"",
            ha="\"CARE yana ba da shawarar alaƙa da sautin {{tone}}.\"",
            am="\"CARE ከ{{tone}} ድምጽ ጋር ትስስሮችን ያቀርባል።\"",
            tl="\"Iminumungkahi ng CARE ang mga ugnayang may {{tone}} na tono.\"",
            ms="\"CARE mencadangkan ikatan bernada {{tone}}.\"",
            mi="\"E marohi ana a CARE i ngā here me te reo {{tone}}.\"",
        ),
    },
    {
        "value": "badge.closeTip",
        "order": 31,
        "translations": L(
            es="Cercanos: Match dentro de 10 km",
            en="Nearby: Match within 10 km",
            pt="Próximos: Match em até 10 km",
            fr="Proches : Match dans un rayon de 10 km",
            de="Nahe: Match im Umkreis von 10 km",
            it="Vicini: Match entro 10 km",
            ru="Рядом: совпадения в радиусе 10 км",
            sv="Nära: Matchning inom 10 km",
            nl="Dichtbij: match binnen 10 km",
            zh="附近：10公里内匹配",
            hi="आस-पास: 10 किमी के भीतर मैच",
            bn="কাছাকাছি: ১০ কিমি-এর মধ্যে মিল",
            ja="近所：10km圏内でマッチ",
            ko="가까운: 10km 이내 매칭",
            ar="قريب: توافق ضمن 10 كم",
            sw="Karibu: Sambamba ndani ya km 10",
            ha="Kusa: Daidaituwa cikin kilomita 10",
            am="ቅርብ፡ እስከ 10 ኪ.ሜ ውስጥ መsakመጥ",
            tl="Malapit: Match sa loob ng 10 km",
            ms="Berdekatan: Padanan dalam 10 km",
            mi="Tatahi: Hononga i roto i te 10 km",
        ),
    },
    {
        "value": "badge.curiousTip",
        "order": 32,
        "translations": L(
            es="Curioso: Match entre 50-70 km",
            en="Curious: Match between 50-70 km",
            pt="Curioso: Match entre 50-70 km",
            fr="Curieux : Match entre 50 et 70 km",
            de="Neugierig: Match zwischen 50–70 km",
            it="Curioso: Match tra 50-70 km",
            ru="Любопытный: совпадения 50–70 км",
            sv="Nyfiken: Matchning mellan 50–70 km",
            nl="Nieuwsgierig: match tussen 50-70 km",
            zh="好奇型：50-70公里匹配",
            hi="जिज्ञासु: 50-70 किमी के बीच मैच",
            bn="কৌতূহলী: ৫০-৭০ কিমি-এর মধ্যে মিল",
            ja="好奇心型：50〜70kmでマッチ",
            ko="호기심형: 50-70km 매칭",
            ar="فضولي: توافق بين 50-70 كم",
            sw="Mdadisi: Sambamba kati ya km 50-70",
            ha="Mai son sani: Daidaituwa tsakanin kilomita 50-70",
            am="ጉጉት ያለው: ከ50-70 ኪ.ሜ መsakመጥ",
            tl="Mausisa: Match sa pagitan ng 50-70 km",
            ms="Ingin tahu: Padanan antara 50-70 km",
            mi="Māhirahira: Hononga i waenga i te 50-70 km",
        ),
    },
    {
        "value": "badge.adventureTip",
        "order": 33,
        "translations": L(
            es="Aventurero: Match a más de 80 km",
            en="Adventurer: Match beyond 80 km",
            pt="Aventureiro: Match além de 80 km",
            fr="Aventurier : Match au-delà de 80 km",
            de="Abenteurer: Match über 80 km hinaus",
            it="Avventuriero: Match oltre 80 km",
            ru="Искатель приключений: совпадения дальше 80 км",
            sv="Äventyrare: Matchning bortom 80 km",
            nl="Avonturier: match verder dan 80 km",
            zh="冒险家：80公里外匹配",
            hi="रोमांचप्रेमी: 80 किमी से दूर मैच",
            bn="দুঃসাহসী: ৮০ কিমি-এর বাইরে মিল",
            ja="冒険家：80km超でマッチ",
            ko="모험가: 80km 이상 매칭",
            ar="مغامر: توافق beyond 80 كم",
            sw="Msafiri: Sambamba zaidi ya km 80",
            ha="Mai kasada: Daidaituwa bayan kilomita 80",
            am="ጀብደኛ: ከ80 ኪ.ሜ በላይ መsakመጥ",
            tl="Mapagsapalaran: Match na lampas 80 km",
            ms="Pengembara: Padanan melebihi 80 km",
            mi="Kaimōrearea: Hononga i tua atu i te 80 km",
        ),
    },
    {
        "value": "badge.explorerTip",
        "order": 34,
        "translations": L(
            es="Explorador: Match con otro estado (Requiere seleccionar estados)",
            en="Explorer: Match with another state (Requires selecting states)",
            pt="Explorador: Match com outro estado (Requer selecionar estados)",
            fr="Explorateur : Match avec un autre État (États requis)",
            de="Entdecker: Match mit anderem Bundesstaat (Staaten wählen)",
            it="Esploratore: Match con un altro stato (Richiede stati)",
            ru="Исследователь: совпадения с другим штатом (выберите штаты)",
            sv="Utforskare: Matchning med annan delstat (kräver delstater)",
            nl="Ontdekker: match met een andere staat (staten vereist)",
            zh="探索者：与其他州匹配（需选择州/省）",
            hi="खोजकर्ता: दूसरे राज्य से मैच (राज्य चुनना ज़रूरी)",
            bn="অভিযাত্রী: অন্য রাজ্যের সাথে মিল (রাজ্য নির্বাচন প্রয়োজন)",
            ja="探検家：他の州とマッチ（州の選択が必要）",
            ko="탐험가: 다른 주와 매칭 (주 선택 필요)",
            ar="مستكشف: توافق مع ولاية أخرى (يتطلب اختيار الولايات)",
            sw="Mpelelezi: Sambamba na jimbo lingine (inahitaji majimbo)",
            ha="Mai bincike: Daidaituwa da wata jiha (jihohi ake buƙata)",
            am="አሳሽ: ከሌላ ግዛት ጋር መsakመጥ (ግዛቶችን መምረጥ ያስፈልጋል)",
            tl="Eksplorador: Match sa ibang estado (nangangailangan ng estado)",
            ms="Penjelajah: Padanan dengan negeri lain (perlu pilih negeri)",
            mi="Kaitūhura: Hononga ki tētahi atu wehenga (me tīpako wehenga)",
        ),
    },
    {
        "value": "badge.backpackerTip",
        "order": 35,
        "translations": L(
            es="Mochilero: Match internacional (Requiere VIP)",
            en="Backpacker: International match (Requires VIP)",
            pt="Mochileiro: Match internacional (Requer VIP)",
            fr="Routard : Match international (VIP requis)",
            de="Rucksackreisender: Internationaler Match (VIP nötig)",
            it="Zaino in spalla: Match internazionale (Richiede VIP)",
            ru="Путешественник: международные совпадения (нужен VIP)",
            sv="Ryggsäcksresenär: Internationell matchning (kräver VIP)",
            nl="Backpacker: internationale match (VIP vereist)",
            zh="背包客：国际匹配（需VIP）",
            hi="बैकपैकर: अंतरराष्ट्रीय मैच (VIP आवश्यक)",
            bn="ব্যাকপ্যাকার: আন্তর্জাতিক মিল (VIP প্রয়োজন)",
            ja="バックパッカー：国際マッチ（VIP必須）",
            ko="배낭여행가: 국제 매칭 (VIP 필요)",
            ar="رحالة: توافق دولي (يتطلب VIP)",
            sw="Msafiri wa mgongoni: Sambamba ya kimataifa (inahitaji VIP)",
            ha="Mai jakar baya: Daidaituwa ta ƙasa da ƙasa (VIP ake buƙata)",
            am="ቦርሳ ተጓዥ: ዓለም አቀፍ መsakመጥ (VIP ያስፈልጋል)",
            tl="Backpacker: International na match (nangangailangan ng VIP)",
            ms="Pengembara beg galas: Padanan antarabangsa (perlu VIP)",
            mi="Kaihaere pēke: Hononga ā-ao (me whai VIP)",
        ),
    },
    {
        "value": "countriesLimit",
        "order": 36,
        "translations": L(
            es="Has alcanzado el límite de 20 países. Elimina alguno para agregar otro.",
            en="You reached the 20-country limit. Remove one to add another.",
            pt="Você atingiu o limite de 20 países. Remova um para adicionar outro.",
            fr="Limite de 20 pays atteinte. Retirez-en un pour en ajouter un autre.",
            de="20-Länder-Limit erreicht. Entferne eines, um ein weiteres hinzuzufügen.",
            it="Hai raggiunto il limite di 20 paesi. Rimuovine uno per aggiungerne un altro.",
            ru="Достигнут лимит в 20 стран. Удалите одну, чтобы добавить другую.",
            sv="Du har nått gränsen på 20 länder. Ta bort ett för att lägga till ett annat.",
            nl="Limiet van 20 landen bereikt. Verwijder er een om een ander toe te voegen.",
            zh="已达20个国家上限。删除一个再添加。",
            hi="20 देशों की सीमा पूरी। दूसरा जोड़ने के लिए एक हटाएं।",
            bn="২০টি দেশের সীমা পূর্ণ। আরেকটি যোগ করতে একটি সরান।",
            ja="20か国の上限に達しました。追加するには1つ削除してください。",
            ko="20개국上限에 도달했습니다. 추가하려면 하나를 삭제하세요.",
            ar="بلغت حد 20 دولة. احذف واحدة لإضافة أخرى.",
            sw="Umefikia kikomo cha nchi 20. Ondoa moja ili uongeze nyingine.",
            ha="Ka kai iyakar ƙasashe 20. Cire ɗaya don ƙara wani.",
            am="የ20 ሀገራት ገደብ ደርሰሃል። ሌላ ለመጨመር አንዱን አስወግድ።",
            tl="Naabot mo na ang limit na 20 bansa. Mag-alis ng isa para magdagdag.",
            ms="Anda mencapai had 20 negara. Alih keluar satu untuk menambah.",
            mi="Kua eke koe i te tepenga o ngā whenua 20. Tango tētahi kia tāpiri atu ai.",
        ),
    },
    {
        "value": "countriesUnit",
        "order": 37,
        "translations": L(
            es="países", en="countries",
            pt="países", fr="pays",
            de="Länder", it="paesi",
            ru="стран", sv="länder",
            nl="landen", zh="个国家",
            hi="देश", bn="দেশ",
            ja="か国", ko="개국",
            ar="دول", sw="nchi",
            ha="ƙasashe", am="ሀገራት",
            tl="bansa", ms="negara",
            mi="whenua",
        ),
    },
    {
        "value": "statesUnit",
        "order": 38,
        "translations": L(
            es="estados", en="states",
            pt="estados", fr="États",
            de="Staaten", it="stati",
            ru="штатов", sv="delstater",
            nl="staten", zh="个州/省",
            hi="राज्य", bn="রাজ্য",
            ja="州", ko="개 주",
            ar="ولايات", sw="majimbo",
            ha="jihohi", am="ግዛቶች",
            tl="estado", ms="negeri",
            mi="wehenga",
        ),
    },
    {
        "value": "limitReached",
        "order": 39,
        "translations": L(
            es="Límite de {{limit}} {{unit}} alcanzado para tu plan.",
            en="{{limit}} {{unit}} limit reached for your plan.",
            pt="Limite de {{limit}} {{unit}} atingido para seu plano.",
            fr="Limite de {{limit}} {{unit}} atteinte pour ton forfait.",
            de="{{limit}}-{{unit}}-Limit für deinen Plan erreicht.",
            it="Limite di {{limit}} {{unit}} raggiunto per il tuo piano.",
            ru="Достигнут лимит {{limit}} {{unit}} для вашего тарифа.",
            sv="{{limit}} {{unit}}-gräns nådd för din plan.",
            nl="{{limit}} {{unit}}-limiet bereikt voor je abonnement.",
            zh="你的套餐已达{{limit}}{{unit}}上限。",
            hi="आपके प्लान हेतु {{limit}} {{unit}} सीमा पूर्ण।",
            bn="আপনার প্ল্যানের জন্য {{limit}} {{unit}} সীমা পূর্ণ।",
            ja="プランの上限{{limit}}{{unit}}に達しました。",
            ko="요금제 {{limit}}{{unit}}上限 도달.",
            ar="تم بلوغ حد {{limit}} {{unit}} لخطتك.",
            sw="Kikomo cha {{limit}} {{unit}} kimefikiwa.",
            ha="An kai iyakar {{limit}} {{unit}} na tsarinka.",
            am="{{limit}} {{unit}} ገደብ ለዕቅድህ ደርሷል።",
            tl="Naabot ang {{limit}} {{unit}} limit para sa plan mo.",
            ms="Had {{limit}} {{unit}} dicapai untuk pelan anda.",
            mi="Kua eke te tepenga {{limit}} {{unit}} mō tō mahere.",
        ),
    },
    {
        "value": "premiumStates",
        "order": 40,
        "translations": L(
            es="¡Suscríbete a Premium para seleccionar estados o VIP para todo el mundo!",
            en="Subscribe to Premium to select states or VIP for the whole world!",
            pt="Assine Premium para selecionar estados ou VIP para o mundo todo!",
            fr="Abonne-toi à Premium pour choisir des États ou VIP pour le monde entier !",
            de="Abonniere Premium für Staaten oder VIP für die ganze Welt!",
            it="Abbonati a Premium per selezionare stati o VIP per il mondo intero!",
            ru="Оформите Premium для выбора штатов или VIP для всего мира!",
            sv="Prenumerera på Premium för delstater eller VIP för hela världen!",
            nl="Abonneer op Premium voor staten of VIP voor de hele wereld!",
            zh="订阅Premium可选州/省，VIP畅游全世界！",
            hi="राज्य चुनने हेतु Premium लें या पूरी दुनिया हेतु VIP!",
            bn="রাজ্য বেছে নিতে Premium নিন বা সারা বিশ্বের জন্য VIP!",
            ja="州を選ぶにはPremium、全世界にはVIPに登録！",
            ko="주를 선택하려면 Premium, 전 세계는 VIP 구독!",
            ar="اشترك في Premium لاختيار الولايات أو VIP للعالم كله!",
            sw="Jisajili Premium kuchagua majimbo au VIP kwa dunia nzima!",
            ha="Yi rajista da Premium don zaɓar jihohi ko VIP don duniya baki ɗaya!",
            am="ግዛቶችን ለመምረጥ ፕሪሚየምን ወይም ለመላው ዓለም VIPን ተመዝግብ!",
            tl="Mag-subscribe sa Premium para pumili ng estado o VIP para sa buong mundo!",
            ms="Langgan Premium untuk pilih negeri atau VIP untuk seluruh dunia!",
            mi="Ohauru ki te Premium mō ngā wehenga, VIP rānei mō te ao katoa!",
        ),
    },
    {
        "value": "vipOnly",
        "order": 41,
        "translations": L(
            es="La selección internacional es exclusiva para miembros VIP.",
            en="International selection is exclusive to VIP members.",
            pt="A seleção internacional é exclusiva para membros VIP.",
            fr="La sélection internationale est réservée aux membres VIP.",
            de="Internationale Auswahl nur für VIP-Mitglieder.",
            it="La selezione internazionale è riservata ai membri VIP.",
            ru="Международный выбор только для VIP.",
            sv="Internationellt urval endast för VIP-medlemmar.",
            nl="Internationale selectie alleen voor VIP-leden.",
            zh="国际选择仅限VIP会员。",
            hi="अंतरराष्ट्रीय चयन केवल VIP सदस्यों हेतु।",
            bn="আন্তর্জাতিক নির্বাচন শুধু VIP সদস্যদের জন্য।",
            ja="国際選択はVIP会員限定です。",
            ko="국제 선택은 VIP 회원 전용입니다.",
            ar="الاختيار الدولي حصري لأعضاء VIP.",
            sw="Uchaguzi wa kimataifa ni kwa wanachama VIP pekee.",
            ha="Zaɓin ƙasa da ƙasa na musamman ne ga mambobin VIP.",
            am="ዓለም አቀፍ ምርጫ ለVIP አባላት ብቻ ነው።",
            tl="Ang internasyonal na pagpili ay para sa VIP members lamang.",
            ms="Pemilihan antarabangsa eksklusif untuk ahli VIP.",
            mi="Ko te kōwhiringa ā-ao mā ngā mema VIP anake.",
        ),
    },
    {
        "value": "lockedStates",
        "order": 42,
        "translations": L(
            es="Selecciona estados específicos",
            en="Select specific states",
            pt="Selecione estados específicos",
            fr="Sélectionnez des États précis",
            de="Wähle bestimmte Staaten",
            it="Seleziona stati specifici",
            ru="Выберите конкретные штаты",
            sv="Välj specifika delstater",
            nl="Selecteer specifieke staten",
            zh="选择具体州/省",
            hi="विशिष्ट राज्य चुनें",
            bn="নির্দিষ্ট রাজ্য বেছে নিন",
            ja="特定の州を選択",
            ko="특정 주 선택",
            ar="اختر ولايات محددة",
            sw="Chagua majimbo mahususi",
            ha="Zaɓi takamaiman jihohi",
            am="ልዩ ግዛቶች ምረጥ",
            tl="Pumili ng partikular na estado",
            ms="Pilih negeri tertentu",
            mi="Tīpakohia ngā wehenga motuhake",
        ),
    },
    {
        "value": "scopeGlobal",
        "order": 43,
        "translations": L(
            es="Ámbito: Global", en="Scope: Global",
            pt="Âmbito: Global", fr="Portée : Mondiale",
            de="Reichweite: Global", it="Ambito: Globale",
            ru="Охват: Глобальный", sv="Omfattning: Global",
            nl="Bereik: Wereldwijd", zh="范围：全球",
            hi="दायरा: वैश्विक", bn="পরিধি: বৈশ্বিক",
            ja="範囲：グローバル", ko="범위: 글로벌",
            ar="النطاق: عالمي", sw="Wigo: Kimataifa",
            ha="Iyaka: Duniya baki ɗaya", am="ወሰን፡ ዓለም አቀፍ",
            tl="Saklaw: Global", ms="Skop: Global",
            mi="Korahi: Ao",
        ),
    },
    {
        "value": "scopeNational",
        "order": 44,
        "translations": L(
            es="Alcance: Nacional", en="Scope: National",
            pt="Alcance: Nacional", fr="Portée : Nationale",
            de="Reichweite: National", it="Ambito: Nazionale",
            ru="Охват: Национальный", sv="Omfattning: Nationell",
            nl="Bereik: Nationaal", zh="范围：全国",
            hi="दायरा: राष्ट्रीय", bn="পরিধি: জাতীয়",
            ja="範囲：国内", ko="범위: 국내",
            ar="النطاق: وطني", sw="Wigo: Kitaifa",
            ha="Iyaka: Na ƙasa", am="ወሰን፡ ሀገራዊ",
            tl="Saklaw: Pambansa", ms="Skop: Kebangsaan",
            mi="Korahi: Motu",
        ),
    },
    {
        "value": "setSuccess",
        "order": 45,
        "translations": L(
            es="Ubicación establecida: {{city}}",
            en="Location set: {{city}}",
            pt="Localização definida: {{city}}",
            fr="Position définie : {{city}}",
            de="Standort gesetzt: {{city}}",
            it="Posizione impostata: {{city}}",
            ru="Местоположение задано: {{city}}",
            sv="Plats angiven: {{city}}",
            nl="Locatie ingesteld: {{city}}",
            zh="已设置位置：{{city}}",
            hi="स्थान सेट: {{city}}",
            bn="অবস্থান নির্ধারিত: {{city}}",
            ja="位置を設定：{{city}}",
            ko="위치 설정됨: {{city}}",
            ar="تم تحديد الموقع: {{city}}",
            sw="Mahali pamewekwa: {{city}}",
            ha="An sa wuri: {{city}}",
            am="አካባቢ ተቀምጧል፦ {{city}}",
            tl="Naitakda ang lokasyon: {{city}}",
            ms="Lokasi ditetapkan: {{city}}",
            mi="Kua whakaritea te wāhi: {{city}}",
        ),
    },
    {
        "value": "detectFailed",
        "order": 46,
        "translations": L(
            es="No pudimos detectar tu ubicación.",
            en="We could not detect your location.",
            pt="Não pudemos detectar sua localização.",
            fr="Nous n'avons pas pu détecter ta position.",
            de="Dein Standort konnte nicht ermittelt werden.",
            it="Non siamo riusciti a rilevare la tua posizione.",
            ru="Не удалось определить ваше местоположение.",
            sv="Vi kunde inte hitta din plats.",
            nl="We konden je locatie niet detecteren.",
            zh="无法检测你的位置。",
            hi="आपका स्थान पता नहीं चल सका।",
            bn="আপনার অবস্থান শনাক্ত করা যায়নি।",
            ja="位置を検出できませんでした。",
            ko="위치를 감지하지 못했습니다.",
            ar="تعذر علينا تحديد موقعك.",
            sw="Hatukuweza kubaini mahali ulipo.",
            ha="Ba mu iya gano wurinka ba.",
            am="አካባቢህን መለየት አልቻልንም።",
            tl="Hindi namin matukoy ang lokasyon mo.",
            ms="Kami tidak dapat mengesan lokasi anda.",
            mi="Kāore i kitea tō wāhi.",
        ),
    },
    {
        "value": "noGeolocation",
        "order": 47,
        "translations": L(
            es="Tu navegador no soporta geolocalización.",
            en="Your browser does not support geolocation.",
            pt="Seu navegador não suporta geolocalização.",
            fr="Ton navigateur ne prend pas en charge la géolocalisation.",
            de="Dein Browser unterstützt keine Geolokalisierung.",
            it="Il tuo browser non supporta la geolocalizzazione.",
            ru="Ваш браузер не поддерживает геолокацию.",
            sv="Din webbläsare stöder inte geolokalisering.",
            nl="Je browser ondersteunt geen geolocatie.",
            zh="你的浏览器不支持定位。",
            hi="आपका ब्राउज़र जियोलोकेशन समर्थित नहीं करता।",
            bn="আপনার ব্রাউজার জিওলোকেশন সমর্থন করে না।",
            ja="お使いのブラウザは位置情報に対応していません。",
            ko="브라우저가 위치 정보를 지원하지 않습니다.",
            ar="متصفحك لا يدعم تحديد الموقع.",
            sw="Kivinjari chako hakitumii eneo.",
            ha="Burauzarka ba ta tallafa da tantance wuri ba.",
            am="አሳሽህ አካባቢ መለየትን አይደግፍም።",
            tl="Hindi sinusuportahan ng browser mo ang geolocation.",
            ms="Pelayar anda tidak menyokong geolokasi.",
            mi="Kāore tō pūtirotiro e tautoko i te kimowāhi.",
        ),
    },
    {
        "value": "statesReset",
        "order": 48,
        "translations": L(
            es="Se han restablecido los estados al cambiar de país.",
            en="States were reset after changing country.",
            pt="Os estados foram redefinidos ao trocar de país.",
            fr="Les États ont été réinitialisés après changement de pays.",
            de="Staaten wurden nach Länderwechsel zurückgesetzt.",
            it="Gli stati sono stati reimpostati dopo il cambio di paese.",
            ru="Штаты сброшены после смены страны.",
            sv="Delstaterna återställdes efter landsbyte.",
            nl="Staten zijn gereset na landwissel.",
            zh="切换国家后州/省已重置。",
            hi="देश बदलने पर राज्य रीसेट हो गए।",
            bn="দেশ বদলানোর পর রাজ্য রিসেট হয়েছে।",
            ja="国を変更したため州がリセットされました。",
            ko="국가 변경으로 주가 초기화되었습니다.",
            ar="أُعيد تعيين الولايات بعد تغيير الدولة.",
            sw="Majimbo yamewekwa upya baada ya kubadilisha nchi.",
            ha="An sake saita jihohi bayan canza ƙasa.",
            am="ሀገር ከተቀየረ በኋላ ግዛቶች ዳግም ተቀናጅተዋል።",
            tl="Nai-reset ang mga estado pagkatapos magpalit ng bansa.",
            ms="Negeri ditetapkan semula selepas menukar negara.",
            mi="Kua tautuhi anō ngā wehenga whai muri i te hurihanga whenua.",
        ),
    },
    {
        "value": "writeState",
        "order": 49,
        "translations": L(
            es="Escribe un estado...", en="Type a state...",
            pt="Digite um estado...", fr="Tapez un État...",
            de="Staat eingeben...", it="Digita uno stato...",
            ru="Введите штат...", sv="Skriv en delstat...",
            nl="Typ een staat...", zh="输入州/省…",
            hi="राज्य लिखें...", bn="রাজ্য লিখুন...",
            ja="州を入力…", ko="주 입력…",
            ar="اكتب ولاية...", sw="Andika jimbo...",
            ha="Rubuta jiha...", am="ግዛት ጻፍ…",
            tl="Mag-type ng estado...", ms="Taip negeri...",
            mi="Tāuru wehenga…",
        ),
    },
    {
        "value": "excludeStates",
        "order": 50,
        "translations": L(
            es="Excluir estados", en="Exclude states",
            pt="Excluir estados", fr="Exclure des États",
            de="Staaten ausschließen", it="Escludi stati",
            ru="Исключить штаты", sv="Exkludera delstater",
            nl="Staten uitsluiten", zh="排除州/省",
            hi="राज्य बाहर करें", bn="রাজ্য বাদ দিন",
            ja="州を除外", ko="주 제외",
            ar="استبعاد الولايات", sw="Ondoa majimbo",
            ha="Cire jihohi", am="ግዛቶች አግልል",
            tl="Ibukod ang mga estado", ms="Kecualikan negeri",
            mi="Whakakore wehenga",
        ),
    },
    {
        "value": "excludeStatesPh",
        "order": 51,
        "translations": L(
            es="Ej. Tartaria...", en="E.g. Tartaria...",
            pt="Ex. Tartária...", fr="Ex. Tartarie...",
            de="Z. B. Tartaria...", it="Es. Tartaria...",
            ru="Напр. Тартария...", sv="T.ex. Tartarien...",
            nl="Bijv. Tartarije...", zh="例如：塔尔塔利亚…",
            hi="जैसे टार्टारिया...", bn="যেমন টারটারিয়া...",
            ja="例：タルタリア…", ko="예: 타르타리아…",
            ar="مثال: تارتاريا...",
            sw="Mf. Tartaria...", ha="Mis. Tartaria...",
            am="ምሳሌ ታርታሪያ…", tl="Hal. Tartaria...",
            ms="Cth. Tartaria...", mi="Hei tauira: Tartaria…",
        ),
    },
    {
        "value": "excludeCountriesPh",
        "order": 52,
        "translations": L(
            es="Ej. Wakanda...", en="E.g. Wakanda...",
            pt="Ex. Wakanda...", fr="Ex. Wakanda...",
            de="Z. B. Wakanda...", it="Es. Wakanda...",
            ru="Напр. Ваканда...", sv="T.ex. Wakanda...",
            nl="Bijv. Wakanda...", zh="例如：瓦坎达…",
            hi="जैसे वकांडा...", bn="যেমন ওয়াকান্ডা...",
            ja="例：ワカンダ…", ko="예: 와칸다…",
            ar="مثال: واكاندا...",
            sw="Mf. Wakanda...", ha="Mis. Wakanda...",
            am="ምሳሌ ዋካንዳ…", tl="Hal. Wakanda...",
            ms="Cth. Wakanda...", mi="Hei tauira: Wakanda…",
        ),
    },
    {
        "value": "exceptPrefix",
        "order": 53,
        "translations": L(
            es="Excepto: ", en="Except: ",
            pt="Exceto: ", fr="Sauf : ",
            de="Außer: ", it="Tranne: ",
            ru="Кроме: ", sv="Utom: ",
            nl="Behalve: ", zh="除了：",
            hi="सिवाय: ", bn="ছাড়া: ",
            ja="除外：", ko="제외: ",
            ar="باستثناء: ", sw="Isipokuwa: ",
            ha="Sai: ", am="በስተቀር፦ ",
            tl="Maliban sa: ", ms="Kecuali: ",
            mi="Haunga:",
        ),
    },
    {
        "value": "oneContinent",
        "order": 54,
        "translations": L(
            es="Solo puedes seleccionar un continente completo a la vez.",
            en="You can only select one full continent at a time.",
            pt="Você só pode selecionar um continente inteiro por vez.",
            fr="Tu ne peux sélectionner qu'un continent entier à la fois.",
            de="Du kannst nur einen ganzen Kontinent auf einmal wählen.",
            it="Puoi selezionare un solo continente intero alla volta.",
            ru="Можно выбрать только один целый континент за раз.",
            sv="Du kan bara välja en hel kontinent åt gången.",
            nl="Je kunt slechts één volledig continent tegelijk selecteren.",
            zh="一次只能选择一整个大洲。",
            hi="एक बार में केवल एक पूरा महाद्वीप चुन सकते हैं।",
            bn="একবারে শুধু একটি সম্পূর্ণ মহাদেশ বেছে নিতে পারেন।",
            ja="一度に選択できる大陸全体は1つのみです。",
            ko="한 번에 하나의 대륙 전체만 선택할 수 있습니다.",
            ar="يمكنك اختيار قارة كاملة واحدة فقط في المرة.",
            sw="Unaweza kuchagua bara zima moja tu kwa wakati.",
            ha="Za ka iya zaɓar nahiya ɗaya cikakkiya kawai a lokaci ɗaya.",
            am="በአንድ ጊዜ አንድ ሙሉ አህጉር ብቻ መምረጥ ትችላለህ።",
            tl="Isang buong kontinente lang ang maaari mong piliin sa isang pagkakataon.",
            ms="Anda hanya boleh memilih satu benua penuh pada satu masa.",
            mi="Kotahi te paparahi katoa ka taea te kōwhiri i te wā kotahi.",
        ),
    },
    {
        "value": "infoModal.title",
        "order": 55,
        "translations": L(
            es="¿Por qué pedimos tu ubicación?", en="Why do we ask for your location?",
            pt="Por que pedimos sua localização?", fr="Pourquoi demandons-nous ta position ?",
            de="Warum fragen wir nach deinem Standort?", it="Perché chiediamo la tua posizione?",
            ru="Зачем нам ваше местоположение?", sv="Varför frågar vi efter din plats?",
            nl="Waarom vragen we je locatie?", zh="为什么需要你的位置？",
            hi="हम आपका स्थान क्यों मांगते हैं?", bn="আমরা আপনার অবস্থান কেন চাই?",
            ja="位置情報を求める理由", ko="위치를 묻는 이유",
            ar="لماذا نطلب موقعك؟", sw="Kwa nini tunauliza mahali ulipo?",
            ha="Me ya sa muke tambayar wurinka?", am="አካባቢህን ለምን እንጠይቃለን?",
            tl="Bakit namin hinihingi ang lokasyon mo?", ms="Mengapa kami meminta lokasi anda?",
            mi="He aha mātou i tono ai i tō wāhi?",
        ),
    },
    {
        "value": "infoModal.text",
        "order": 56,
        "translations": L(
            es="Tu ubicación nos ayuda a mostrarte personas cercanas y a definir el alcance de tus conexiones. Nunca compartiremos tu ubicación exacta sin tu consentimiento.",
            en="Your location helps us show nearby people and define your connection scope. We will never share your exact location without consent.",
            pt="Sua localização nos ajuda a mostrar pessoas próximas e definir o alcance das conexões. Nunca compartilharemos sua localização exata sem consentimento.",
            fr="Ta position nous aide à montrer des personnes proches et à définir ta portée. Nous ne partagerons jamais ta position exacte sans consentement.",
            de="Dein Standort hilft uns, Personen in der Nähe zu zeigen. Wir geben deinen genauen Standort nie ohne Zustimmung weiter.",
            it="La tua posizione ci aiuta a mostrarti persone vicine. Non condivideremo mai la tua posizione esatta senza consenso.",
            ru="Местоположение помогает показывать людей рядом. Мы никогда не передадим точное местоположение без согласия.",
            sv="Din plats hjälper oss visa personer i närheten. Vi delar aldrig din exakta plats utan samtycke.",
            nl="Je locatie helpt ons mensen in de buurt te tonen. We delen nooit je exacte locatie zonder toestemming.",
            zh="你的位置帮助我们展示附近的人。未经同意绝不分享精确位置。",
            hi="आपका स्थान आस-पास के लोग दिखाने में मदद करता है। बिना सहमति सटीक स्थान साझा नहीं करेंगे।",
            bn="আপনার অবস্থান কাছের মানুষ দেখাতে সাহায্য করে। সম্মতি ছাড়া সঠিক অবস্থান ভাগ করব না।",
            ja="位置情報は近くの人を表示するために使います。同意なく正確な位置を共有しません。",
            ko="위치는 근처의 사람을 보여주는 데 사용됩니다. 동의 없이 정확한 위치를 공유하지 않습니다.",
            ar="يساعدنا موقعك في عرض الأشخاص القريبين. لن نشارك موقعك الدقيق دون موافقة.",
            sw="Mahali pako hutusaidia kuonyesha watu wa karibu. Hatutashiriki mahali kamili bila ridhaa.",
            ha="Wurinka yana taimaka mana nuna mutanen kusa. Ba za mu raba ainihin wurinka ba tare da izini ba.",
            am="አካባቢህ በአቅራቢያ ያሉ ሰዎችን እንድናሳይ ይረዳናል። ትክክለኛ አካባቢህን ያለ እርስዎ ፈቃድ አናጋራም።",
            tl="Tinutulungan kami ng lokasyon mo na magpakita ng malalapit na tao. Hindi namin ibabahagi ang eksaktong lokasyon nang walang pahintulot.",
            ms="Lokasi anda membantu kami menunjukkan orang berdekatan. Kami tidak akan berkongsi lokasi tepat tanpa keizinan.",
            mi="Mā tō wāhi e āhei ai mātou ki te whakaatu i ngā tāngata tata. E kore rawa e tuari i tō wāhi tino whai whakaaetanga.",
        ),
    },
    {
        "value": "infoModal.button",
        "order": 57,
        "translations": L(
            es="Entendido", en="Got it",
            pt="Entendido", fr="Compris",
            de="Verstanden", it="Capito",
            ru="Понял", sv="Fattat",
            nl="Begrepen", zh="明白了",
            hi="समझ गया", bn="বুঝেছি",
            ja="了解", ko="알겠어요",
            ar="فهمت", sw="Nimeelewa",
            ha="Na gane", am="ገብቶኛል",
            tl="Naintindihan", ms="Faham",
            mi="Kua mārama",
        ),
    },
]

# Typo guard for accidental non-keyword arguments
for _item in TEXTS:
    assert set(_item["translations"]) == set(LANGS), _item["value"]

_VALUES = [item["value"] for item in TEXTS]
assert len(_VALUES) == len(set(_VALUES)), "duplicate seed values"
assert len(TEXTS) == 58, f"expected 58 texts, got {len(TEXTS)}"


async def main() -> None:
    await init_db()
    created = 0
    updated = 0
    for item in TEXTS:
        value = item["value"]
        order = item["order"]
        translations = item["translations"]

        existing = await SystemOption.find_one(
            SystemOption.category == "profile_location_section",
            SystemOption.value == value,
        )

        doc_data = {
            "category": "profile_location_section",
            "value": value,
            "label": translations["es"],
            "order": order,
            "is_active": True,
        }
        for lang in LANGS:
            doc_data[f"label_{lang}"] = translations.get(lang, "")

        if existing:
            for key, val in doc_data.items():
                setattr(existing, key, val)
            await existing.save()
            updated += 1
        else:
            await SystemOption(**doc_data).insert()
            created += 1

    print(
        f"seed_profile_location_section: created {created}, "
        f"updated {updated}, total {len(TEXTS)}"
    )


if __name__ == "__main__":
    asyncio.run(main())
