"""
Seed the `profile_progress_section` system options catalog for the profile
completion widget (progress hints + suggestion checklist).

Keys resolve flat as profile.complete, profile.completionHint70, ... and
nested as profile.suggestions.{messageKey} via dots.

Idempotent: upserts every value so re-running refreshes translations.
Run inside the backend container:
    docker exec -w /app redthread-backend python seed/seed_profile_progress_section.py
"""

import asyncio
import os
import sys

# Add the project root to sys.path
sys.path.append(os.getcwd())

from src.core.database import init_db
from src.models.system_options import SystemOption

LANGS = [
    "es", "en", "pt", "fr", "de", "it", "ru", "sv", "nl", "zh",
    "hi", "bn", "ja", "ko", "ar", "sw", "ha", "am", "tl", "ms", "mi",
]


def L(**kw) -> dict:
    """Language-specific text. Raises if any supported language is missing."""
    missing = [lang for lang in LANGS if lang not in kw]
    if missing:
        raise ValueError(f"missing languages: {missing}")
    unknown = [key for key in kw if key not in LANGS]
    if unknown:
        raise ValueError(f"unknown languages: {unknown}")
    return kw


TEXTS = [
    {
        "value": "complete",
        "order": 0,
        "translations": L(
            es="Perfil completo", en="Complete profile",
            pt="Perfil completo", fr="Profil complet",
            de="Vollständiges Profil", it="Profilo completo",
            ru="Профиль заполнен", sv="Komplett profil",
            nl="Volledig profiel", zh="资料完整",
            hi="पूर्ण प्रोफ़ाइल", bn="সম্পূর্ণ প্রোফাইল",
            ja="プロフィール完成", ko="프로필 완성",
            ar="الملف مكتمل", sw="Wasifu umekamilika",
            ha="Bayani ya cika", am="መገለጫ ተሟልቷል",
            tl="Kumpleto ang profile", ms="Profil lengkap",
            mi="Kua oti te kōtaha",
        ),
    },
    {
        "value": "incomplete",
        "order": 1,
        "translations": L(
            es="Perfil incompleto", en="Incomplete profile",
            pt="Perfil incompleto", fr="Profil incomplet",
            de="Unvollständiges Profil", it="Profilo incompleto",
            ru="Профиль не заполнен", sv="Ofullständig profil",
            nl="Onvolledig profiel", zh="资料未完整",
            hi="अपूर्ण प्रोफ़ाइल", bn="অসম্পূর্ণ প্রোফাইল",
            ja="プロフィール未完成", ko="프로필 미완성",
            ar="الملف غير مكتمل", sw="Wasifu hauj kamilika",
            ha="Bayani bai cika ba", am="መገለጫ ያልተሟላ",
            tl="Hindi kumpletong profile", ms="Profil tidak lengkap",
            mi="Kāore anō kia oti te kōtaha",
        ),
    },
    {
        "value": "completionHint0",
        "order": 2,
        "translations": L(
            es="Completa tu información básica para empezar.",
            en="Complete your basic info to get started.",
            pt="Complete suas informações básicas para começar.",
            fr="Complète tes infos de base pour commencer.",
            de="Vervollständige deine Basisinfos für den Start.",
            it="Completa le informazioni di base per iniziare.",
            ru="Заполните основную информацию для начала.",
            sv="Fyll i din grundinfo för att börja.",
            nl="Vul je basisinfo in om te beginnen.",
            zh="先完善你的基本资料吧。",
            hi="शुरू करने हेतु बुनियादी जानकारी पूरी करें।",
            bn="শুরু করতে মৌলিক তথ্য পূরণ করুন।",
            ja="まずは基本情報を入力しよう。",
            ko="시작하려면 기본 정보를 입력하세요.",
            ar="أكمل معلوماتك الأساسية للبدء.",
            sw="Jaza taarifa zako za msingi kuanza.",
            ha="Cika ainihin bayananka don farawa.",
            am="ለመጀመር መሠረታዊ መረጃህን ሙላ።",
            tl="Kumpletuhin ang pangunahing impormasyon para magsimula.",
            ms="Lengkapkan maklumat asas untuk bermula.",
            mi="Whakakīa ō pārongo taketake kia tīmata ai.",
        ),
    },
    {
        "value": "completionHint30",
        "order": 3,
        "translations": L(
            es="¡Vas bien! Agrega más detalles para destacar.",
            en="Good progress! Add more details to stand out.",
            pt="Bom progresso! Adicione detalhes para se destacar.",
            fr="Bien parti ! Ajoute des détails pour te démarquer.",
            de="Gut gemacht! Füge Details hinzu, um aufzufallen.",
            it="Ben fatto! Aggiungi dettagli per distinguerti.",
            ru="Хороший прогресс! Добавьте деталей, чтобы выделиться.",
            sv="Bra jobbat! Lägg till detaljer för att sticka ut.",
            nl="Goed bezig! Voeg details toe om op te vallen.",
            zh="不错！多加点细节让自己脱颖而出。",
            hi="बढ़िया! अलग दिखने हेतु विवरण जोड़ें।",
            bn="ভালো অগ্রগতি! আলাদা হতে বিশদ যোগ করুন।",
            ja="いい調子！目立つために詳細を追加しよう。",
            ko="잘하고 있어요! 돋보이려면 세부 정보를 추가하세요.",
            ar="تقدم جيد! أضف تفاصيل لتتميز.",
            sw="Nzuri! Ongeza maelezo ili ujitokeze.",
            ha="Madalla! Ƙara bayanai don ficewa.",
            am="ጥሩ እድገት! ለመ menonjol ዝርዝሮችን ጨምር።",
            tl="Ayos! Magdagdag ng detalye para tumayo.",
            ms="Bagus! Tambah butiran untuk menyerlah.",
            mi="Ka pai! Tāpirihia ētahi kōrero kia tū motuhake ai.",
        ),
    },
    {
        "value": "completionHint70",
        "order": 4,
        "translations": L(
            es="¡Casi listo! Tu perfil se ve genial.",
            en="Almost there! Your profile looks great.",
            pt="Quase lá! Seu perfil está ótimo.",
            fr="Presque fini ! Ton profil est super.",
            de="Fast geschafft! Dein Profil sieht toll aus.",
            it="Quasi fatto! Il tuo profilo è fantastico.",
            ru="Почти готово! Ваш профиль выглядит отлично.",
            sv="Nästan klart! Din profil ser strålande ut.",
            nl="Bijna klaar! Je profiel ziet er top uit.",
            zh="快完成了！你的资料看起来很棒。",
            hi="लगभग तैयार! आपकी प्रोफ़ाइल शानदार लग रही है।",
            bn="প্রায় শেষ! আপনার প্রোফাইল দারুণ দেখাচ্ছে।",
            ja="あと少し！プロフィールいい感じだよ。",
            ko="거의 다 됐어요! 프로필이 멋져요.",
            ar="أوشكت على الانتهاء! ملفك يبدو رائعًا.",
            sw="Karibu kumaliza! Wasifu wako unaonekana vizuri.",
            ha="Kusan ka gama! Bayaninka yana da kyau.",
            am="ሊጠናቀቅ ጥቂት қалды! መገለጫህ ድንቅ ይመስላል።",
            tl="Malapit na! Ang ganda ng profile mo.",
            ms="Hampir siap! Profil anda kelihatan hebat.",
            mi="Tata kore! Ka rawe tō kōtaha.",
        ),
    },
    {
        "value": "completionHint100",
        "order": 5,
        "translations": L(
            es="¡Excelente! Tu perfil está al máximo nivel 🌟",
            en="Excellent! Your profile is maxed out 🌟",
            pt="Excelente! Seu perfil está no nível máximo 🌟",
            fr="Excellent ! Ton profil est au max 🌟",
            de="Exzellent! Dein Profil ist auf Top-Level 🌟",
            it="Eccellente! Il tuo profilo è al massimo 🌟",
            ru="Отлично! Ваш профиль на максимуме 🌟",
            sv="Utmärkt! Din profil är maxad 🌟",
            nl="Uitstekend! Je profiel is maximaal 🌟",
            zh="太棒了！你的资料已满级 🌟",
            hi="शानदार! आपकी प्रोफ़ाइल शीर्ष स्तर पर है 🌟",
            bn="চমৎকার! আপনার প্রোফাইল সর্বোচ্চ স্তরে 🌟",
            ja="最高！プロフィールはMAXレベルだよ 🌟",
            ko="훌륭해요! 프로필이 최고 레벨이에요 🌟",
            ar="ممتاز! ملفك في أعلى مستوى 🌟",
            sw="Bora! Wasifu wako uko kiwango cha juu 🌟",
            ha="Madalla! Bayaninka ya kai mataki mafi girma 🌟",
            am=" በጣም ጥሩ! መገለጫህ ከፍተኛ ደረጃ ላይ ነው 🌟",
            tl="Napakagaling! Nasa max level na ang profile mo 🌟",
            ms="Cemerlang! Profil anda di tahap maksimum 🌟",
            mi="Tino pai! Kua eke tō kōtaha ki te taumata teitei 🌟",
        ),
    },
    {
        "value": "suggestionsTitle",
        "order": 6,
        "translations": L(
            es="Sugerencias para completar tu perfil:",
            en="Suggestions to complete your profile:",
            pt="Sugestões para completar seu perfil:",
            fr="Suggestions pour compléter ton profil :",
            de="Vorschläge zur Vervollständigung:",
            it="Suggerimenti per completare il profilo:",
            ru="Советы для заполнения профиля:",
            sv="Förslag för att fylla i profilen:",
            nl="Suggesties om je profiel af te maken:",
            zh="完善资料的建议：",
            hi="प्रोफ़ाइल पूर्ण हेतु सुझाव:",
            bn="প্রোফাইল সম্পূর্ণ করতে পরামর্শ:",
            ja="プロフィールを完成させるヒント：",
            ko="프로필 완성을 위한 제안:",
            ar="اقتراحات لاستكمال ملفك:",
            sw="Mapendekezo ya kukamilisha wasifu:",
            ha="Shawarwari don kammala bayani:",
            am="መገለጫህን ለማጠናቀቅ ұсыныстар፦",
            tl="Mga mungkahi para kumpletuhin ang profile:",
            ms="Cadangan untuk melengkapkan profil:",
            mi="Ngā marohi hei whakaoti i tō kōtaha:",
        ),
    },
    {
        "value": "suggestions.sexualOrientation",
        "order": 7,
        "translations": L(
            es="Define tu orientación sexual", en="Define your sexual orientation",
            pt="Defina sua orientação sexual", fr="Définis ton orientation sexuelle",
            de="Definiere deine sexuelle Orientierung", it="Definisci il tuo orientamento sessuale",
            ru="Укажите сексуальную ориентацию", sv="Definiera din sexuella läggning",
            nl="Bepaal je seksuele oriëntatie", zh="设置你的性取向",
            hi="यौन अभिविन्यास निर्धारित करें", bn="যৌন অভিমুখ নির্ধারণ করুন",
            ja="性的指向を設定", ko="성적 지향 설정",
            ar="حدد توجهك الجنسي", sw="Bainisha mwelekeo wako wa kingono",
            ha="Ƙayyade yanayin jima'inka", am="የወሲብ ዝንባሌህን ግለጽ",
            tl="Tukuyin ang oryentasyong sekswal", ms="Tentukan orientasi seksual",
            mi="Tautuhia tō ia whakapapa",
        ),
    },
    {
        "value": "suggestions.relationshipGoals",
        "order": 8,
        "translations": L(
            es="Define qué tipo de relación buscas", en="Define what relationship you seek",
            pt="Defina que tipo de relação busca", fr="Définis le type de relation cherchée",
            de="Definiere, welche Beziehung du suchst", it="Definisci che tipo di relazione cerchi",
            ru="Укажите, какие отношения ищете", sv="Definiera vilken relation du söker",
            nl="Bepaal welk type relatie je zoekt", zh="明确你想找的关系类型",
            hi="कैसा रिश्ता चाहते हैं बताएं", bn="কেমন সম্পর্ক চান নির্ধারণ করুন",
            ja="求める関係の形を設定", ko="찾는 관계 유형 정하기",
            ar="حدد نوع العلاقة التي تبحث عنها", sw="Bainisha aina ya uhusiano unaotafuta",
            ha="Ƙayyade irin dangantakar da kake nema", am="የምትፈልገውን የግንኙነት አይነት ግለጽ",
            tl="Tukuyin kung anong relasyon ang hanap", ms="Tentukan jenis hubungan yang dicari",
            mi="Tautuhia te momo hononga e rapu ana",
        ),
    },
    {
        "value": "suggestions.nickname",
        "order": 9,
        "translations": L(
            es="Agrega un nickname", en="Add a nickname",
            pt="Adicione um apelido", fr="Ajoute un pseudo",
            de="Füge einen Nickname hinzu", it="Aggiungi un nickname",
            ru="Добавьте никнейм", sv="Lägg till ett smeknamn",
            nl="Voeg een bijnaam toe", zh="添加一个昵称",
            hi="उपनाम जोड़ें", bn="ডাকনাম যোগ করুন",
            ja="ニックネームを追加", ko="닉네임 추가",
            ar="أضف لقبًا", sw="Ongeza jina la utani",
            ha="Ƙara laƙabi", am="ቅጽል ስም ጨምር",
            tl="Magdagdag ng palayaw", ms="Tambah nama samaran",
            mi="Tāpiri ingoa karanga",
        ),
    },
    {
        "value": "suggestions.gender",
        "order": 10,
        "translations": L(
            es="Selecciona tu género", en="Select your gender",
            pt="Selecione seu gênero", fr="Sélectionne ton genre",
            de="Wähle dein Geschlecht", it="Seleziona il tuo genere",
            ru="Укажите ваш гендер", sv="Välj ditt kön",
            nl="Selecteer je gender", zh="选择你的性别",
            hi="लिंग चुनें", bn="লিঙ্গ নির্বাচন করুন",
            ja="性別を選択", ko="성별 선택",
            ar="اختر جنسك", sw="Chagua jinsia yako",
            ha="Zaɓi jinsinka", am="ጾታህን ምረጥ",
            tl="Piliin ang kasarian", ms="Pilih jantina",
            mi="Tīpakohia tō ira",
        ),
    },
    {
        "value": "suggestions.bio",
        "order": 11,
        "translations": L(
            es="Escribe algo interesante en 'Sobre mí'",
            en="Write something interesting in 'About me'",
            pt="Escreva algo interessante em 'Sobre mim'",
            fr="Écris quelque chose d'intéressant dans « À propos »",
            de="Schreib etwas Interessantes in „Über mich“",
            it="Scrivi qualcosa di interessante in 'Su di me'",
            ru="Напишите что-нибудь интересное в «Обо мне»",
            sv="Skriv något intressant i 'Om mig'",
            nl="Schrijf iets interessants bij 'Over mij'",
            zh="在“关于我”里写点有趣的",
            hi="'मेरे बारे में' में कुछ रोचक लिखें",
            bn="'আমার সম্পর্কে'-তে মজার কিছু লিখুন",
            ja="「自己紹介」に面白いことを書こう",
            ko="'자기소개'에 재미있는 내용 쓰기",
            ar="اكتب شيئًا مثيرًا في 'عني'",
            sw="Andika jambo la kuvutia katika 'Kuhusu mimi'",
            ha="Rubuta wani abu mai ban sha'awa a 'Game da ni'",
            am="በ'ስለ እኔ' ውስጥ አስደሳች ነገር ጻፍ",
            tl="Sumulat ng kawili-wili sa 'Tungkol sa akin'",
            ms="Tulis sesuatu yang menarik dalam 'Tentang saya'",
            mi="Tuhia tētahi mea pārekareka ki 'Mōku'",
        ),
    },
    {
        "value": "suggestions.photos",
        "order": 12,
        "translations": L(
            es="Sube al menos una foto para que te conozcan",
            en="Upload at least one photo so they know you",
            pt="Suba ao menos uma foto para te conhecerem",
            fr="Ajoute au moins une photo pour qu'on te connaisse",
            de="Lade mindestens ein Foto hoch",
            it="Carica almeno una foto per farti conoscere",
            ru="Загрузите хотя бы одно фото",
            sv="Ladda upp minst ett foto",
            nl="Upload minstens één foto",
            zh="至少上传一张照片",
            hi="कम से कम एक फोटो अपलोड करें",
            bn="অন্তত একটি ছবি আপলোড করুন",
            ja="写真を1枚以上アップしよう",
            ko="사진을 최소 한 장 업로드하세요",
            ar="ارفع صورة واحدة على الأقل",
            sw="Pakia angalau picha moja",
            ha="Loda aƙalla hoto ɗaya",
            am="ቢያንስ አንድ ፎቶ ስቀል",
            tl="Mag-upload ng kahit isang larawan",
            ms="Muat naik sekurang-kurangnya satu foto",
            mi="Tukuake kia kotahi whakaahua",
        ),
    },
    {
        "value": "suggestions.interests",
        "order": 13,
        "translations": L(
            es="Selecciona al menos un interés o estilo de vida",
            en="Select at least one interest or lifestyle",
            pt="Selecione ao menos um interesse ou estilo de vida",
            fr="Sélectionne au moins un centre d'intérêt",
            de="Wähle mindestens ein Interesse",
            it="Seleziona almeno un interesse o stile di vita",
            ru="Выберите хотя бы один интерес",
            sv="Välj minst ett intresse",
            nl="Selecteer minstens één interesse",
            zh="至少选择一个兴趣",
            hi="कम से कम एक रुचि चुनें",
            bn="অন্তত একটি আগ্রহ বেছে নিন",
            ja="興味を1つ以上選択",
            ko="관심사를 최소 하나 선택하세요",
            ar="اختر اهتمامًا واحدًا على الأقل",
            sw="Chagua angalau jambo moja unalopenda",
            ha="Zaɓi aƙalla sha'awa ɗaya",
            am="ቢያንስ አንድ ፍላጎት ምረጥ",
            tl="Pumili ng kahit isang interes",
            ms="Pilih sekurang-kurangnya satu minat",
            mi="Tīpakohia kia kotahi kaingākau",
        ),
    },
    {
        "value": "suggestions.relationshipStatus",
        "order": 14,
        "translations": L(
            es="¿Cuál es tu estado civil?", en="What is your relationship status?",
            pt="Qual é seu estado civil?", fr="Quel est ton statut relationnel ?",
            de="Wie ist dein Beziehungsstatus?", it="Qual è il tuo stato sentimentale?",
            ru="Ваше семейное положение?", sv="Vilken är din relationsstatus?",
            nl="Wat is je relatiestatus?", zh="你的感情状态是？",
            hi="आपकी वैवाहिक स्थिति क्या है?", bn="আপনার বৈবাহিক অবস্থা কী?",
            ja="交際ステータスは？", ko="연애 상태는?",
            ar="ما حالتك الاجتماعية؟", sw="Hali yako ya uhusiano ni ipi?",
            ha="Mene ne matsayin auratayyarka?", am="የጋብቻ ሁኔታህ ምንድነው?",
            tl="Ano ang civil status mo?", ms="Apakah status hubungan anda?",
            mi="He aha tō tūnga hononga?",
        ),
    },
    {
        "value": "suggestions.relationshipType",
        "order": 15,
        "translations": L(
            es="¿Qué tipo de relación prefieres?", en="What relationship type do you prefer?",
            pt="Que tipo de relação você prefere?", fr="Quel type de relation préfères-tu ?",
            de="Welche Beziehungsart bevorzugst du?", it="Che tipo di relazione preferisci?",
            ru="Какой тип отношений предпочитаете?", sv="Vilken relationstyp föredrar du?",
            nl="Welk relatietype verkies je?", zh="你更喜欢哪种关系类型？",
            hi="किस तरह का रिश्ता पसंद है?", bn="কোন ধরনের সম্পর্ক পছন্দ করেন?",
            ja="どんな関係が好み？", ko="어떤 관계 유형을 선호하나요?",
            ar="ما نوع العلاقة الذي تفضله؟", sw="Unapendelea aina gani ya uhusiano?",
            ha="Wane irin dangantaka ka fi so?", am="የየትኛውን የግንኙነት አይነት ትመርጣለህ?",
            tl="Anong uri ng relasyon ang gusto mo?", ms="Jenis hubungan apa yang anda suka?",
            mi="He aha te momo hononga e pai ana ki a koe?",
        ),
    },
    {
        "value": "suggestions.zodiac",
        "order": 16,
        "translations": L(
            es="Agrega tu signo zodiacal", en="Add your zodiac sign",
            pt="Adicione seu signo", fr="Ajoute ton signe astro",
            de="Füge dein Sternzeichen hinzu", it="Aggiungi il tuo segno zodiacale",
            ru="Добавьте знак зодиака", sv="Lägg till ditt stjärntecken",
            nl="Voeg je sterrenbeeld toe", zh="添加你的星座",
            hi="राशि जोड़ें", bn="রাশি যোগ করুন",
            ja="星座を追加", ko="별자리 추가",
            ar="أضف برجك", sw="Ongeza ishara yako ya nyota",
            ha="Ƙara alamar tauraro", am="የዞዲያክ ምልክትህን ጨምር",
            tl="Idagdag ang zodiac sign", ms="Tambah tanda zodiak",
            mi="Tāpiri tō tohu whetū",
        ),
    },
    {
        "value": "suggestions.educationLevel",
        "order": 17,
        "translations": L(
            es="Completa tu nivel educativo", en="Complete your education level",
            pt="Complete seu nível educacional", fr="Complète ton niveau d'études",
            de="Vervollständige deinen Bildungsstand", it="Completa il tuo livello di istruzione",
            ru="Укажите уровень образования", sv="Fyll i din utbildningsnivå",
            nl="Vul je opleidingsniveau in", zh="完善你的教育程度",
            hi="शैक्षणिक स्तर पूरा करें", bn="শিক্ষার স্তর পূরণ করুন",
            ja="学歴を入力", ko="학력 입력",
            ar="أكمل مستواك التعليمي", sw="Kamilisha kiwango chako cha elimu",
            ha="Cika matakin iliminka", am="የትምህርት ደረጃህን ሙላ",
            tl="Kumpletuhin ang antas ng edukasyon", ms="Lengkapkan tahap pendidikan",
            mi="Whakaotia tō taumata mātauranga",
        ),
    },
    {
        "value": "suggestions.occupation",
        "order": 18,
        "translations": L(
            es="Añade tu profesión", en="Add your occupation",
            pt="Adicione sua profissão", fr="Ajoute ta profession",
            de="Füge deinen Beruf hinzu", it="Aggiungi la tua professione",
            ru="Добавьте профессию", sv="Lägg till ditt yrke",
            nl="Voeg je beroep toe", zh="添加你的职业",
            hi="पेशा जोड़ें", bn="পেশা যোগ করুন",
            ja="職業を追加", ko="직업 추가",
            ar="أضف مهنتك", sw="Ongeza kazi yako",
            ha="Ƙara sana'arka", am="ሙያህን ጨምር",
            tl="Idagdag ang propesyon", ms="Tambah pekerjaan",
            mi="Tāpiri tō umanga",
        ),
    },
    {
        "value": "suggestions.educationCenter",
        "order": 19,
        "translations": L(
            es="¿Dónde estudiaste?", en="Where did you study?",
            pt="Onde você estudou?", fr="Où as-tu étudié ?",
            de="Wo hast du studiert?", it="Dove hai studiato?",
            ru="Где вы учились?", sv="Var studerade du?",
            nl="Waar heb je gestudeerd?", zh="你在哪里上学？",
            hi="आपने कहाँ पढ़ाई की?", bn="কোথায় পড়াশোনা করেছেন?",
            ja="どこで学んだ？", ko="어디서 공부했나요?",
            ar="أين درست؟", sw="Ulisomea wapi?",
            ha="Ina ka yi karatu?", am="የት ተምረሃል?",
            tl="Saan ka nag-aral?", ms="Di mana anda belajar?",
            mi="I ako koe ki hea?",
        ),
    },
    {
        "value": "suggestions.workCompany",
        "order": 20,
        "translations": L(
            es="Indica dónde trabajas", en="Tell where you work",
            pt="Indique onde trabalha", fr="Indique où tu travailles",
            de="Gib an, wo du arbeitest", it="Indica dove lavori",
            ru="Укажите, где работаете", sv="Ange var du jobbar",
            nl="Geef aan waar je werkt", zh="填写你的工作单位",
            hi="बताएं कहाँ काम करते हैं", bn="কোথায় কাজ করেন জানান",
            ja="勤務先を入力", ko="직장을 입력하세요",
            ar="اذكر أين تعمل", sw="Eleza unapofanya kazi",
            ha="Nuna inda kake aiki", am="የምትሠራበትን ቦታ ግለጽ",
            tl="Ilagay kung saan nagtatrabaho", ms="Nyatakan tempat anda bekerja",
            mi="Whakaaturia tō wāhi mahi",
        ),
    },
    {
        "value": "suggestions.languages",
        "order": 21,
        "translations": L(
            es="¿Qué idiomas hablas?", en="Which languages do you speak?",
            pt="Quais idiomas você fala?", fr="Quelles langues parles-tu ?",
            de="Welche Sprachen sprichst du?", it="Quali lingue parli?",
            ru="На каких языках вы говорите?", sv="Vilka språk talar du?",
            nl="Welke talen spreek je?", zh="你会说什么语言？",
            hi="कौन-सी भाषाएँ बोलते हैं?", bn="কোন ভাষায় কথা বলেন?",
            ja="話せる言語は？", ko="어떤 언어를 하세요?",
            ar="ما اللغات التي تتحدثها؟", sw="Unazungumza lugha gani?",
            ha="Wadanne harsuna kake magana?", am="የraznትኞች ቋንቋዎች ትናገራለህ?",
            tl="Anong mga wika ang sinasalita mo?", ms="Bahasa apa yang anda tuturkan?",
            mi="He aha ngā reo e kōrero ana koe?",
        ),
    },
    {
        "value": "suggestions.pronouns",
        "order": 22,
        "translations": L(
            es="Agrega tus pronombres", en="Add your pronouns",
            pt="Adicione seus pronomes", fr="Ajoute tes pronoms",
            de="Füge deine Pronomen hinzu", it="Aggiungi i tuoi pronomi",
            ru="Добавьте местоимения", sv="Lägg till dina pronomen",
            nl="Voeg je voornaamwoorden toe", zh="添加你的代词",
            hi="सर्वनाम जोड़ें", bn="সর্বনাম যোগ করুন",
            ja="代名詞を追加", ko="대명사 추가",
            ar="أضف ضمائرك", sw="Ongeza viwakilishi vyako",
            ha="Ƙara wakilan sunanka", am="ተውላጠ ስሞችህን ጨምር",
            tl="Idagdag ang panghalip", ms="Tambah kata ganti",
            mi="Tāpiri ō tūwāhi",
        ),
    },
    {
        "value": "suggestions.musicConnect",
        "order": 23,
        "translations": L(
            es="Conecta tu música o agrega artistas favoritos",
            en="Connect your music or add favorite artists",
            pt="Conecte sua música ou adicione artistas favoritos",
            fr="Connecte ta musique ou ajoute des artistes préférés",
            de="Verbinde deine Musik oder füge Lieblingskünstler hinzu",
            it="Collega la tua musica o aggiungi artisti preferiti",
            ru="Подключите музыку или добавьте любимых артистов",
            sv="Anslut din musik eller lägg till favoritartister",
            nl="Koppel je muziek of voeg favoriete artiesten toe",
            zh="关联你的音乐或添加喜欢的艺人",
            hi="संगीत जोड़ें या पसंदीदा कलाकार जोड़ें",
            bn="সঙ্গীত সংযুক্ত করুন বা প্রিয় শিল্পী যোগ করুন",
            ja="音楽を連携するか好きなアーティストを追加",
            ko="음악을 연결하거나 좋아하는 아티스트 추가",
            ar="اربط موسيقاك أو أضف فنانين مفضلين",
            sw="Unganisha muziki wako au ongeza wasanii unaowapenda",
            ha="Haɗa kiɗanka ko ƙara mawakan da ka fi so",
            am="ሙዚቃህን አገናኝ ወይም የምትወዳቸው አርቲስቶችን ጨምር",
            tl="Ikonekta ang musika o magdagdag ng paboritong artist",
            ms="Sambungkan muzik atau tambah artis kegemaran",
            mi="Tūhonohia tō puoro, tāpirihia rānei ngā kaitito pai",
        ),
    },
    {
        "value": "suggestions.musicGenres",
        "order": 24,
        "translations": L(
            es="¿Qué géneros musicales te gustan?", en="Which music genres do you like?",
            pt="De quais gêneros musicais você gosta?", fr="Quels genres musicaux aimes-tu ?",
            de="Welche Musikgenres magst du?", it="Quali generi musicali ti piacciono?",
            ru="Какие музыкальные жанры вам нравятся?", sv="Vilka musikgenrer gillar du?",
            nl="Welke muziekgenres vind je leuk?", zh="你喜欢什么音乐类型？",
            hi="कौन-सी संगीत शैलियाँ पसंद हैं?", bn="কোন সঙ্গীত ধারা পছন্দ করেন?",
            ja="好きな音楽ジャンルは？", ko="좋아하는 음악 장르는?",
            ar="ما أنواع الموسيقى التي تحبها؟", sw="Unapenda aina gani za muziki?",
            ha="Wane irin kiɗa kake so?", am="የየትኞቹን የሙዚቃ አይነቶች ትወዳለህ?",
            tl="Anong genre ng musika ang gusto mo?", ms="Genre muzik apa yang anda suka?",
            mi="He aha ngā momo puoro e pai ana ki a koe?",
        ),
    },
    {
        "value": "suggestions.socialStyle",
        "order": 25,
        "translations": L(
            es="¿Cómo te defines socialmente?", en="How do you define yourself socially?",
            pt="Como você se define socialmente?", fr="Comment te définis-tu socialement ?",
            de="Wie definierst du dich sozial?", it="Come ti definisci socialmente?",
            ru="Как вы определяете себя в социуме?", sv="Hur definierar du dig socialt?",
            nl="Hoe definieer je jezelf sociaal?", zh="你如何定义自己的社交风格？",
            hi="सामाजिक रूप से खुद को कैसे परिभाषित करते हैं?", bn="সামাজিকভাবে নিজেকে কীভাবে সংজ্ঞায়িত করেন?",
            ja="社交スタイルをどう定義する？", ko="사회적으로 자신을 어떻게 정의하나요?",
            ar="كيف تعرف نفسك اجتماعيًا؟", sw="Unajieleza vipi kijamii?",
            ha="Yaya kake ayyana kanka a zamantakewa?", am="በማህበራዊ ረገድ ራስህን እንዴት ትገልጻለህ?",
            tl="Paano mo inilalarawan ang sarili sa lipunan?", ms="Bagaimana anda mentakrifkan diri secara sosial?",
            mi="Me pēhea koe e tautuhi ai i a koe ā-pāpori?",
        ),
    },
    {
        "value": "suggestions.neurodiversity",
        "order": 26,
        "translations": L(
            es="Agrega información sobre neurodiversidad",
            en="Add neurodiversity info",
            pt="Adicione informações sobre neurodiversidade",
            fr="Ajoute des infos sur la neurodiversité",
            de="Füge Infos zu Neurodiversität hinzu",
            it="Aggiungi info sulla neurodiversità",
            ru="Добавьте информацию о нейроразнообразии",
            sv="Lägg till info om neurodiversitet",
            nl="Voeg neurodiversiteitsinfo toe",
            zh="添加神经多样性信息",
            hi="न्यूरोडायवर्सिटी जानकारी जोड़ें",
            bn="নিউরোডাইভার্সিটি তথ্য যোগ করুন",
            ja="ニューロダイバーシティ情報を追加",
            ko="신경다양성 정보 추가",
            ar="أضف معلومات التنوع العصبي",
            sw="Ongeza maelezo ya neurodiversity",
            ha="Ƙara bayani game da neurodiversity",
            am="የኒውሮዳይቨርሲቲ መረጃ ጨምር",
            tl="Magdagdag ng impormasyon sa neurodiversity",
            ms="Tambah maklumat neurodiversiti",
            mi="Tāpiri pārongo kanorau ā-roro",
        ),
    },
    {
        "value": "suggestions.processingStyle",
        "order": 27,
        "translations": L(
            es="¿Cuál es tu estilo de procesamiento?", en="What is your processing style?",
            pt="Qual é seu estilo de processamento?", fr="Quel est ton style de traitement ?",
            de="Was ist dein Verarbeitungsstil?", it="Qual è il tuo stile di elaborazione?",
            ru="Какой у вас стиль обработки?", sv="Vilken är din bearbetningsstil?",
            nl="Wat is je verwerkingsstijl?", zh="你的信息处理风格是？",
            hi="आपकी प्रसंस्करण शैली क्या है?", bn="আপনার প্রক্রিয়াকরণ ধরন কী?",
            ja="情報処理スタイルは？", ko="정보 처리 스타일은?",
            ar="ما أسلوب المعالجة لديك؟", sw="Mtindo wako wa kuchakata ni upi?",
            ha="Menene salon sarrafa bayananka?", am="የሂደት ዘይቤህ ምንድነው?",
            tl="Ano ang estilo ng pagproseso mo?", ms="Apakah gaya pemprosesan anda?",
            mi="He aha tō kāhua tukatuka?",
        ),
    },
    {
        "value": "suggestions.riskTolerance",
        "order": 28,
        "translations": L(
            es="¿Cuál es tu tolerancia al riesgo?", en="What is your risk tolerance?",
            pt="Qual é sua tolerância ao risco?", fr="Quelle est ta tolérance au risque ?",
            de="Wie hoch ist deine Risikobereitschaft?", it="Qual è la tua tolleranza al rischio?",
            ru="Каково ваше отношение к риску?", sv="Vilken är din risktolerans?",
            nl="Wat is je risicotolerantie?", zh="你的风险承受力如何？",
            hi="जोखिम सहनशीलता कितनी है?", bn="ঝুঁকি সহনশীলতা কেমন?",
            ja="リスク許容度は？", ko="위험 감수 성향은?",
            ar="ما مدى تقبلك للمخاطرة؟", sw="Uvumilivu wako wa hatari ukoje?",
            ha="Menene juriyar haɗarinka?", am="ለስጋት ያለህ መቻቻል ምን ያህል ነው?",
            tl="Ano ang risk tolerance mo?", ms="Apakah toleransi risiko anda?",
            mi="He aha tō manawanui mōrearea?",
        ),
    },
    {
        "value": "suggestions.decisionMaking",
        "order": 29,
        "translations": L(
            es="¿Cómo tomas decisiones?", en="How do you make decisions?",
            pt="Como você toma decisões?", fr="Comment prends-tu tes décisions ?",
            de="Wie triffst du Entscheidungen?", it="Come prendi le decisioni?",
            ru="Как вы принимаете решения?", sv="Hur fattar du beslut?",
            nl="Hoe neem je beslissingen?", zh="你怎么做决定？",
            hi="निर्णय कैसे लेते हैं?", bn="সিদ্ধান্ত কীভাবে নেন?",
            ja="どうやって決める？", ko="어떻게 결정하나요?",
            ar="كيف تتخذ قراراتك؟", sw="Unafanya maamuzi vipi?",
            ha="Yaya kake yanke shawara?", am="እንዴት ውሳኔ ታደርጋለህ?",
            tl="Paano ka nagdedesisyon?", ms="Bagaimana anda membuat keputusan?",
            mi="Me pēhea koe e whakatau ai?",
        ),
    },
    {
        "value": "suggestions.disabilities",
        "order": 30,
        "translations": L(
            es="Agrega información sobre discapacidad",
            en="Add disability info",
            pt="Adicione informações sobre deficiência",
            fr="Ajoute des infos sur le handicap",
            de="Füge Infos zu Behinderung hinzu",
            it="Aggiungi info sulla disabilità",
            ru="Добавьте информацию об инвалидности",
            sv="Lägg till info om funktionsnedsättning",
            nl="Voeg handicapinfo toe",
            zh="添加残障信息",
            hi="विकलांगता जानकारी जोड़ें",
            bn="প্রতিবন্ধিতা তথ্য যোগ করুন",
            ja="障害情報を追加",
            ko="장애 정보 추가",
            ar="أضف معلومات الإعاقة",
            sw="Ongeza maelezo ya ulemavu",
            ha="Ƙara bayani game da nakasa",
            am="የአካል ጉዳት መረጃ ጨምር",
            tl="Magdagdag ng impormasyon sa kapansanan",
            ms="Tambah maklumat hilang upaya",
            mi="Tāpiri pārongo hauātanga",
        ),
    },
    {
        "value": "suggestions.health",
        "order": 31,
        "translations": L(
            es="Agrega información de salud", en="Add health info",
            pt="Adicione informações de saúde", fr="Ajoute des infos de santé",
            de="Füge Gesundheitsinfos hinzu", it="Aggiungi info sulla salute",
            ru="Добавьте информацию о здоровье", sv="Lägg till hälsoinfo",
            nl="Voeg gezondheidsinfo toe", zh="添加健康信息",
            hi="स्वास्थ्य जानकारी जोड़ें", bn="স্বাস্থ্য তথ্য যোগ করুন",
            ja="健康情報を追加", ko="건강 정보 추가",
            ar="أضف معلومات صحية", sw="Ongeza maelezo ya afya",
            ha="Ƙara bayanin lafiya", am="የጤና መረጃ ጨምር",
            tl="Magdagdag ng impormasyong pangkalusugan", ms="Tambah maklumat kesihatan",
            mi="Tāpiri pārongo hauora",
        ),
    },
    {
        "value": "suggestions.energyLevel",
        "order": 32,
        "translations": L(
            es="¿Eres matutino o nocturno?", en="Are you a morning or night person?",
            pt="Você é matutino ou noturno?", fr="Tu es du matin ou du soir ?",
            de="Bist du Morgen- oder Nachtmensch?", it="Sei mattiniero o nottambulo?",
            ru="Вы жаворонок или сова?", sv="Är du morgon- eller kvällsmänniska?",
            nl="Ben je een ochtend- of avondmens?", zh="你是早起型还是夜猫子？",
            hi="सुबह के हैं या रात के?", bn="সকালের না রাতের মানুষ?",
            ja="朝型？夜型？", ko="아침형인가요, 저녁형인가요?",
            ar="هل أنت صباحي أم ليلي؟", sw="Wewe ni wa asubuhi au usiku?",
            ha="Kana na safe ne ko dare?", am="የጠዋት ሰው ነህ ወይስ የሌሊት?",
            tl="Pang-umaga ka ba o panggabi?", ms="Adakah anda orang pagi atau malam?",
            mi="He tangata ata, he tangata pō rānei koe?",
        ),
    },
    {
        "value": "suggestions.learningPreferences",
        "order": 33,
        "translations": L(
            es="¿Cómo prefieres aprender?", en="How do you prefer to learn?",
            pt="Como você prefere aprender?", fr="Comment préfères-tu apprendre ?",
            de="Wie lernst du am liebsten?", it="Come preferisci imparare?",
            ru="Как вы предпочитаете учиться?", sv="Hur föredrar du att lära dig?",
            nl="Hoe leer je het liefst?", zh="你更喜欢怎样学习？",
            hi="सीखना कैसे पसंद है?", bn="কীভাবে শিখতে পছন্দ করেন?",
            ja="どんな学び方が好き？", ko="어떻게 배우는 것을 선호하나요?",
            ar="كيف تفضل التعلم؟", sw="Unapendelea kujifunza vipi?",
            ha="Yaya kafi son koyo?", am="እንዴት መማር ትመርጣለህ?",
            tl="Paano mo gustong matuto?", ms="Bagaimana anda lebih suka belajar?",
            mi="Me pēhea koe e pai ai ki te ako?",
        ),
    },
]

# Typo guard for accidental non-keyword arguments
for _item in TEXTS:
    assert set(_item["translations"]) == set(LANGS), _item["value"]

_VALUES = [item["value"] for item in TEXTS]
assert len(_VALUES) == len(set(_VALUES)), "duplicate seed values"
assert len(TEXTS) == 34, f"expected 34 texts, got {len(TEXTS)}"


async def main() -> None:
    await init_db()
    created = 0
    updated = 0
    for item in TEXTS:
        value = item["value"]
        order = item["order"]
        translations = item["translations"]

        existing = await SystemOption.find_one(
            SystemOption.category == "profile_progress_section",
            SystemOption.value == value,
        )

        doc_data = {
            "category": "profile_progress_section",
            "value": value,
            "label": translations["es"],
            "order": order,
            "is_active": True,
        }
        for lang in LANGS:
            doc_data[f"label_{lang}"] = translations.get(lang, "")

        if existing:
            for key, val in doc_data.items():
                setattr(existing, key, val)
            await existing.save()
            updated += 1
        else:
            await SystemOption(**doc_data).insert()
            created += 1

    print(
        f"seed_profile_progress_section: created {created}, "
        f"updated {updated}, total {len(TEXTS)}"
    )


if __name__ == "__main__":
    asyncio.run(main())
