"""
Seed microtest texts under profile.personality.microtest.* (Social Style test).

Keys: title, q1-q5 text + opts, cancel/prev/next/finish,
done.title/subtitle/expl/review/apply, result.extrovert/introvert/ambivert.

Idempotent: upserts. Run:
    docker exec -w /app redthread-backend python seed/seed_profile_microtest_section.py
"""

import asyncio
import os
import sys

sys.path.append(os.getcwd())

from src.core.database import init_db
from src.models.system_options import SystemOption

LANGS = [
    "es", "en", "pt", "fr", "de", "it", "ru", "sv", "nl", "zh",
    "hi", "bn", "ja", "ko", "ar", "sw", "ha", "am", "tl", "ms", "mi",
]


def L(**kw) -> dict:
    missing = [lang for lang in LANGS if lang not in kw]
    if missing:
        raise ValueError(f"missing languages: {missing}")
    unknown = [key for key in kw if key not in LANGS]
    if unknown:
        raise ValueError(f"unknown languages: {unknown}")
    return kw


TEXTS = [
    {
        "value": "microtest.title",
        "order": 100,
        "translations": L(
            es="Microtest: Estilo Social", en="Microtest: Social Style",
            pt="Microteste: Estilo Social", fr="Micro-test : Style social",
            de="Mikrotest: Sozialstil", it="Microtest: Stile sociale",
            ru="Микротест: Социальный стиль", sv="Mikrotest: Social stil",
            nl="Microtest: Sociale stijl", zh="微测试：社交风格",
            hi="माइक्रोटेस्ट: सामाजिक शैली", bn="মাইক্রোটেস্ট: সামাজিক ধরন",
            ja="マイクロテスト：ソーシャルスタイル", ko="마이크로테스트: 소셜 스타일",
            ar="اختبار مصغر: النمط الاجتماعي", sw="Kipimo kifupi: Mtindo wa kijamii",
            ha="Ƙaramin gwaji: Salon zamantakewa", am="ማይክሮቴስት: ማህበራዊ ዘይቤ",
            tl="Microtest: Estilong Panlipunan", ms="Ujian mikro: Gaya sosial",
            mi="Whakamātautau iti: Kāhua pāpori",
        ),
    },
    {
        "value": "microtest.q1.text",
        "order": 101,
        "translations": L(
            es="¿Cómo recargas energía después de un día largo?",
            en="How do you recharge after a long day?",
            pt="Como você recarrega energia após um dia longo?",
            fr="Comment recharges-tu ton énergie après une longue journée ?",
            de="Wie tankst du nach einem langen Tag Energie?",
            it="Come ricarichi energia dopo una lunga giornata?",
            ru="Как вы восстанавливаете силы после долгого дня?",
            sv="Hur laddar du om efter en lång dag?",
            nl="Hoe laad je op na een lange dag?",
            zh="漫长的一天后你如何恢复精力？",
            hi="लंबे दिन के बाद आप ऊर्जा कैसे पुनः प्राप्त करते हैं?",
            bn="দীর্ঘ দিনের পর আপনি কীভাবে শক্তি পুনরায় অর্জন করেন?",
            ja="長い一日の後、どうやってエネルギーを回復しますか？",
            ko="긴 하루 후 어떻게 에너지를 충전하나요?",
            ar="كيف تعيد شحن طاقتك بعد يوم طويل؟",
            sw="Unajaza nishati vipi baada ya siku ndefu?",
            ha="Yaya kake cika kuzari bayan doguwar rana?",
            am="ከረጅም ቀን በኋላ ኃይልህን እንዴት ትሞላለህ?",
            tl="Paano ka nagre-recharge pagkatapos ng mahabang araw?",
            ms="Bagaimana anda mengecas semula tenaga selepas hari yang panjang?",
            mi="Me pēhea koe e whakakī ai i tō pūngao whai muri i te rā roa?",
        ),
    },
    {
        "value": "microtest.q1.opt.extrovert",
        "order": 102,
        "translations": L(
            es="Estando con amigos o en una reunión.",
            en="Being with friends or at a gathering.",
            pt="Estando com amigos ou em uma reunião.",
            fr="En étant avec des amis ou à une réunion.",
            de="Mit Freunden oder auf einem Treffen.",
            it="Stando con amici o a una riunione.",
            ru="Находясь с друзьями или на встрече.",
            sv="Med vänner eller på en träff.",
            nl="Met vrienden of op een bijeenkomst.",
            zh="和朋友在一起或参加聚会。",
            hi="दोस्तों के साथ या किसी सभा में।",
            bn="বন্ধুদের সাথে বা কোনো সমাবেশে।",
            ja="友達といるか集まりに参加して。",
            ko="친구들과 함께 있거나 모임에서.",
            ar="بالتواجد مع الأصدقاء أو في تجمع.",
            sw="Nikiwa na marafiki au kwenye mkusanyiko.",
            ha="Tare da abokai ko a taro.",
            am="ከጓደኞች ጋር በመሆን ወይም በስብሰባ ላይ።",
            tl="Kasama ang mga kaibigan o sa isang pagtitipon.",
            ms="Bersama rakan atau di perhimpunan.",
            mi="Me ngā hoa, i te huihuinga rānei.",
        ),
    },
    {
        "value": "microtest.q1.opt.introvert",
        "order": 103,
        "translations": L(
            es="En casa, solo/a, leyendo o descansando.",
            en="At home, alone, reading or resting.",
            pt="Em casa, sozinho/a, lendo ou descansando.",
            fr="À la maison, seul/e, en lisant ou en me reposant.",
            de="Zuhause, allein, lesend oder ausruhend.",
            it="A casa, da solo/a, leggendo o riposando.",
            ru="Дома, в одиночестве, читая или отдыхая.",
            sv="Hemma, ensam, läsande eller vilande.",
            nl="Thuis, alleen, lezend of rustend.",
            zh="在家，独自一人，看书或休息。",
            hi="घर पर, अकेले, पढ़ते या आराम करते हुए।",
            bn="বাড়িতে, একা, পড়ে বা বিশ্রাম নিয়ে।",
            ja="家で一人で読書や休息をして。",
            ko="집에서 혼자 책을 읽거나 쉬면서.",
            ar="في المنزل، وحيدًا، أقرأ أو أستريح.",
            sw="Nyumbani, peke yangu, nikisoma au kupumzika.",
            ha="A gida, ni kaɗai, ina karatu ko hutu.",
            am="በቤት፣ ብቻዬን፣ በማንበብ ወይም በእረፍት።",
            tl="Sa bahay, mag-isa, nagbabasa o nagpapahinga.",
            ms="Di rumah, bersendirian, membaca atau berehat.",
            mi="Ki te kāinga, ko au anake, e pānui ana, e okioki ana rānei.",
        ),
    },
    {
        "value": "microtest.q1.opt.ambivert",
        "order": 104,
        "translations": L(
            es="Depende del día, a veces social, a veces tranquilo.",
            en="Depends on the day, sometimes social, sometimes quiet.",
            pt="Depende do dia, às vezes social, às vezes tranquilo.",
            fr="Ça dépend du jour, parfois social, parfois tranquille.",
            de="Kommt auf den Tag an, mal gesellig, mal ruhig.",
            it="Dipende dal giorno, a volte socievole, a volte tranquillo.",
            ru="Зависит от дня: иногда общительный, иногда спокойный.",
            sv="Beror på dagen, ibland social, ibland lugn.",
            nl="Hangt van de dag af, soms sociaal, soms rustig.",
            zh="看当天情况，有时社交，有时安静。",
            hi="दिन पर निर्भर, कभी सामाजिक, कभी शांत।",
            bn="দিনের উপর নির্ভর করে, কখনও সামাজিক, কখনও শান্ত।",
            ja="日による、社交的な時もあれば静かな時も。",
            ko="날에 따라 다름, 사교적일 때도 조용할 때도.",
            ar="حسب اليوم، أحيانًا اجتماعي وأحيانًا هادئ.",
            sw="Inategemea siku, wakati mwingine kijamii, wakati mwingine kimya.",
            ha="Ya danganta da rana, wani lokaci zamantakewa, wani lokaci natsuwa.",
            am="በቀኑ ይወሰናል፣ አንዳንድ ጊዜ ማህበራዊ አንዳንድ ጊዜ 조용።",
            tl="Depende sa araw, minsan sosyal, minsan tahimik.",
            ms="Bergantung pada hari, kadang-kadang sosial, kadang-kadang pendiam.",
            mi="Kei te rā te tikanga, i ētahi wā pāpori, i ētahi wā mārie.",
        ),
    },
    {
        "value": "microtest.q2.text",
        "order": 105,
        "translations": L(
            es="En una fiesta donde no conoces a nadie, tú…",
            en="At a party where you know no one, you…",
            pt="Em uma festa onde você não conhece ninguém, você…",
            fr="À une fête où tu ne connais personne, tu…",
            de="Auf einer Party, wo du niemanden kennst, du…",
            it="A una festa dove non conosci nessuno, tu…",
            ru="На вечеринке, где вы никого не знаете, вы…",
            sv="På en fest där du inte känner någon, du…",
            nl="Op een feestje waar je niemand kent, jij…",
            zh="在一个谁都不认识的派对上，你会…",
            hi="किसी पार्टी में जहाँ आप किसी को नहीं जानते, आप…",
            bn="যে পার্টিতে আপনি কাউকে চেনেন না, আপনি…",
            ja="誰も知らないパーティーでは、あなたは…",
            ko="아무도 모르는 파티에서 당신은…",
            ar="في حفلة لا تعرف فيها أحدًا، أنت…",
            sw="Kwenye sherehe usiyomjua mtu, wewe…",
            ha="A biki inda ba ka san kowa ba, kai…",
            am="እ Personም የማታውቅበት ድግስ ላይ አንተ…",
            tl="Sa party na wala kang kilala, ikaw…",
            ms="Di parti yang anda tidak kenal sesiapa, anda…",
            mi="I te pāti kāore koe e mōhio ki tētahi, koe…",
        ),
    },
    {
        "value": "microtest.q2.opt.extrovert",
        "order": 106,
        "translations": L(
            es="Te acercas a hablar con varias personas.",
            en="You approach several people to talk.",
            pt="Você se aproxima para falar com várias pessoas.",
            fr="Tu vas parler à plusieurs personnes.",
            de="Du sprichst mehrere Leute an.",
            it="Ti avvicini a parlare con varie persone.",
            ru="Вы подходите поговорить с разными людьми.",
            sv="Du går fram och pratar med flera personer.",
            nl="Je stapt op verschillende mensen af.",
            zh="你会主动和好几个人攀谈。",
            hi="आप कई लोगों से बात करने जाते हैं।",
            bn="আপনি বিভিন্ন মানুষের সাথে কথা বলতে এগিয়ে যান।",
            ja="いろんな人に話しかけに行く。",
            ko="여러 사람에게 다가가 말을 건다.",
            ar="تقترب للتحدث مع عدة أشخاص.",
            sw="Unawakaribia watu kadhaa kuzungumza.",
            ha="Kana kusantar mutane da yawa don magana.",
            am="ከብዙ ሰዎች ጋር ለመነጋገር ትቀርባለህ።",
            tl="Lumalapit ka upang makipag-usap sa ilan.",
            ms="Anda mendekati beberapa orang untuk berbual.",
            mi="Ka whakatata koe ki ētahi tāngata ki te kōrero.",
        ),
    },
    {
        "value": "microtest.q2.opt.introvert",
        "order": 107,
        "translations": L(
            es="Observas, te quedas en tu rincón o con alguien conocido.",
            en="You observe, stay in your corner or with someone known.",
            pt="Você observa, fica no seu canto ou com alguém conhecido.",
            fr="Tu observes, restes dans ton coin ou avec quelqu'un de connu.",
            de="Du beobachtest, bleibst in deiner Ecke oder bei Bekannten.",
            it="Osservi, resti nel tuo angolo o con qualcuno che conosci.",
            ru="Вы наблюдаете, держитесь в стороне или с кем-то знакомым.",
            sv="Du observerar, håller dig i ditt hörn eller med någon bekant.",
            nl="Je observeert, blijft in je hoekje of bij een bekende.",
            zh="你观察，待在角落或和认识的人在一起。",
            hi="आप देखते हैं, अपने कोने में या किसी जाने-पहचाने के साथ रहते हैं।",
            bn="আপনি পর্যবেক্ষণ করেন, নিজের কোণে বা পরিচিত কারো সাথে থাকেন।",
            ja="様子を見て、隅にいるか知人といる。",
            ko="지켜보다가 구석에 있거나 아는 사람과 함께 있다.",
            ar="تراقب وتبقى في زاويتك أو مع شخص تعرفه.",
            sw="Unatazama, unakaa pembeni au na unayemjua.",
            ha="Kana lura, kana zama a kusurwarka ko tare da wanda ka sani.",
            am="ትመለከታለህ፣ በማዕዘንህ ትቆያለህ ወይም ከምታውቀው ሰው ጋር።",
            tl="Nagmamasid ka, nananatili sa sulok o kasama ang kilala.",
            ms="Anda memerhati, kekal di sudut atau bersama kenalan.",
            mi="Ka mātakitaki koe, ka noho ki tō kokonga, ki te tangata e mōhio ana rānei.",
        ),
    },
    {
        "value": "microtest.q2.opt.ambivert",
        "order": 108,
        "translations": L(
            es="Te adaptas según el ambiente y tu estado de ánimo.",
            en="You adapt to the vibe and your mood.",
            pt="Você se adapta ao clima e ao seu humor.",
            fr="Tu t'adaptes à l'ambiance et à ton humeur.",
            de="Du passt dich an Stimmung und Laune an.",
            it="Ti adatti all'atmosfera e al tuo umore.",
            ru="Вы подстраиваетесь под атмосферу и настроение.",
            sv="Du anpassar dig efter stämningen och humöret.",
            nl="Je past je aan aan sfeer en stemming.",
            zh="你会根据气氛和心情调整自己。",
            hi="माहौल और मूड के अनुसार ढल जाते हैं।",
            bn="পরিবেশ ও মেজাজ অনুযায়ী মানিয়ে নেন।",
            ja="場の雰囲気や気分に合わせる。",
            ko="분위기와 기분에 따라 적응한다.",
            ar="تتكيف حسب الأجواء ومزاجك.",
            sw="Unajirekebisha kulingana na hali na hisia.",
            ha="Kana daidaita bisa ga yanayi da yanayin zuciyarka.",
            am="ከከባቢው እና ከስሜትህ ጋር ትላመዳለህ።",
            tl="Umaangkop ka ayon sa氛围 at mood.",
            ms="Anda menyesuaikan diri mengikut suasana dan mood.",
            mi="Ka urutau koe ki te āhuatanga me tō wairua.",
        ),
    },
    {
        "value": "microtest.q3.text",
        "order": 109,
        "translations": L(
            es="¿Qué te resulta más agotador?",
            en="What drains you most?",
            pt="O que mais te esgota?",
            fr="Qu'est-ce qui t'épuise le plus ?",
            de="Was erschöpft dich am meisten?",
            it="Cosa ti stanca di più?",
            ru="Что вас больше утомляет?",
            sv="Vad tröttar ut dig mest?",
            nl="Wat put je het meest uit?",
            zh="什么最让你感到疲惫？",
            hi="आपको सबसे ज़्यादा क्या थकाता है?",
            bn="কী আপনাকে সবচেয়ে বেশি ক্লান্ত করে?",
            ja="一番疲れるのは？",
            ko="가장 지치게 하는 것은?",
            ar="ما الذي يرهقك أكثر؟",
            sw="Nini kinakuchosha zaidi?",
            ha="Me ne yafi gajiyar da kai?",
            am="ምን ነው በጣም የሚያደክምህ?",
            tl="Ano ang pinakanakakapagod sa iyo?",
            ms="Apa yang paling memenatkan anda?",
            mi="He aha te mea e tino whakapau ai i a koe?",
        ),
    },
    {
        "value": "microtest.q3.opt.extrovert",
        "order": 110,
        "translations": L(
            es="Estar solo mucho tiempo.", en="Being alone a long time.",
            pt="Ficar sozinho muito tempo.", fr="Rester seul longtemps.",
            de="Lange allein sein.", it="Restare solo a lungo.",
            ru="Долго быть в одиночестве.", sv="Vara ensam länge.",
            nl="Lang alleen zijn.", zh="长时间独处。",
            hi="लंबे समय तक अकेले रहना।", bn="দীর্ঘক্ষণ একা থাকা।",
            ja="長時間一人でいること。", ko="오랫동안 혼자 있기.",
            ar="البقاء وحيدًا طويلًا.", sw="Kukaa peke yako muda mrefu.",
            ha="Zama ni kaɗai na dogon lokaci.", am="ለረጅም ጊዜ ብቻ መሆን።",
            tl="Mag-isa nang matagal.", ms="Bersendirian lama.",
            mi="Te noho takitahi mō te wā roa.",
        ),
    },
    {
        "value": "microtest.q3.opt.introvert",
        "order": 111,
        "translations": L(
            es="Estar rodeado de gente por horas.", en="Being around people for hours.",
            pt="Ficar rodeado de gente por horas.", fr="Être entouré pendant des heures.",
            de="Stundenlang unter Leuten sein.", it="Stare tra la gente per ore.",
            ru="Часами находиться среди людей.", sv="Vara omgiven av folk i timmar.",
            nl="Urenlang omringd zijn door mensen.", zh="和人待在一起好几个小时。",
            hi="घंटों लोगों से घिरे रहना।", bn="ঘণ্টার পর ঘণ্টা মানুষের মধ্যে থাকা।",
            ja="何時間も人に囲まれていること。", ko="수 시간 동안 사람들에 둘러싸여 있기.",
            ar="التواجد حول الناس لساعات.", sw="Kuzungukwa na watu kwa masaa.",
            ha="Zama da mutane na sa'o'i.", am="ለሰዓታት በሰዎች መከበብ።",
            tl="Mapalibutan ng tao nang maraming oras.", ms="Dikelilingi orang berjam-jam.",
            mi="Te karapotia e te tangata mō ngā hāora.",
        ),
    },
    {
        "value": "microtest.q3.opt.ambivert",
        "order": 112,
        "translations": L(
            es="Ambos, depende del contexto.", en="Both, depends on context.",
            pt="Ambos, depende do contexto.", fr="Les deux, selon le contexte.",
            de="Beides, je nach Kontext.", it="Entrambi, dipende dal contesto.",
            ru="И то, и другое, зависит от контекста.", sv="Båda, beror på sammanhang.",
            nl="Beide, hangt van context af.", zh="两者都是，看情况。",
            hi="दोनों, संदर्भ पर निर्भर।", bn="দুটোই, প্রসঙ্গের উপর নির্ভর।",
            ja="どちらも、状況による。", ko="둘 다, 상황에 따라 다름.",
            ar="كلاهما، حسب السياق.", sw="Vyote, inategemea muktadha.",
            ha="Dukansu, ya danganta da yanayi.", am="ሁለቱም፣ በአውድ ይወሰናል።",
            tl="Pareho, depende sa konteksto.", ms="Kedua-duanya, bergantung konteks.",
            mi="E rua, kei te horopaki te tikanga.",
        ),
    },
    {
        "value": "microtest.q4.text",
        "order": 113,
        "translations": L(
            es="¿Cómo prefieres trabajar o estudiar?",
            en="How do you prefer to work or study?",
            pt="Como você prefere trabalhar ou estudar?",
            fr="Comment préfères-tu travailler ou étudier ?",
            de="Wie arbeitest oder lernst du am liebsten?",
            it="Come preferisci lavorare o studiare?",
            ru="Как вы предпочитаете работать или учиться?",
            sv="Hur föredrar du att arbeta eller studera?",
            nl="Hoe werk of studeer je het liefst?",
            zh="你更喜欢怎样工作或学习？",
            hi="आप काम या पढ़ाई कैसे करना पसंद करते हैं?",
            bn="আপনি কীভাবে কাজ বা পড়াশোনা করতে পছন্দ করেন?",
            ja="どのように働いたり勉強したりするのが好き？",
            ko="일하거나 공부할 때 어떤 방식을 선호하나요?",
            ar="كيف تفضل العمل أو الدراسة؟",
            sw="Unapendelea kufanya kazi au kusoma vipi?",
            ha="Yaya kafi son yin aiki ko karatu?",
            am="እንዴት መሥራት ወይም መማር ትመርጣለህ?",
            tl="Paano mo gustong magtrabaho o mag-aral?",
            ms="Bagaimana anda lebih suka bekerja atau belajar?",
            mi="Me pēhea koe e pai ai ki te mahi, ki te ako rānei?",
        ),
    },
    {
        "value": "microtest.q4.opt.extrovert",
        "order": 114,
        "translations": L(
            es="En equipo, compartiendo ideas.", en="In a team, sharing ideas.",
            pt="Em equipe, compartilhando ideias.", fr="En équipe, en partageant des idées.",
            de="Im Team, Ideen teilen.", it="In squadra, condividendo idee.",
            ru="В команде, делясь идеями.", sv="I team, dela idéer.",
            nl="In teamverband, ideeën delend.", zh="团队合作，分享想法。",
            hi="टीम में, विचार साझा करते हुए।", bn="দলে, ধারণা ভাগ করে।",
            ja="チームでアイデアを共有しながら。", ko="팀으로 아이디어를 나누면서.",
            ar="ضمن فريق، بمشاركة الأفكار.", sw="Kikundi, tukishiriki mawazo.",
            ha="A rukuni, ana raba ra'ayoyi.", am="በቡድን፣ ሀሳቦችን እየተጋራህ።",
            tl="Sa team, nagbabahagi ng ideya.", ms="Berkumpulan, berkongsi idea.",
            mi="Ā-rōpū, me te tiri whakaaro.",
        ),
    },
    {
        "value": "microtest.q4.opt.introvert",
        "order": 115,
        "translations": L(
            es="En silencio, concentrado/a en solitario.", en="In silence, focused alone.",
            pt="Em silêncio, focado/a sozinho/a.", fr="En silence, concentré/e seul/e.",
            de="In Stille, allein konzentriert.", it="In silenzio, concentrato/a da solo/a.",
            ru="В тишине, сосредоточенно в одиночку.", sv="I tystnad, fokuserad ensam.",
            nl="In stilte, alleen geconcentreerd.", zh="安静地独自专注。",
            hi="शांति में, अकेले केंद्रित।", bn="নীরবে, একা মনোযোগ দিয়ে।",
            ja="静かに一人で集中して。", ko="조용히 혼자 집중해서.",
            ar="بصمت، مركزًا بمفردك.", sw="Kimya, makini peke yako.",
            ha="A shiru, mai da hankali ni kaɗai.", am="በዝምታ፣ ብቻህን ተከትህለህ።",
            tl="Tahimik, nakatutok nang mag-isa.", ms="Senyap, fokus bersendirian.",
            mi="Mārie, arotahi ko au anake.",
        ),
    },
    {
        "value": "microtest.q4.opt.ambivert",
        "order": 116,
        "translations": L(
            es="Alterno entre ambos según el proyecto.", en="I switch depending on the project.",
            pt="Alterno entre ambos conforme o projeto.", fr="J'alterne selon le projet.",
            de="Ich wechsle je nach Projekt.", it="Alterno a seconda del progetto.",
            ru="Чередую в зависимости от проекта.", sv="Växlar beroende på projekt.",
            nl="Wissel af per project.", zh="根据项目在两者间切换。",
            hi="प्रोजेक्ट के अनुसार बदलता/बदलती हूँ।", bn="প্রকল্প অনুযায়ী বদলাই।",
            ja="プロジェクトによって使い分ける。", ko="프로젝트에 따라 바꾼다.",
            ar="أبدّل حسب المشروع.", sw="Nabadilisha kulingana na mradi.",
            ha="Ina canzawa bisa ga aikin.", am="በፕሮጀክቱ እቀያይራለሁ።",
            tl="Nagpapalit depende sa proyekto.", ms="Bertukar mengikut projek.",
            mi="Ka whakawhiti au kei te kaupapa te tikanga.",
        ),
    },
    {
        "value": "microtest.q5.text",
        "order": 117,
        "translations": L(
            es="¿Qué te describe mejor?", en="What describes you best?",
            pt="O que melhor te descreve?", fr="Qu'est-ce qui te décrit le mieux ?",
            de="Was beschreibt dich am besten?", it="Cosa ti descrive meglio?",
            ru="Что описывает вас лучше?", sv="Vad beskriver dig bäst?",
            nl="Wat beschrijft je het best?", zh="哪项最符合你？",
            hi="आपका सबसे अच्छा वर्णन क्या है?", bn="কোনটি আপনাকে সবচেয়ে ভালো বর্ণনা করে?",
            ja="あなたを最も表すのは？", ko="당신을 가장 잘 설명하는 것은?",
            ar="ما الذي يصفك أفضل؟", sw="Nini kinakuelezea vizuri?",
            ha="Me ne yafi bayyana kai?", am="ምን ነው በተሻለ የሚገልጽህ?",
            tl="Ano ang pinakamaglalarawan sa iyo?", ms="Apa yang paling menggambarkan anda?",
            mi="He aha te mea e tino whakaahua ana i a koe?",
        ),
    },
    {
        "value": "microtest.q5.opt.extrovert",
        "order": 118,
        "translations": L(
            es="Me encanta hablar y compartir.", en="I love talking and sharing.",
            pt="Adoro falar e compartilhar.", fr="J'adore parler et partager.",
            de="Ich rede und teile gern.", it="Adoro parlare e condividere.",
            ru="Обожаю говорить и делиться.", sv="Jag älskar att prata och dela.",
            nl="Ik praat en deel graag.", zh="我超爱说话和分享。",
            hi="मुझे बात करना और साझा करना पसंद है।", bn="আমি কথা বলতে ও ভাগ করতে ভালোবাসি।",
            ja="話したり共有したりするのが大好き。", ko="말하고 나누는 것을 좋아함.",
            ar="أحب التحدث والمشاركة.", sw="Ninapenda kuzungumza na kushiriki.",
            ha="Ina son magana da raba.", am="መነጋገር እና መጋራት እወዳለሁ።",
            tl="Mahilig akong magsalita at magbahagi.", ms="Saya suka bercakap dan berkongsi.",
            mi="He pai ki ahau te kōrero me te tiri.",
        ),
    },
    {
        "value": "microtest.q5.opt.introvert",
        "order": 119,
        "translations": L(
            es="Prefiero escuchar y reflexionar.", en="I prefer listening and reflecting.",
            pt="Prefiro ouvir e refletir.", fr="Je préfère écouter et réfléchir.",
            de="Ich höre lieber zu und denke nach.", it="Preferisco ascoltare e riflettere.",
            ru="Предпочитаю слушать и размышлять.", sv="Jag föredrar att lyssna och reflektera.",
            nl="Ik luister en reflecteer liever.", zh="我更喜欢倾听和思考。",
            hi="सुनना और सोचना पसंद है।", bn="শোনা ও চিন্তা করা পছন্দ করি।",
            ja="聞いたり考えたりする方が好き。", ko="듣고 성찰하는 것을 선호함.",
            ar="أفضل الاستماع والتأمل.", sw="Ninapendelea kusikiliza na kutafakari.",
            ha="Na fi sauraro da tunani.", am="ማዳመጥ እና ማሰላሰል እመርጣለሁ።",
            tl="Mas gusto kong makinig at magnilay.", ms="Saya lebih suka mendengar dan merenung.",
            mi="He pai ake ki ahau te whakarongo me te huritao.",
        ),
    },
    {
        "value": "microtest.q5.opt.ambivert",
        "order": 120,
        "translations": L(
            es="Hago ambas cosas según la situación.", en="I do both depending on the situation.",
            pt="Faço ambas conforme a situação.", fr="Je fais les deux selon la situation.",
            de="Beides, je nach Situation.", it="Faccio entrambe le cose a seconda della situazione.",
            ru="Делаю и то, и другое по ситуации.", sv="Gör båda beroende på situation.",
            nl="Doe beide, afhankelijk van de situatie.", zh="看情况，两者都做。",
            hi="स्थिति के अनुसार दोनों करता/करती हूँ।", bn="পরিস্থিতি অনুযায়ী দুটোই করি।",
            ja="状況によって両方する。", ko="상황에 따라 둘 다 함.",
            ar="أفعل كليهما حسب الموقف.", sw="Nafanya vyote kulingana na hali.",
            ha="Ina yin duka biyun bisa ga yanayi.", am="ሁለቱንም እንደ ሁኔታው አደርጋለሁ።",
            tl="Ginagawa ko ang pareho depende sa sitwasyon.", ms="Saya buat kedua-duanya mengikut keadaan.",
            mi="Ka mahi au i ngā mea e rua kei te āhuatanga te tikanga.",
        ),
    },
    {
        "value": "microtest.cancel",
        "order": 121,
        "translations": L(
            es="Cancelar", en="Cancel",
            pt="Cancelar", fr="Annuler",
            de="Abbrechen", it="Annulla",
            ru="Отмена", sv="Avbryt",
            nl="Annuleren", zh="取消",
            hi="रद्द करें", bn="বাতিল",
            ja="キャンセル", ko="취소",
            ar="إلغاء", sw="Ghairi",
            ha="Soke", am="ሰርዝ",
            tl="Kanselahin", ms="Batal",
            mi="Whakakore",
        ),
    },
    {
        "value": "microtest.prev",
        "order": 122,
        "translations": L(
            es="Anterior", en="Back",
            pt="Anterior", fr="Précédent",
            de="Zurück", it="Indietro",
            ru="Назад", sv="Tillbaka",
            nl="Vorige", zh="上一步",
            hi="पीछे", bn="পেছনে",
            ja="戻る", ko="이전",
            ar="رجوع", sw="Nyuma",
            ha="Baya", am="ተመለስ",
            tl="Bumalik", ms="Kembali",
            mi="Hoki",
        ),
    },
    {
        "value": "microtest.next",
        "order": 123,
        "translations": L(
            es="Siguiente", en="Next",
            pt="Próximo", fr="Suivant",
            de="Weiter", it="Avanti",
            ru="Далее", sv="Nästa",
            nl="Volgende", zh="下一步",
            hi="आगे", bn="পরবর্তী",
            ja="次へ", ko="다음",
            ar="التالي", sw="Endelea",
            ha="Na gaba", am="ቀጣይ",
            tl="Susunod", ms="Seterusnya",
            mi="Panuku",
        ),
    },
    {
        "value": "microtest.finish",
        "order": 124,
        "translations": L(
            es="Finalizar", en="Finish",
            pt="Finalizar", fr="Terminer",
            de="Abschließen", it="Fine",
            ru="Завершить", sv="Slutför",
            nl="Afronden", zh="完成",
            hi="समाप्त", bn="শেষ",
            ja="完了", ko="완료",
            ar="إنهاء", sw="Maliza",
            ha="Gama", am="ጨርስ",
            tl="Tapusin", ms="Selesai",
            mi="Whakaoti",
        ),
    },
    {
        "value": "microtest.done.title",
        "order": 125,
        "translations": L(
            es="¡Test completado!", en="Test complete!",
            pt="Teste concluído!", fr="Test terminé !",
            de="Test abgeschlossen!", it="Test completato!",
            ru="Тест завершён!", sv="Testet klart!",
            nl="Test voltooid!", zh="测试完成！",
            hi="टेस्ट पूरा!", bn="টেস্ট সম্পন্ন!",
            ja="テスト完了！", ko="테스트 완료!",
            ar="اكتمل الاختبار!", sw="Kipimo kimekamilika!",
            ha="An gama gwaji!", am="ሙከራ ተጠናቋል!",
            tl="Tapos na ang test!", ms="Ujian selesai!",
            mi="Kua oti te whakamātautau!",
        ),
    },
    {
        "value": "microtest.done.subtitle",
        "order": 126,
        "translations": L(
            es="Tu estilo social parece ser:", en="Your social style seems to be:",
            pt="Seu estilo social parece ser:", fr="Ton style social semble être :",
            de="Dein Sozialstil scheint zu sein:", it="Il tuo stile sociale sembra essere:",
            ru="Ваш социальный стиль, похоже:", sv="Din sociala stil verkar vara:",
            nl="Je sociale stijl lijkt te zijn:", zh="你的社交风格似乎是：",
            hi="आपकी सामाजिक शैली लगती है:", bn="আপনার সামাজিক ধরন মনে হয়:",
            ja="あなたのソーシャルスタイルは：", ko="당신의 소셜 스타일은:",
            ar="يبدو أن نمطك الاجتماعي هو:", sw="Mtindo wako wa kijamii unaonekana kuwa:",
            ha="Salon zamantakewarka kamar shine:", am="ማህበራዊ ዘይቤህ ይመስላል፦",
            tl="Ang iyong istilong panlipunan ay tila:", ms="Gaya sosial anda nampaknya:",
            mi="Ko tō kāhua pāpori, te āhua nei:",
        ),
    },
    {
        "value": "microtest.done.expl",
        "order": 127,
        "translations": L(
            es="Basado en tus respuestas, este es el estilo que mejor encaja contigo. Puedes aplicarlo ahora o cambiarlo manualmente después.",
            en="Based on your answers, this style fits you best. Apply now or change manually later.",
            pt="Com base nas respostas, este estilo combina mais com você. Aplique agora ou mude depois.",
            fr="Selon tes réponses, ce style te correspond le mieux. Applique-le ou change-le plus tard.",
            de="Basierend auf deinen Antworten passt dieser Stil am besten. Jetzt anwenden oder später ändern.",
            it="In base alle risposte, questo stile fa per te. Applicalo ora o cambialo dopo.",
            ru="Судя по ответам, этот стиль вам подходит лучше. Примените сейчас или измените позже.",
            sv="Baserat på dina svar passar denna stil dig bäst. Använd nu eller ändra senare.",
            nl="Op basis van je antwoorden past deze stijl het best. Pas toe of wijzig later.",
            zh="根据你的回答，这种风格最适合你。现在应用或稍后手动更改。",
            hi="आपके उत्तरों के आधार पर यह शैली सबसे उपयुक्त है। अभी लागू करें या बाद में बदलें।",
            bn="আপনার উত্তরের ভিত্তিতে এই ধরনটি সবচেয়ে মানানসই। এখন প্রয়োগ করুন বা পরে বদলান।",
            ja="回答から、このスタイルがあなたに最も合っています。今適用するか後で変更できます。",
            ko="답변 기준으로 이 스타일이 가장 잘 맞습니다. 지금 적용하거나 나중에 변경하세요.",
            ar="بناءً على إجاباتك، هذا النمط يناسبك أكثر. طبّقه الآن أو غيّره لاحقًا.",
            sw="Kulingana na majibu yako, mtindo huu unakufaa zaidi. Tumia sasa au badilisha baadaye.",
            ha="Bisa ga amsoshinka, wannan salon yafi dacewa da kai. Aiwatar yanzu ko canza daga baya.",
            am="በመልሶችህ መሠረት ይህ ዘይቤ ለአንተ በተሻለ ይስማማል። አሁን ተግብር ወይም በኋላ ቀይር።",
            tl="Batay sa mga sagot mo, ang istilong ito ang pinakabagay. I-apply ngayon o baguhin mamaya.",
            ms="Berdasarkan jawapan anda, gaya ini paling sesuai. Terapkan sekarang atau ubah kemudian.",
            mi="I runga i ō whakautu, e tino hāngai ana tēnei kāhua ki a koe. Hoatu ināianei, hurihia rānei ā muri.",
        ),
    },
    {
        "value": "microtest.done.review",
        "order": 128,
        "translations": L(
            es="Revisar respuestas", en="Review answers",
            pt="Revisar respostas", fr="Revoir les réponses",
            de="Antworten prüfen", it="Rivedi risposte",
            ru="Проверить ответы", sv="Granska svar",
            nl="Antwoorden bekijken", zh="查看回答",
            hi="उत्तर देखें", bn="উত্তর দেখুন",
            ja="回答を確認", ko="답변 검토",
            ar="مراجعة الإجابات", sw="Kagua majibu",
            ha="Duba amsoshi", am="መልሶችን ዳግም እይ",
            tl="Suriin ang mga sagot", ms="Semak jawapan",
            mi="Arotake whakautu",
        ),
    },
    {
        "value": "microtest.done.apply",
        "order": 129,
        "translations": L(
            es="Aceptar y aplicar", en="Accept and apply",
            pt="Aceitar e aplicar", fr="Accepter et appliquer",
            de="Annehmen und anwenden", it="Accetta e applica",
            ru="Принять и применить", sv="Acceptera och använd",
            nl="Accepteren en toepassen", zh="接受并应用",
            hi="स्वीकारें और लागू करें", bn="গ্রহণ ও প্রয়োগ করুন",
            ja="承諾して適用", ko="수락하고 적용",
            ar="قبول وتطبيق", sw="Kubali na tumia",
            ha="Karɓa ka aiwatar", am="ተቀበል እና ተግብር",
            tl="Tanggapin at ilapat", ms="Terima dan terapkan",
            mi="Whakaae ka whakamahi",
        ),
    },
    {
        "value": "microtest.result.extrovert",
        "order": 130,
        "translations": L(
            es="Extrovertido", en="Extrovert",
            pt="Extrovertido", fr="Extraverti",
            de="Extrovertiert", it="Estroverso",
            ru="Экстраверт", sv="Extrovert",
            nl="Extravert", zh="外向型",
            hi="बहिर्मुखी", bn="বহির্মুখী",
            ja="外向型", ko="외향형",
            ar="منفتح", sw="Mchangamfu",
            ha="Mai buɗewa", am="ውጫዊ",
            tl="Palakaibigan", ms="Ekstrovert",
            mi="Torohū",
        ),
    },
    {
        "value": "microtest.result.introvert",
        "order": 131,
        "translations": L(
            es="Introvertido", en="Introvert",
            pt="Introvertido", fr="Introverti",
            de="Introvertiert", it="Introverso",
            ru="Интроверт", sv="Introvert",
            nl="Introvert", zh="内向型",
            hi="अंतर्मुखी", bn="অন্তর্মুখী",
            ja="内向型", ko="내향형",
            ar="انطوائي", sw="Mtu wa ndani",
            ha="Mai shiru", am="ገላጭ",
            tl="Tahimik", ms="Introvert",
            mi="Whakama",
        ),
    },
    {
        "value": "microtest.result.ambivert",
        "order": 132,
        "translations": L(
            es="Ambivertido", en="Ambivert",
            pt="Ambivertido", fr="Ambisverti",
            de="Ambivertiert", it="Ambiverso",
            ru="Амбиверт", sv="Ambivert",
            nl="Ambivert", zh="中间型",
            hi="उभयमुखी", bn="উভমুখী",
            ja="両向型", ko="양향형",
            ar="وسطي", sw="Mchanganyiko",
            ha="Tsakani", am="አምቢቨርት",
            tl="Ambivert", ms="Ambivert",
            mi="Takawaenga",
        ),
    },
]

# Typo guard
for _item in TEXTS:
    assert set(_item["translations"]) == set(LANGS), _item["value"]


async def main() -> None:
    await init_db()
    created = 0
    updated = 0
    for item in TEXTS:
        value = item["value"]
        order = item["order"]
        translations = item["translations"]
        existing = await SystemOption.find_one(
            SystemOption.category == "profile_personality_section",
            SystemOption.value == value,
        )
        doc_data = {
            "category": "profile_personality_section",
            "value": value,
            "label": translations["es"],
            "order": order,
            "is_active": True,
        }
        for lang in LANGS:
            doc_data[f"label_{lang}"] = translations.get(lang, "")
        if existing:
            for key, val in doc_data.items():
                setattr(existing, key, val)
            await existing.save()
            updated += 1
        else:
            await SystemOption(**doc_data).insert()
            created += 1
    print(f"seed microtest: created {created}, updated {updated}, total {len(TEXTS)}")


if __name__ == "__main__":
    asyncio.run(main())
