export const supportedLanguages = [
    { code: 'en', label: 'English', sample: 'A E I O U' },
    { code: 'es', label: 'Español', sample: 'A E I O U' },
    { code: 'pt', label: 'Português', sample: 'A Ã E Ê I O Õ U' },
    { code: 'fr', label: 'Français', sample: 'A E I O U Y' },
    { code: 'de', label: 'Deutsch', sample: 'A Ä E I O Ö U Ü' },
    { code: 'it', label: 'Italiano', sample: 'A E I O U' },
    { code: 'ru', label: 'Русский', sample: 'А Е Ё И О У Ы Э Ю Я' },
    { code: 'sv', label: 'Svenska', sample: 'A E I O U Å Ä Ö' },
    { code: 'nl', label: 'Nederlands', sample: 'A E I O U' },
    { code: 'zh', label: '中文 (Mandarín)', sample: 'a o e i u ü' },
    { code: 'hi', label: 'हिन्दी (Hindi)', sample: 'अ आ इ ई उ ऊ ए ऐ ओ औ' },
    { code: 'bn', label: 'বাংলা (Bengali)', sample: 'অ আ ই ঈ উ ঊ এ ঐ ও ঔ' },
    { code: 'ja', label: '日本語 (Japanese)', sample: 'あ い う え お ア イ ウ エ オ' },
    { code: 'ko', label: '한국어 (Korean)', sample: 'ㅏ ㅑ ㅓ ㅕ ㅗ ㅛ ㅜ ㅠ ㅡ ㅣ' },
    { code: 'ar', label: 'العربية (Arabic)', sample: 'ا و ي' },
    { code: 'sw', label: 'Kiswahili (Swahili)', sample: 'A E I O U' },
    { code: 'ha', label: 'Hausa', sample: 'Á À É È Í Ì Ó Ò Ú' },
    { code: 'am', label: 'አማርኛ (Amharic)', sample: 'ሀ ሁ ሂ ሃ ሄ ህ ሆ' },
    { code: 'fil', label: 'Filipino/Tagalog', sample: 'A E I O U' },
];
