apiVersion: v1
kind: ConfigMap
metadata:
  name: redthread-config
data:
  environment: "local"
  redis-host: "localhost"
  redis-port: "6379"
  api-url: "http://localhost:8000"
  cors-origins: "http://localhost:3000,http://localhost:3001"
