"""UI texts for the "Estilo de comunicación" (Communication Style) subsection."""

from .common import text

TEXTS = [
    text(
        "communication.title", 110,
        es="Estilo de comunicación", en="Communication style",
        pt="Estilo de comunicação", fr="Style de communication",
        de="Kommunikationsstil", it="Stile di comunicazione",
        ru="Стиль общения", sv="Kommunikationsstil",
        nl="Communicatiestijl",
        zh="沟通风格", hi="संचार शैली", bn="যোগাযোগের ধরন",
        ja="コミュニケーションスタイル", ko="소통 스타일",
        ar="أسلوب التواصل",
        sw="Mtindo wa mawasiliano", ha="Hanyewar hujayi",
        am="የግንነት አቀራረብ",
        tl="Estilo ng komunikasyon", ms="Gaya komunikasi",
        mi="Mō te tikara whakawhiti",
    ),
    text(
        "communication.question", 111,
        es="¿Cómo prefieres comunicarte con tus conexiones?",
        en="How do you prefer to communicate with your connections?",
        pt="Como você prefere se comunicar com suas conexões?",
        fr="Comment préférez-vous communiquer avec vos connexions ?",
        de="Wie möchten Sie mit Ihren Verbindungen kommunizieren?",
        it="Come preferisci comunicarti con le tue connessioni?",
        ru="Как вы предпочитаете общаться с вашими связями?",
        sv="Hur föredrar du att kommunicera med dina kontakter?",
        nl="Hoe communiceer je het liefst met je connecties?",
        zh="你更喜欢如何与你的联结沟通？",
        hi="आप अपने जुड़ावों से कैसे संवाद करना पसंद करते हैं?",
        bn="আপনি আপনার সংযোগের সাথে কীভাবে কথা বলতে পছন্দ করেন?",
        ja="あなたのつながりとのやりとりはどのようなものが好きですか？",
        ko="당신은 어떤 방식으로 소통하시나요?",
        ar="كيف تفضّل أن تتواصل مع روابطك؟",
        sw="Unapenda kuzungumza na viungo vyako vipi?",
        ha="Kana son hujayi yadda?",
        am="ከግንነቶችህ ጋር እንወስድ አንድ ይፈልጋለህ?",
        tl="Paano mo gustong makipag-usap sa iyong mga koneksyon?",
        ms="Bagaimanakah anda lebih suka berkomunikasi dengan hubungan anda?",
        mi="Me pēhea koe e hiahia ana ki te kōrero ki ō rangi hī?",
    ),
    text(
        "communication.whyTitle", 112,
        es="¿Por qué es necesario definir el estilo de comunicación?",
        en="Why is it necessary to define your communication style?",
        pt="Por que é necessário definir o estilo de comunicação?",
        fr="Pourquoi est-il nécessaire de définir le style de communication ?",
        de="Warum ist es notwendig, den Kommunikationsstil zu definieren?",
        it="Perché è necessario definire lo stile di comunicazione?",
        ru="Почему необходимо определить стиль общения?",
        sv="Varför är det nödvändigt att definiera kommunikationsstilen?",
        nl="Waarom is het nodig je communicatiestijl te bepalen?",
        zh="为什么有必要定义沟通风格？",
        hi="संचार शैली को परिभाषित करना क्यों आवश्यक है?",
        bn="যোগাযোগের ধরন নির্ধারণ করা কেন প্রয়োজন?",
        ja="コミュニケーションスタイルを定義するのはなぜですか？",
        ko="소통 스타일을 정의하는 이유는 무엇인가요?",
        ar="لماذا من الضروري تحديد أسلوب التواصل؟",
        sw="Kwa nini ni lazima kufafanua mtindo wa mawasiliano?",
        ha="Me ya sa ka tantanta salin waya?",
        am="የግንነት አቀራረብን መግለጽ ለምን አስፈላጊ ነው?",
        tl="Bakit kailangang i-define ang iyong estilo ng komunikasyon?",
        ms="Mengapa perlu menentukan gaya komunikasi anda?",
        mi="He aha i tino hiahia koe ki te whakatau i tō tikara whakawhiti?",
    ),
    text(
        "communication.why1", 113,
        es="Evita frustraciones tempranas",
        en="It avoids early frustrations",
        pt="Evita frustrações precoce",
        fr="Évite les frustrations précoces",
        de="Vermeidet frühe Frustrationen",
        it="Evita le frustrazioni precoci",
        ru="Предотвращает ранние разочарования",
        sv="Undviker tidiga besvikelser",
        nl="Voorkomt vroege frustraties",
        zh="避免早期挫败感",
        hi="शुरुआती निराशा से बचाता है",
        bn="প্রাথমিক হতাশা এড়ায়",
        ja="初期のフラストレーションを避ける",
        ko="초기의 좌절감을 피하게 합니다",
        ar="يتجنب الإحباط المبكر",
        sw="Inapunguza frustration za awali",
        ha="Yana kuma ya fushi na fushi",
        am="የቀድሞውን ቅርጠት ያስቀስባል",
        tl="Pinipigilan ang mga maagang pagkabigo",
        ms="Mengelakkan kekecewaan awal",
        mi="Ka waho i te māuiro pou",
    ),
    text(
        "communication.why2", 114,
        es="Alinea expectativas de contacto",
        en="It aligns expectations about contact",
        pt="Alinha expectativas de contato",
        fr="Aligne les attentes de contact",
        de="Stimmt die Erwartungen an Kontakt ab",
        it="Allinea le aspettative di contatto",
        ru="Согласует ожидания относительно общения",
        sv="Justerar förväntningar om kontakt",
        nl="Stemt verwachtingen over contact af",
        zh="对齐联系频率的预期",
        hi="संपर्क की अपेक्षाओं को मेल खाता है",
        bn="যোগাযোগের প্রত্যাশা সমন্বয় করে",
        ja="連絡についての期待をそろえる",
        ko="연락에 대한 기대를 맞춰줍니다",
        ar="يوائم التوقعات حول التواصل",
        sw="Inalingisha mategeleo ya mawasiliano",
        ha="Yana daidaita tsayayyuka",
        am="የመገናኘት ጥበቃዎችን ያስተካክላል",
        tl="Inii-align ang mga inaasahan sa pakikipag-ugnayan",
        ms="Menyelaraskan jangkaan mengenai hubungan",
        mi="Ka whakatau i ngā māraratanga mō te whakapā",
    ),
    text(
        "communication.why3", 115,
        es="Refleja compatibilidad energética",
        en="It reflects energy compatibility",
        pt="Reflete a compatibilidade energética",
        fr="Reflète la compatibilité énergétique",
        de="Spiegelt die Energiekompatibilität wider",
        it="Riflette la compatibilità energetica",
        ru="Отражает энергетическую совместимость",
        sv="Speglar energikompatibilitet",
        nl="Weerspiegelt energiecompatibiliteit",
        zh="体现能量匹配度",
        hi="ऊर्जा अनुकूलता को दर्शाता है",
        bn="শক্তির সামঞ্জস্য প্রতিফলিত করে",
        ja="気の相性を表す",
        ko="에너지 궁합을 반영합니다",
        ar="يعكس التوافق الطاقي",
        sw="Inaakisi utayari wa nguvu",
        ha="Yana nuna mutane da kuma",
        am="የኃይል ስምምነትን ያሳያል",
        tl="Ipinapakita ang pagkaangkop ng enerhiya",
        ms="Mencerminkan keserasian tenaga",
        mi="Ka whakaatu i te ōrite o te kaha",
    ),
    text(
        "communication.why4", 116,
        es="Modula el tono del vínculo",
        en="It modulates the tone of the bond",
        pt="Modula o tom do vínculo",
        fr="Module le ton du lien",
        de="Moduliert den Ton der Verbindung",
        it="Modula il tono del legame",
        ru="Модулирует тон связи",
        sv="Modulerar relationens ton",
        nl="Moduleert de toon van de band",
        zh="调节关系的基调",
        hi="रिश्ते के स्वर को साधते हैं",
        bn="সম্পর্কের সুর নিয়ন্ত্রণ করে",
        ja="関係のトーンを調整する",
        ko="관계의 분위기를 조절합니다",
        ar="يعدّل نبرة العلاقة",
        sw="Inarekebisha toni ya uhusiano",
        ha="Yana canza mita na alamar",
        am="የግንነት ምስጫን ያስተካክላል",
        tl="Ina-modulate ang tono ng ugnayan",
        ms="Mengawal nada hubungan",
        mi="Ka whakatau i te reo o te here",
    ),
    text(
        "communication.careImpactTitle", 117,
        es="🔄 Cómo afecta al algoritmo CARE:",
        en="🔄 How it affects the CARE algorithm:",
        pt="🔄 Como isso afeta o algoritmo CARE:",
        fr="🔄 Comment cela affecte-t-il l'algorithme CARE ?",
        de="🔄 Wie es den CARE-Algorithmus beeinflusst:",
        it="🔄 Come influenza l'algoritmo CARE:",
        ru="🔄 Как это влияет на алгоритм CARE:",
        sv="🔄 Så påverkar det CARE-algoritmen:",
        nl="🔄 Hoe dit het CARE-algoritme beïnvloedt:",
        zh="🔄 它如何影响 CARE 算法：",
        hi="🔄 यह CARE एल्गोरिदम को कैसे प्रभावित करता है:",
        bn="🔄 এটি CARE অ্যালগরিদমকে কীভাবে প্রভাবিত করে:",
        ja="🔄 CAREアルゴリズムへの影響：",
        ko="🔄 CARE 알고리즘에 미치는 영향:",
        ar="🔄 كيف يؤثر في خوارزمية CARE:",
        sw="🔄 Jinsi inavyohudhu kwa algoridimu ya CARE:",
        ha="🔄 Yana nuna yadda take shafi na CARE",
        am="🔄 CARE አልጎሪዝሙን መቅረበት።",
        tl="🔄 Paano ito nakakaapekto sa CARE algorithm:",
        ms="🔄 Bagaimana ia mempengaruhi algoritma CARE:",
        mi="🔄 Me pēhea tēnei e pāngai ki te tikara CARE:",
    ),
    text(
        "communication.careNote", 118,
        es="Tu estilo de comunicación define cómo fluye tu conexión. CARE lo usa para encontrar matches que se comuniquen como tú.",
        en="Your communication style defines how your connection flows. CARE uses it to find matches who communicate like you.",
        pt="Seu estilo de comunicação define como sua conexão flui. O CARE usa para encontrar combinações que se comunicam como você.",
        fr="Votre style de communication définit comment votre connexion s'écoule. CARE l'utilise pour trouver des matchs qui communiquent comme vous.",
        de="Ihr Kommunikationsstil bestimmt, wie Ihre Verbindung fließt. CARE nutzt ihn, um Matches zu finden, die wie Sie kommunizieren.",
        it="Il tuo stile di comunicazione definisce come scorre la tua connessione. CARE lo usa per trovare abbinamenti che comunicano come te.",
        ru="Ваш стиль общения определяет, как течёт ваше общение. CARE использует его, чтобы найти людей, которые общаются как вы.",
        sv="Din kommunikationsstil bestämmer hur din kontakt flyter. CARE använder den för att hitta träffar som kommunicerar som du.",
        nl="Je communicatiestijl bepaalt hoe je connectie stroomt. CARE gebruikt het om matches te vinden die communiceren zoals jij.",
        zh="你的沟通风格定义了你们联结的流动方式。CARE 用它来寻找沟通方式和你一样的人。",
        hi="आपकी संचार शैली यह तय करती है कि आपका जुड़ाव कैसे बहता है। CARE इसका उपयोग उन लोगों से मिलाने के लिए करता है जो आपकी तरह संवाद करते हैं।",
        bn="আপনার যোগাযোগের ধরন আপনার সংযোগ কীভাবে প্রবাহিত হয় তা নির্ধারণ করে। CARE এটি ব্যবহার করে এমন মানুষ খুঁজে বের করে যারা আপনার মতো কথা বলেন।",
        ja="あなたのコミュニケーションスタイルはつながりの流れ方を決めます。CARE はそれを使って、あなたと同じように話す人を見つけます。",
        ko="소통 스타일은 관계가 어떻게 흘러가는지를 결정합니다. CARE는 이를 사용해 당신처럼 소통하는 사람을 찾습니다.",
        ar="يحدد أسلوب تواصلك كيفية انسياب رابطتك. يستخدمه CARE للعثور على أشخاص يتواصلون مثلك.",
        sw="Mtindo wako wa mawasiliano unaeleza jinsi muunganisho wako unavyofumika. CARE unatumia kupata watu wanaozungumza kama wewe.",
        ha="Salinka yadda kake take yi amfani da shi don neman mutane da yake maganiya da kai",
        am="የግንነት አቀራረብህ ስለምን ግንነትህ እንወስድ እንቅሳል ያለው። CARE ይህን ለመጠቀሙ እርስህን ያናግሩ ተመሳሳይ ሰዎችን ያስገኛል።",
        tl="Ang iyong estilo ng komunikasyon ang nagtatakda kung paano dumadaloy ang iyong koneksyon. Ginagamit ito ng CARE para makahanap ng mga match na gaya ng sa iyo ang nakikipag-usap.",
        ms="Gaya komunikasi anda mentafsirkan bagaimana hubungan anda mengalir. CARE menggunakannya untuk mencari mereka yang berkomunikasi seperti anda.",
        mi="Ka whakatau tōu tikara whakawhiti i te rere o tōu here. Ka whakamahi a CARE i tei ki te rapu i te hunga e kōrero ana mai i te māhi tōu.",
    ),
    text(
        "communication.option.texting.label", 120,
        es="Mensajes", en="Messaging",
        pt="Mensagens", fr="Messages",
        de="Nachrichten", it="Messaggi",
        ru="Сообщения", sv="Meddelanden", nl="Berichten",
        zh="消息", hi="संदेश", bn="বার্তা",
        ja="メッセージ", ko="메시지", ar="الرسائل",
        sw="Ujumbe", ha="Saurare",
        am="መልእክቶች", tl="Mensahe",
        ms="Mesej", mi="Karere",
    ),
    text(
        "communication.option.texting.desc", 121,
        es="Prefieres la comunicación por mensajes de texto.",
        en="You prefer communicating by text message.",
        pt="Você prefere comunicar por mensagens de texto.",
        fr="Vous préférez communiquer par messages texte.",
        de="Du kommunizierst bevorzugt per Textnachricht.",
        it="Preferisci comunicarti tramite messaggi di testo.",
        ru="Вы предпочитаете общаться в текстовых сообщениях.",
        sv="Du föredrar att kommunicera via textmeddelanden.",
        nl="Je communiceert het liefst via sms.",
        zh="你更喜欢通过文字消息沟通。",
        hi="आप टेक्स्ट संदेशों से संवाद करना पसंद करते हैं।",
        bn="আপনি লেখার বার্তার মাধ্যমে কথা বলতে পছন্দ করেন।",
        ja="テキストメッセージでのやりとりを好みます。",
        ko="문자 메시지로 소통하는 것을 선호해요.",
        ar="تفضّل التواصل عبر الرسائل النصية.",
        sw="Unapenda kuzungumza kupitia ujumbe wa maandishi.",
        ha="Kana son hujayi taƙaƙa",
        am="በጽሑፍ መልእክት ለመገናኘት ይፈልጋለህ።",
        tl="Mas gusto mong makipag-usap sa pamamagitan ng mensahe.",
        ms="Anda lebih suka berkomunikasi melalui mesej teks.",
        mi="Ka hiahia koe ki te kōrero ma te karere kupere.",
    ),
    text(
        "communication.option.texting.careImpact", 122,
        es="CARE priorizará matches que también prefieran mensajes y creará rituales escritos íntimos.",
        en="CARE will prioritize matches who also prefer messaging and create intimate written rituals.",
        pt="O CARE priorizará combinações que também preferem mensagens e criará rituais escritos íntimos.",
        fr="CARE privilégiera les matchs qui préfèrent aussi les messages et créera des rituels écrits intimes.",
        de="CARE priorisiert Matches, die ebenfalls Nachrichten bevorzugen, und schafft intime schriftliche Rituale.",
        it="CARE darà priorità agli abbinamenti che preferiscono i messaggi e creerà rituali scritti intimi.",
        ru="CARE будет отдавать приоритет тем, кто тоже предпочитает сообщения, и создавать интимные письменные ритуалы.",
        sv="CARE prioriterar träffar som också föredrar meddelanden och skapar intima skrivna ritualer.",
        nl="CARE zal voorrang geven aan matches die ook van berichten houden en intieme schriftelijke rituelen creëren.",
        zh="CARE 会优先匹配同样喜欢消息的人，并创造亲密的文字仪式。",
        hi="CARE उन लोगों को प्राथमिकता देगा जो संदेश भी पसंद करते हैं और अंतिम लिखित अनुष्ठान बनाएगा।",
        bn="CARE এমন মানুষকে অগ্রাধিকার দেবে যারাও বার্তা পছন্দ করেন এবং ঘনিষ্ঠ লিখিত অনুষ্ঠান তৈরি করবে।",
        ja="メッセージ式のやりとりを好む相手を優先し、親密な文面の儀式を生み出します。",
        ko="메시지를 선호하는 사람에게 우선권을 주고 친밀한 글쓰기 의식을 만들어요.",
        ar="سيعطي CARE الأولوية لمن يفضلون الرسائل أيضًا وينشئ طقوسًا كتابية حميمة.",
        sw="CARE itapendeleza watu wanaopenda ujumbe pia na kutengeneza mila za maandishi za karibu.",
        ha="CARE za ta sanya mutane da yake son hujayi daƙi shi, sannan ta ƙirƙiri ayyuka naƙaƙai.",
        am="CARE መልእክቶችንም የሚፈልጉ ሰዎችን በቅድሚያ በማቀረብ የጽሑፍ የትርጅት ልማቶችን ይፈጥራል።",
        tl="Ita-prioritize ng CARE ang mga match na masyadong masyahan sa mga mensahe at gagawa ng malalim na ritwal na nakasulat.",
        ms="CARE akan mengutamakan mereka yang turut lebih suka mesej dan mencipta ritual bertulis yang intim.",
        mi="Ka āta whakapiri a CARE ki te hunga e hiahia ana ki te karere, ka waho hoki ia i ngā tikara tuhi whaikōrero.",
    ),
    text(
        "communication.option.phone_call.label", 123,
        es="Llamadas", en="Calls",
        pt="Chamadas", fr="Appels",
        de="Anrufe", it="Chiamate",
        ru="Звонки", sv="Samtal", nl="Gesprekken",
        zh="通话", hi="कॉल", bn="কল",
        ja="通話", ko="전화 통화", ar="المكالمات",
        sw="Simu", ha="Kira",
        am="ጥሪት", tl="Tawagan",
        ms="Panggilan", mi="Waea",
    ),
    text(
        "communication.option.phone_call.desc", 124,
        es="Te gusta hablar por teléfono y tener conversaciones profundas.",
        en="You like talking on the phone and having deep conversations.",
        pt="Você gosta de falar por telefone e ter conversas profundas.",
        fr="Vous aimez parler au téléphone et avoir des conversations profondes.",
        de="Du sprichst gerne telefonisch und hast gerne tiefe Gespräche.",
        it="Ti piace parlare al telefono e avere conversazioni profonde.",
        ru="Вы любите разговаривать по телефону и вести глубокие беседы.",
        sv="Du gillar att prata i telefon och ha djupa samtal.",
        nl="Je praat graag met de telefoon en hebt graag diepe gesprekken.",
        zh="你喜欢打电话聊天，享受深入的对话。",
        hi="आपको फ़ोन पर बात करना और गहरी बातचीत करना पसंद है।",
        bn="আপনি ফোনে কথা বলতে এবং গভীর আলাপ করতে পছন্দ করেন।",
        ja="電話での会話や深い話を好みます。",
        ko="전화로 이야기하고 깊은 대화를 나누는 것을 좋아해요.",
        ar="تحب التحدث هاتفيًا وإجراء محادثات عميقة.",
        sw="Unapenda kuzungumza kwa simu na kuwa na mazungumzo marefu.",
        ha="Kana son ya waya da zurfin hujayi.",
        am="በስልክ መናገርና ጥልቅ ውይይት መካለትን ይችላለህ።",
        tl="Enjoy mo ang pag-usap sa telepono at malalim na usapan.",
        ms="Anda suka berbual melalui telefon dan berbual panjang.",
        mi="Ka hiahia koe ki te kōrero ma te waea, ki te kōrero hōhonu.",
    ),
    text(
        "communication.option.phone_call.careImpact", 125,
        es="CARE usará un tono más directo y emocional en las interacciones.",
        en="CARE will use a more direct and emotional tone in interactions.",
        pt="O CARE usará um tom mais direto e emocional nas interações.",
        fr="CARE utilisera un ton plus direct et émotionnel dans les interactions.",
        de="CARE wird in den Interaktionen einen direkteren und emotionaleren Ton verwenden.",
        it="CARE userà un tono più diretto ed emotivo nelle interazioni.",
        ru="CARE будет использовать более прямой и эмоциональный тон в общении.",
        sv="CARE kommer att använda en mer direkt och känslomässig ton i interaktionerna.",
        nl="CARE zal een directere en emotionelere toon gebruiken in de interacties.",
        zh="CARE 会在互动中采用更直接、更富情感的语调。",
        hi="CARE बातचीत में अधिक सीधा और भावनात्मक स्वर का उपयोग करेगा।",
        bn="CARE কথোপকথনে আরও সরাসরি ও আবেগপূর্ণ ভাষা ব্যবহার করবে।",
        ja="やり取りでは、より直接的で感情的な言い方を使います。",
        ko="CARE는 대화에서 더 직접적이고 감정적인 톤을 사용합니다.",
        ar="سيستخدم CARE نبرة أكثر مباشرة وعاطفية في التفاعلات.",
        sw="CARE itatumia sauti moja kueleka na yenye hisa katika mazungumzo.",
        ha="CARE za ta yi amfani da mita mai tsawani kuma mai zuciya.",
        am="CARE በግብይቶች ውስጥ ቀጥታና ስሜታዊ ድምፅ ይጠቀማል።",
        tl="Gagamit ng CARE ang mas tuwiran at emosyonal na tono sa mga interaksyon.",
        ms="CARE akan menggunakan nada yang lebih langsung dan emosi dalam interaksi.",
        mi="Ka whakamahi a CARE i te reo tōturu ake me te reo aroha.",
    ),
    text(
        "communication.option.video_call.label", 126,
        es="Videollamadas", en="Video calls",
        pt="Videochamadas", fr="Appels vidéo",
        de="Videoanrufe", it="Videochiamate",
        ru="Видеозвонки", sv="Videosamtal", nl="Videobellen",
        zh="视频通话", hi="वीडियो कॉल", bn="ভিডিও কল",
        ja="ビデオ通話", ko="영상 통화",
        ar="مكالمات الفيديو",
        sw="Video za wazi", ha="Kira mai hoto",
        am="የቪዲዮ ጥሪት", tl="Video call",
        ms="Panggilan video", mi="Waea hōhonu",
    ),
    text(
        "communication.option.video_call.desc", 127,
        es="Prefieres ver a la persona mientras hablas.",
        en="You prefer seeing the person while you talk.",
        pt="Você prefere ver a pessoa enquanto fala.",
        fr="Vous préférez voir la personne pendant que vous parlez.",
        de="Du siehst die Person lieber, während du sprichst.",
        it="Preferisci vedere la persona mentre parli.",
        ru="Вы предпочитаете видеть человека, пока разговариваете.",
        sv="Du föredrar att se personen medan du pratar.",
        nl="Je ziet de persoon liever terwijl je praat.",
        zh="你更喜欢在聊天时看到对方。",
        hi="आप बात करते समय व्यक्ति को देखना पसंद करते हैं।",
        bn="আপনি কথা বলার সময় ব্যক্তিকে দেখতে পছন্দ করেন।",
        ja="話している相手の顔を見るほうが好きです。",
        ko="대화할 때 상대의 얼굴을 보는 것을 선호해요.",
        ar="تفضّل رؤية الشخص أثناء حديثك.",
        sw="Unapenda kumwona mtu unavyozungumza naye.",
        ha="Kana son gani mutum alhacin da kake maganiya",
        am="የሚናግረውን ሰዎች በመናገር ሳትቀይቅ ለመመልከት ይፈልጋለህ።",
        tl="Mas gusto mong makita ang tao habang nag-uusap kayo.",
        ms="Anda lebih suka melihat orang itu semasa bercakap.",
        mi="Ka hiahia koe ki te kite i te tanga i te wā e kōrero ana.",
    ),
    text(
        "communication.option.video_call.careImpact", 128,
        es="CARE priorizará progresión visual y revelación facial en Blind Mode.",
        en="CARE will prioritize visual progression and face reveal in Blind Mode.",
        pt="O CARE priorizará progressão visual e revelação de rosto no Modo Oculto.",
        fr="CARE privilégiera la progression visuelle et la révélation du visage en Mode Aveugle.",
        de="CARE priorisiert visuelle Entwicklung und Gesichtsenthüllung im Blindmodus.",
        it="CARE darà priorità alla progressione visiva e alla rivelazione del volto in Modalità Cegas.",
        ru="CARE будет отдавать приоритет визуальному развитию и раскрытию лица в слепом режиме.",
        sv="CARE prioriterar visuell utveckling och ansiktesavslöjande i blint läge.",
        nl="CARE zal visuele vooruitgang en onthulling van het gezicht in Blind Mode prioriteren.",
        zh="CARE 会在蒙面模式下优先推进视觉进展与露脸。",
        hi="CARE ब्लाइंड मोड में दृश्य प्रगति और चेहरा खोलने को प्राथमिकता देगा।",
        bn="CARE অন্ধ মোডে ভিজ্যুয়াল অগ্রগতি ও মুখ প্রকাশকে অগ্রাধিকার দেবে।",
        ja="CARE はシークレットモードでの視覚的な進展と顔の公開を優先します。",
        ko="CARE는 블라인드 모드에서 시각적 진행과 얼굴 공개를 우선합니다.",
        ar="سيعطي CARE الأولوية للتقدم البصري وكشف الوجه في وضع التعتيم.",
        sw="CARE itapendeleza maendeleo ya macho na kufichua uso katika hali ya kuficha uso.",
        ha="CARE za ta sanya gadan ganiya da buɗewar ido girmama daraja a cikin yanayin ɓoye ido.",
        am="CARE በዓል ምልከታ ውስጥ የምስል መሻሻልንና የፊት መፈታትን በቅድሚያ ያቀርጣል።",
        tl="I-prioritize ng CARE ang visual progression at pag-reveal ng mukha sa Blind Mode.",
        ms="CARE akan mengutamakan kemajuan visual dan muka dalam Modus Buta.",
        mi="Ka āta whakapiri a CARE ki te whainga kite, me te whakaatu i te kanohi i te arō matāpere.",
    ),
    text(
        "communication.option.bad_texter.label", 129,
        es="Mal texter", en="Bad texter",
        pt="Mau texter", fr="Mauvais texteur",
        de="Schlechter Texter",
        it="Scarso scrittore di messaggi",
        ru="Плохо пишущий в сообщениях",
        sv="Dålig på att skriva", nl="Slecht in sms'en",
        zh="不擅长发消息", hi="संदेश लिखने में कमजोर",
        bn="বার্তা লেখায় দুর্বল",
        ja="メッセージが苦手", ko="메시지 쓰는 게 서툴한",
        ar="ضعيف في كتابة الرسائل",
        sw="Huandika ujumbe vibaya", ha="Maiƙi aƙin rubutun saƙo",
        am="በመልእክት ላይ ደካማ", tl="Hindi ako magaling sa teksto",
        ms="Lemah messaging", mi="Ka kore e pai te kōrero karere",
    ),
    text(
        "communication.option.bad_texter.desc", 130,
        es="No eres muy bueno/a respondiendo mensajes.",
        en="You are not very good at replying to messages.",
        pt="Você não é muito bom respondendo mensagens.",
        fr="Tu n'es pas très bon pour répondre aux messages.",
        de="Du bist nicht besonders gut darin, auf Nachrichten zu antworten.",
        it="Non sei molto bravo a rispondere ai messaggi.",
        ru="Вы не очень хорошо отвечаете на сообщения.",
        sv="Du är inte särskilt bra på att svara på meddelanden.",
        nl="Je bent niet erg goed in het beantwoorden van berichten.",
        zh="你不太擅长回复消息。",
        hi="आप संदेशों का जवाब देने में बहुत अच्छे नहीं हैं।",
        bn="আপনি বার্তার উত্তর দিতে খুব ভালো নন।",
        ja="メッセージへの返信は得意ではありません。",
        ko="메시지에 답하는 데에는 서툴어요.",
        ar="لست جيدًا جدًا في الرد على الرسائل.",
        sw="Hujajibu ujumbe vizuri sana.",
        ha="Kanaƙi amsaƙi ba da kyau",
        am="መልእክቶችን በተገቢል ቀስት ለመምትል",
        tl="Hindi ako magaling sa pagsagot ng mensahe.",
        ms="Anda tidak sangat baik dalam membalas mesej.",
        mi="Kāore he tino pai koe ki te whakautu karere.",
    ),
    text(
        "communication.option.bad_texter.careImpact", 131,
        es="CARE usará un tono paciente y reducirá la frecuencia de notificaciones.",
        en="CARE will use a patient tone and reduce notification frequency.",
        pt="O CARE usará um tom paciente e reduzirá a frequência de notificações.",
        fr="CARE utilisera un ton patient et réduira la fréquence des notifications.",
        de="CARE verwendet einen geduldigen Ton und senkt die Benachrichtigungshäufigkeit.",
        it="CARE userà un tono paziente e ridurrà la frequenza delle notifiche.",
        ru="CARE будет использовать терпеливый тон и уменьшит частоту уведомлений.",
        sv="CARE använder ett tålmodigt ton och minskar aviseringarnas frekvens.",
        nl="CARE zal een geduldige toon gebruiken en de notificatiefrequentie verlagen.",
        zh="CARE 会采用耐心的语气，并减少通知频率。",
        hi="CARE धैर्यवान स्वर का उपयोग करेगा और सूचनाओं की आवृत्ति कम करेगा।",
        bn="CARE ধৈর্যশীল ভাষা ব্যবহার করবে এবং বিজ্ঞপ্তির হার কমাবে।",
        ja="CARE は辛抱強い言い方を使い、通知の回数を減らします。",
        ko="CARE는 인내심 있는 톤을 사용하고 알림 빈도를 줄입니다.",
        ar="سيستخدم CARE نبرة صبورة ويقلل تكرار الإشعارات.",
        sw="CARE itatumia sauti ya uvumilivu na kutaratibu arifa chache.",
        ha="CARE za ta yi amfani da mita mai hawwa, sa'an kuma ta rage yawanin sanarwa.",
        am="CARE ተገቢል ድምፅ ይጠቀማል እንም የማስጠንቀቂያ ብዛትን ይቀንሳል።",
        tl="Magagamit ng CARE ang pasyenteng tono at ibababa ang dalas ng mga abiso.",
        ms="CARE akan menggunakan nada yang sabar dan mengurangkan pemberitahuan.",
        mi="Ka whakamahi a CARE i te reo manawaroa, ā ka whakawharewareware ngā whakamohio.",
    ),
    text(
        "communication.option.in_person.label", 132,
        es="En persona", en="In person",
        pt="Pessoalmente", fr="En personne",
        de="Persönlich", it="Di persona",
        ru="Лично", sv="Personligen", nl="Persoonlijk",
        zh="线下见面", hi="व्यक्तिगत रूप से", bn="সরাসরি",
        ja="対面", ko="직접 만나기", ar="شخصيًا",
        sw="Uso mo", ha="Kan tare da kai",
        am="በቀጥታ", tl="Personal",
        ms="Bersemuka", mi="Kanohi ki te kanohi",
    ),
    text(
        "communication.option.in_person.desc", 133,
        es="Prefieres conocer a las personas cara a cara.",
        en="You prefer getting to know people face to face.",
        pt="Você prefere conhecer as pessoas cara a cara.",
        fr="Vous préférez rencontrer les gens en face à face.",
        de="Du lernst Menschen lieber von Angesicht zu Angesicht kennen.",
        it="Preferisci conoscere le persone faccia a faccia.",
        ru="Вы предпочитаете знакомиться с людьми лицом к лицу.",
        sv="Du föredrar att träffa människor ansikt mot ansikt.",
        nl="Je leert mensen liever van persoon tot persoon kennen.",
        zh="你更喜欢与人面对面相识。",
        hi="आप लोगों से सामने-सामने मिलकर परिचित होना पसंद करते हैं।",
        bn="আপনি মানুষের সাথে সরাসরি সাক্ষাৎ করে পরিচিত হতে পছন্দ করেন।",
        ja="人と直接会って知ることを好みます。",
        ko="사람과 직접 만나 아는 것을 선호해요.",
        ar="تفضّل التعرف على الأشخاص وجهاً لوجه.",
        sw="Unapenda kukutana na watu uso kwa uso.",
        ha="Kana son ganin mutane aƙƙo da shi.",
        am="ሰዎችን በቀጥታ እንደማወቅ ይፈልጋለህ።",
        tl="Mas gusto mong makilala nang personal sa mga tao.",
        ms="Anda lebih suka mengenali orang secara bersemuka.",
        mi="Ka hiahia koe ki te kite i te hunga kanohi ki te kanohi.",
    ),
    text(
        "communication.option.in_person.careImpact", 134,
        es="CARE priorizará cercanía geográfica y sugerirá encuentros presenciales.",
        en="CARE will prioritize geographic proximity and suggest in-person meetings.",
        pt="O CARE priorizará a proximidade geográfica e sugerirá encontros presenciais.",
        fr="CARE privilégiera la proximité géographique et suggérera des rencontres en personne.",
        de="CARE priorisiert geografische Nähe und schlägt persönliche Treffen vor.",
        it="CARE darà priorità alla vicinanza geografica e suggerirà incontri di persona.",
        ru="CARE будет отдавать приоритет географической близости и предлагать личные встречи.",
        sv="CARE prioriterar geografisk närhet och föreslår möten ansikt mot ansikt.",
        nl="CARE zal geografische nabijheid prioriteren en persoonlijke ontmoetingen voorstellen.",
        zh="CARE 会优先考虑地理接近度，并建议线下见面。",
        hi="CARE भौगोलिक निकटता को प्राथमिकता देगा और व्यक्तिगत मुलाक़ात सुझाएगा।",
        bn="CARE ভৌগোলিক কাছাকাছি অগ্রাধিকার দেবে এবং সরাসরি সাক্ষাৎের পরামর্শ দেবে।",
        ja="CARE は地理的な近さを優先し、対面の交会を提案します。",
        ko="CARE는 지리적 근접성을 우선하고 직접 만남을 제안합니다.",
        ar="سيعطي CARE الأولوية للقرب الجغرافي ويقترح لقاءات حاضرة.",
        sw="CARE itapendeleza ukaribu wa kijiografia na kupendekeza miutano ya uso kwa uso.",
        ha="CARE za ta mayar da hankali na tsaro, sannan ta ba da shawara kan ziyawa da kar tare.",
        am="CARE የመልክር ቅርበትን በቅድሚያ አድርጎ መገናኘት መባልን ያቀርጣል።",
        tl="I-prioritize ng CARE ang geograpiyang kalakip at magrerekomenda ng personal na pagtatagpo.",
        ms="CARE akan mengutamakan kedekatan geografi dan mencadangkan pertemuan bersemuka.",
        mi="Ka āta whakapiri a CARE ki te tata ā-whenua, ā ka tohutohu i ngā hui kanohi ki te kanohi.",
    ),
]