"""UI texts for the "Planes de familia" (Family Plans) subsection."""

from .common import text

TEXTS = [
    text(
        "family.title", 80,
        es="Planes de familia", en="Family plans",
        pt="Planos familiares", fr="Projets familiaux",
        de="Familienpläne", it="Piani familiari",
        ru="Семейные планы", sv="Familjeplaner", nl="Gezinsplannen",
        zh="家庭计划", hi="परिवार योजनाएं", bn="পারিবারিক পরিকল্পনা",
        ja="家族のプラン", ko="가족 계획", ar="خطط العائلة",
        sw="Mipango ya familia", ha="Tsarin iyali",
        am="የቤተሰብል ዕቅድ", tl="Mga plano ng pamilya",
        ms="Pelan keluarga", mi="Ngā mahere whānau",
    ),
    text(
        "family.question", 81,
        es="¿Cuál es tu postura actual sobre tener hijos?",
        en="What is your current stance on having children?",
        pt="Qual é a sua posição atual sobre ter filhos?",
        fr="Quelle est votre position actuelle sur le fait d'avoir des enfants ?",
        de="Wie ist Ihre derzeitige Haltung dazu, Kinder zu bekommen?",
        it="Qual è la tua posizione attuale sull'avere figli?",
        ru="Какова ваша позиция сейчас по поводу детей?",
        sv="Vad är din nuvarande syn på att få barn?",
        nl="Wat is je huidige houding tegenover het krijgen van kinderen?",
        zh="你目前对生育子女的态度是什么？",
        hi="बच्चे होने के बारे में आपकी वर्तमान स्थिति क्या है?",
        bn="সন্তান হওয়া নিয়ে আপনার বর্তমান অবস্থান কী?",
        ja="子供を持つことについての今の気持ちは？",
        ko="자녀를 갖는 것에 대해 지금 어떻게 생각하시나요?",
        ar="ما هو موقفك الحالي من إنجاب الأطفال؟",
        sw="Ni nini hoja yako kwa sasa kuhusu kuwa na watoto?",
        ha="Me ya kana yi nufi ta yadda kake da haifi yaro?",
        am="አሁን ስለልጆች ያለዎት አቋም አንድ ነው።",
        tl="Ano ang kasalukuyan mong pananaw sa pagkakaroon ng anak?",
        ms="Apakah pendirian semasa anda tentang mempunyai anak?",
        mi="He aha tōu whakaaro ināianei mō te whai tamariki?",
    ),
    text(
        "family.tip", 82,
        es="💡 Tu decisión sobre tener hijos es parte de tu camino. Aquí puedes expresarla con libertad.",
        en="💡 Your decision about having children is part of your journey. Here you can express it freely.",
        pt="💡 Sua decisão sobre ter filhos faz parte da sua jornada. Aqui você pode expressá-la com liberdade.",
        fr="💡 Votre décision d'avoir ou non des enfants fait partie de votre chemin. Vous pouvez l'exprimer librement ici.",
        de="💡 Ihre Entscheidung zu Kindern ist Teil Ihres Weges. Hier können Sie sie frei äußern.",
        it="💡 La tua decisione sull'avere figli fa parte del tuo percorso. Qui puoi esprimerla liberamente.",
        ru="💡 Ваше решение о детях — часть вашего пути. Здесь вы можете свободно его высказать.",
        sv="💡 Ditt beslut om barn är en del av din väg. Här kan du uttrycka det fritt.",
        nl="💡 Je beslissing over kinderen is onderdeel van je reis. Hier kun je het vrij uiten.",
        zh="💡 你关于生育的决定是你人生旅程的一部分。在这里你可以自由表达。",
        hi="💡 बच्चे होने के बारे में आपका निर्णय आपकी यात्रा का हिस्सा है। यहाँ आप इसे स्वतंत्र रूप से व्यक्त कर सकते हैं।",
        bn="💡 সন্তান হওয়া সম্পর্কে আপনার সিদ্ধান্ত আপনার পথের একটি অংশ। এখানে আপনি নির্দ্বিধায় তা প্রকাশ করতে পারেন।",
        ja="💡 子供についてのあなたの選択は、人生の旅の一部です。ここで自由に表現できます。",
        ko="💡 자녀에 대한 당신의 결정은 여정의 한 부분입니다. 여기서 자유롭게 표현할 수 있습니다.",
        ar="💡 قرارك بشأن إنجاب الأطفال جزء من رحلتك. يمكنك التعبير عنه بحرية هنا.",
        sw="💡 Uamuzi wako kuhusu watoto ni sehemu ya safari yako. Unaweza kuueleza kwa uhuru hapa.",
        ha="Shawararinka kanne yafi da haifi yaro wani ne daga jagorantarinka. Za ka iya faɗa ba tare da damar ba a nan.",
        am="💡 ስለልጆች የወለዱት ውሳኔ ከመንገርህ አካል ነው። እህና በሙሉ ነፃነት መግለጽ ትችላለህ።",
        tl="💡 Ang desisyon mo tungkol sa pagkakaroon ng anak ay bahagi ng iyong paglalakbay. Dito mo ito maaaring ipahayag nang malaya.",
        ms="💡 Keputusan anda mengenai mempunyai anak adalah sebahagian daripada perjalanan anda. Di sini anda boleh menyatakannya dengan bebas.",
        mi="💡 Tō whakatau mō te whai tamariki he wāhanga nō tōu haerenga. Ka taea e koe ki te kōrero ki te māori i konei.",
    ),
    text(
        "family.relevantLabel", 83,
        es="¿Te gustaría que esta información influya en tu compatibilidad?",
        en="Would you like this information to influence your compatibility?",
        pt="Você gostaria que esta informação influenciasse sua compatibilidade?",
        fr="Souhaiteriez-vous que cette information influence votre compatibilité ?",
        de="Soll diese Information Ihre Kompatibilität beeinflussen?",
        it="Vorresti che questa informazione influenzi la tua compatibilità?",
        ru="Хотите, чтобы эта информация влияла на вашу совместимость?",
        sv="Vill du att denna information påverkar din kompatibilitet?",
        nl="Wil je dat deze informatie je compatibiliteit beïnvloedt?",
        zh="你希望这些信息影响你的匹配度吗？",
        hi="क्या आप चाहते हैं कि यह जानकारी आपकी अनुकूलता को प्रभावित करे?",
        bn="আপনি কি চান যে এই তথ্য আপনার সামঞ্জস্যতাকে প্রভাবিত করুক?",
        ja="この情報があなたのマッチに影響を与えることを希望しますか？",
        ko="이 정보가 당신의 궁합에 영향을 주기를 원하시나요?",
        ar="هل تريد أن تؤثر هذه المعلومات في توافقك؟",
        sw="Ungependa taarifa hii ionyeshe kwenye uoendana wako?",
        ha="Kana so wannan bayanai ya nuna cewa ta yi daɗawa da mutammaninka?",
        am="ይህ መረጃ ማስማሚነትህን እንወስድ ይፈልጋለህ?",
        tl="Gusto mo bang ang impormasyong ito ay makaaalam sa compatibility mo?",
        ms="Adakah anda mahu maklumat ini mempengaruhi keserasian anda?",
        mi="E hiahia ana koe kia whakatau kōtū tēnei mōhio?",
    ),
    text(
        "family.relevantTooltip", 84,
        es="Tu plan familiar puede influir en tu compatibilidad. Tú decides si lo activas.",
        en="Your family plan can influence your compatibility. You decide whether to switch it on.",
        pt="Seu plano familiar pode influenciar sua compatibilidade. Você decide se o ativa.",
        fr="Votre projet familial peut influencer votre compatibilité. Vous décidez de l'activer.",
        de="Ihr Familienplan kann Ihre Kompatibilität beeinflussen. Sie entscheiden, ob Sie ihn aktivieren.",
        it="Il tuo piano familiare può influenzare la tua compatibilità. Decidi tu se attivarlo.",
        ru="Ваш семейный план может влиять на вашу совместимость. Вы решаете, включать его или нет.",
        sv="Din familjeplan kan påverka din kompatibilitet. Du bestämmer om du aktiverar den.",
        nl="Je gezinsplan kan je compatibiliteit beïnvloeden. Jij bepaalt of je het activeert.",
        zh="你的家庭计划可以影响你的匹配度。是否启用由你决定。",
        hi="आपका परिवार प्लान आपकी अनुकूलता को प्रभावित कर सकता है। इसे चालू करना है या नहीं, यह आप तय करते हैं।",
        bn="আপনার পারিবারিক পরিকল্পনা আপনার সামঞ্জস্যতাকে প্রভাবিত করতে পারে। এটি চালু করবেন কি না তা আপনি ঠিক করবেন।",
        ja="家族のプランはマッチに影響を与えることがあります。有効にするかどうかはおあなたが決めてください。",
        ko="가족 계획은 궁합에 영향을 줄 수 있습니다. 활성화 여부는 당신이 결정합니다.",
        ar="قد تؤثر خطتك العائلية في توافقك. أنت تقرر تفعيلها.",
        sw="Mipango yako ya familia inaweza kushikilia uoendana wako. Unaamua kuwasukuma au la.",
        ha="Tsarin iyali na iya nuna cewa ta yi daɗawa da mutammaninka. Kana yanke ko za a kunna shi ko ba.",
        am="የቤተሰብል ዕቅድህ ማስማሚነትህን ሊጎዳ ይችላል። ማስተዋልበት አለ ወይስ አላለ በራስህ ይወሰናል።",
        tl="Ang plano ng pamilya ay maaaring makaaalam sa compatibility mo. Ikaw ang nagpapasiya kung ia-on ito o hindi.",
        ms="Pelan keluarga anda boleh mempengaruhi keserasian anda. Anda yang memutuskan sama ada untuk mengaktifkannya.",
        mi="Ka taea tō te mahere whānau e pāngai tō te whakatau kōtū. Ka koe e whakatau mō te whakature.",
    ),
    text(
        "family.childQuestion", 85,
        es="🧠 ¿Estás abierto/a a conectar con alguien que ya tenga hijos?",
        en="🧠 Are you open to connecting with someone who already has children?",
        pt="🧠 Você está aberto a conectar com alguém que já tenha filhos?",
        fr="🧠 Êtes-vous ouvert à rencontrer quelqu'un qui a déjà des enfants ?",
        de="🧠 Sind Sie offen für eine Verbindung mit jemandem, der bereits Kinder hat?",
        it="🧠 Sei aperto a connetterti con qualcuno che ha già dei figli?",
        ru="🧠 Готовы ли вы общаться с тем, у кого уже есть дети?",
        sv="🧠 Är du öppen för att koppla med någon som redan har barn?",
        nl="🧠 Sta je open om te connecten met iemand die al kinderen heeft?",
        zh="🧠 你愿意与已经有孩子的人建立联结吗？",
        hi="🧠 क्या आप उनसे जुड़ना चाहेंगे जिनके पहले से बच्चे हैं?",
        bn="🧠 আপনি কি এমন কারও সাথে সংযুক্ত হতে চান যার ইতিমধ্যে সন্তান আছে?",
        ja="🧠 すでに子どもがいる人とつながることに開かれていますか？",
        ko="🧠 이미 자녀가 있는 사람과 연결되는 것에 열려 있으신가요?",
        ar="🧠 هل أنت منفتح على التواصل مع شخص لديه أطفال بالفعل؟",
        sw="Je, umeweka kuwa tayari kuunganisha na mtu ambaye tayari ana watoto?",
        ha="Ka buɗe kowane gani da zai yi hannu da mutum da yake da yaro?",
        am="አሁን ያሉት ልጆች ያላቸው ሰዎች ጋር እንደመገናኘት ክፈት ነዎት?",
        tl="Handa ka bang makaugnayan sa isang taong may anak na?",
        ms="Adakah anda terbuka untuk berhubung dengan seseorang yang sudah mempunyai anak?",
        mi="Ka tuwhera ana koe ki te here ki tētahi kua whai tamariki nei?",
    ),
    text(
        "family.disabled", 86,
        es="Preferencia desactivada", en="Preference disabled",
        pt="Preferência desativada", fr="Préférence désactivée",
        de="Einstellung deaktiviert", it="Preferenza disattivata",
        ru="Настройка отключена", sv="Inställning avstängd",
        nl="Voorkeur uitgeschakeld",
        zh="偏好已关闭", hi="प्राथमिकता बंद है", bn="পছন্দ বন্ধ করা আছে",
        ja="この設定は無効です", ko="이 선호 설정은 꺼져 있습니다",
        ar="تم تعطيل التفضيل",
        sw="Mapendeleo yamezimwa", ha="Za a kashe zaɗi",
        am="ቅንብር ጠፍቷል", tl="Naka-off ang preference",
        ms="Keutamaan dinyahikan", mi="Kua kore whiringa",
    ),
    text(
        "family.quote", 87,
        es="Tu plan familiar es parte de tu esencia. CARE lo usará para encontrar conexiones más profundas.",
        en="Your family plan is part of your essence. CARE will use it to find deeper connections.",
        pt="Seu plano familiar faz parte da sua essência. O CARE vai usá-lo para encontrar conexões mais profundas.",
        fr="Votre projet familial fait partie de votre essence. CARE l'utilisera pour trouver des connexions plus profondes.",
        de="Ihr Familienplan ist Teil Ihrer Wesensart. CARE nutzt ihn, um tiefere Verbindungen zu finden.",
        it="Il tuo piano familiare fa parte della tua essenza. CARE lo userà per trovare connessioni più profonde.",
        ru="Ваш семейный план — часть вашей сути. CARE использует его, чтобы найти более глубокие связи.",
        sv="Din familjeplan är en del av din kärna. CARE använder den för att hitta djupare kontakter.",
        nl="Je gezinsplan maakt deel uit van je essentie. CARE gebruikt het om diepere verbindingen te vinden.",
        zh="你的家庭计划是你本质的一部分。CARE 会用它来寻找更深的联结。",
        hi="आपका परिवार प्लान आपकी पहचान का हिस्सा है। CARE इसका उपयोग गहरे जुड़ाव खोजने के लिए करेगा।",
        bn="আপনার পারিবারিক পরিকল্পনা আপনার মূল পরিচয়ের একটি অংশ। CARE এটি দিয়ে আরও গভীর সংযোগ খুঁজবে।",
        ja="家族のプランはあなたの本質の一部です。CARE はこれを使ってより深いつながりを見つけます。",
        ko="가족 계획은 당신의 본질의 일부입니다. CARE는 이를 사용해 더 깊은 연결을 찾습니다.",
        ar="خطتك العائلية جزء من جوهرك. سيستخدمها CARE للعثور على روابط أعمق.",
        sw="Mipango yako ya familia ni sehemu ya asili yako. CARE itatumia kupata miungo iliyo karibu zaidi.",
        ha="Tsarin iyali wani ne daga ainihinka. CARE za ta yi amfani da shi don neman mahaɗuwa mai zurfin.",
        am="የቤተሰብል ዕቅድህ ከመለያህ አካል ነው። CARE ይህን ለመጠቀሙ የተጋሩ ግንኙነቶችን ያስገኛል።",
        tl="Ang plano ng pamilya ay bahagi ng iyong pagkatao. Ia gamitin ito ng CARE upang makahanap ng mas malalim na koneksyon.",
        ms="Pelan keluarga anda adalah sebahagian daripada esensi anda. CARE akan menggunakannya untuk mencari hubungan yang lebih mendalam.",
        mi="He wāhanga tō te mahere whānau i tōu mauri. Ka whakamahi a CARE i tei ki te rapu i ngā here hōhonu ake.",
    ),
    text(
        "family.option.wants_children.label", 90,
        es="Quiero hijos", en="I want children",
        pt="Quero filhos", fr="Je veux des enfants",
        de="Ich möchte Kinder", it="Voglio figli",
        ru="Хочу детей", sv="Jag vill ha barn", nl="Ik wil kinderen",
        zh="我要孩子", hi="मैं बच्चे चाहता/चाहती हूं", bn="আমি সন্তান চাই",
        ja="子どもをほしいです", ko="자녀를 원해요", ar="أريد أطفالاً",
        sw="Nataka watoto", ha="Ina son yaro",
        am="ልጆች እፈልጋለሁ", tl="Gusto ko ng anak",
        ms="Saya mahukan anak", mi="Ka hiahia tamariki",
    ),
    text(
        "family.option.wants_children.desc", 91,
        es="Tienes la intención de formar una familia en el futuro.",
        en="You intend to start a family in the future.",
        pt="Você pretende formar uma família no futuro.",
        fr="Vous avez l'intention de fonder une famille à l'avenir.",
        de="Sie möchten irgendwann eine Familie gründen.",
        it="Intendi formare una famiglia in futuro.",
        ru="Вы планируете создать семью в будущем.",
        sv="Du planerar att bilda en familj i framtiden.",
        nl="Je van plan om in de toekomst een gezin te stichten.",
        zh="你打算在未来组建家庭。",
        hi="आप भविष्य में परिवार बनाना चाहते हैं।",
        bn="আপনি ভবিষ্যতে পরিবার গড়তে চান।",
        ja="将来家族をもつ予定です。",
        ko="앞으로 가정을 이루고 싶습니다.",
        ar="تنوي تكوين أسرة في المستقبل.",
        sw="Unatarajia kuanzisha familia baadaye.",
        ha="Kana yi shakka yin za ƙirƙira iyali a ba na biyo.",
        am="በወደቀድ ቤተሰብል መመጣት ይፈልጋለህ።",
        tl="Nakatimbal na magkaroon ng pamilya sa hinaharap.",
        ms="Anda berhasrat untuk membina keluarga pada masa hadapan.",
        mi="Ke whakawhananga koe i te whānau i te ra e haere ake nei.",
    ),
    text(
        "family.option.does_not_want_children.label", 92,
        es="No quiero hijos", en="I don't want children",
        pt="Não quero filhos", fr="Je ne veux pas d'enfants",
        de="Ich möchte keine Kinder", it="Non voglio figli",
        ru="Не хочу детей", sv="Jag vill inte ha barn",
        nl="Ik wil geen kinderen",
        zh="我不想要孩子", hi="मैं बच्चे नहीं चाहता/चाहती", bn="আমি সন্তান চাই না",
        ja="子どもはほしくないです", ko="자녀는 원하지 않아요",
        ar="لا أريد أطفالاً",
        sw="Sitaki watoto", ha="Ban son yaro",
        am="ልጆችን አይፈልግምም",
        tl="Hindi ko gustong magkaroon ng anak",
        ms="Saya tidak mahukan anak", mi="Kāore au e hiahia tamariki",
    ),
    text(
        "family.option.does_not_want_children.desc", 93,
        es="Has decidido no tener hijos en tu proyecto de vida.",
        en="You have decided not to have children in your life plan.",
        pt="Você decidiu não ter filhos no seu projeto de vida.",
        fr="Vous avez décidé de ne pas avoir d'enfants dans votre projet de vie.",
        de="Sie haben sich entschieden, keine Kinder zu bekommen.",
        it="Hai deciso di non avere figli nel tuo progetto di vita.",
        ru="Вы решили не заводить детей в своём жизненном плане.",
        sv="Du har bestämt att inte få barn i din livsplan.",
        nl="Je hebt besloten geen kinderen te krijgen in je levensplan.",
        zh="在你的生活规划中，你决定不要孩子。",
        hi="आपने अपनी जीवन योजना में बच्चे न होने का निर्णय लिया है।",
        bn="আপনি আপনার জীবন পরিকল্পনায় সন্তান না রাখার সিদ্ধান্ত নিয়েছেন।",
        ja="人生計画の中で子どもを持たないことを決めています。",
        ko="삶의 계획에서 자녀를 갖지 않기로 결정했습니다.",
        ar="لقد قررت عدم إنجاب الأطفال في مشروع حياتك.",
        sw="Umeamua kutotoa watoto katika mpango wako wa maisha.",
        ha="Ka yanke ba za ka yi da yaro a cikin tsarin rayuwarka.",
        am="በየእርስህ ዕቅድ ልጆችን አለመካት መምረጥሀህ።",
        tl="Nagpasya kang hindi magkakaroon ng anak sa iyong plano sa buhay.",
        ms="Anda memutuskan untuk tidak mempunyai anak dalam rancangan hidup anda.",
        mi="Kua whakatau koe kore whai tamariki i tō mahere oranga.",
    ),
    text(
        "family.option.has_children_wants_more.label", 94,
        es="Ya tengo hijos y quiero más",
        en="I already have children and want more",
        pt="Já tenho filhos e quero mais",
        fr="J'ai déjà des enfants et j'en veux plus",
        de="Ich habe bereits Kinder und möchte mehr",
        it="Ho già dei figli e ne voglio altri",
        ru="У меня уже есть дети, и я хочу ещё",
        sv="Jag har redan barn och vill ha fler",
        nl="Ik heb al kinderen en wil er meer",
        zh="我已有孩子，还想要更多",
        hi="मेरे पहले से बच्चे हैं और मैं और चाहता/चाहती हूं",
        bn="আমার ইতিমধ্যে সন্তান আছে এবং আরও চাই",
        ja="子どもがいてさらにほしいです",
        ko="이미 자녀가 있고 더 원해요",
        ar="لدي أطفال بالفعل وأريد المزيد",
        sw="Nina watoto tayari na nataka zaidi",
        ha="Ina da yaro da kuma ina son karfi",
        am="ልጆች አሉኝ ከዚያ ተጨማሪ እፈልጋለሁ",
        tl="Mayroon na akong anak at gusto ko pa",
        ms="Saya sudah mempunyai anak dan mahukan lagi",
        mi="Kua whai tamariki koe, ka hiahia ano",
    ),
    text(
        "family.option.has_children_wants_more.desc", 95,
        es="Eres padre/madre y estás abierto/a a tener más hijos.",
        en="You are a parent and you are open to having more children.",
        pt="Você é pai/mãe e está aberto a ter mais filhos.",
        fr="Vous êtes parent et ouvert à avoir d'autres enfants.",
        de="Sie sind Elternteil und offen für weitere Kinder.",
        it="Sei un genitore e sei aperto ad avere altri figli.",
        ru="Вы родитель и готовы завести ещё детей.",
        sv="Du är förälder och öppen för fler barn.",
        nl="Je bent ouder en staat open voor meer kinderen.",
        zh="你是家长，并愿意再要孩子。",
        hi="आप माता/पिता हैं और अधिक बच्चों के लिए खुले हैं।",
        bn="আপনি অভিভাবক এবং আরও সন্তানের জন্য প্রস্তুত।",
        ja="子どもがいる親として、さらに増やしたいです。",
        ko="부모이며 더 많은 자녀를 원합니다",
        ar="أنت أب/أم ومستعد لإنجاب المزيد.",
        sw="Wewe ni mzazi na uko tayari kwa watoto zaidi.",
        ha="Kana iyali kuma kana buɗe don ƙara yaro.",
        am="ወላጆች አለዎት፣ ተጨማሪ ልጆችንም ለመግባት ተስማሚ ነህ።",
        tl="Ikaw ay isang magulang at bukas sa pagkakaroon ng higit pang anak.",
        ms="Anda adalah ibu/bapa dan terbuka untuk mempunyai anak lagi.",
        mi="He whāonga koe, ā ke tuwhera ana kia whai tamariki anō.",
    ),
    text(
        "family.option.has_children_no_more.label", 96,
        es="Ya tengo hijos y no quiero más",
        en="I already have children and do not want more",
        pt="Já tenho filhos e não quero mais",
        fr="J'ai déjà des enfants et je n'en veux pas d'autres",
        de="Ich habe bereits Kinder und möchte keine mehr",
        it="Ho già dei figli e non ne voglio altri",
        ru="У меня уже есть дети, и я не хочу ещё",
        sv="Jag har redan barn och vill inte ha fler",
        nl="Ik heb al kinderen en wil er geen meer",
        zh="我已有孩子，不要更多了",
        hi="मेरे पहले से बच्चे हैं और मैं और नहीं चाहता/चाहती",
        bn="আমার ইতিমধ্যে সন্তান আছে এবং আর চাই না",
        ja="子どもがおり、これ以上ほしくないです",
        ko="이미 자녀가 있고 더 원하지 않아요",
        ar="لدي أطفال ولا أريد المزيد",
        sw="Nina watoto tayari sitaki zaidi",
        ha="Ina da yaro, ba son karfi",
        am="ልጆች አሉኝ ከዚያም አላለፍምም",
        tl="Mayroon na akong anak at ayoko na sa higit pa",
        ms="Saya sudah mempunyai anak dan tidak mahukan lagi",
        mi="Kua whai tamariki koe, kaore e hiahia ano",
    ),
    text(
        "family.option.has_children_no_more.desc", 97,
        es="Eres padre/madre y tu familia está completa.",
        en="You are a parent and your family is complete.",
        pt="Você é pai/mãe e sua família está completa.",
        fr="Vous êtes parent et votre famille est complète.",
        de="Sie sind Elternteil und Ihre Familie ist vollständig.",
        it="Sei un genitore e la tua famiglia è completa.",
        ru="Вы родитель, и ваша семья полна.",
        sv="Du är förälder och din familj är komplett.",
        nl="Je bent ouder en je gezin is compleet.",
        zh="你是家长，你的家庭已经完整。",
        hi="आप माता/पिता हैं और आपका परिवार पूर्ण है।",
        bn="আপনি অভিভাবক এবং আপনার পরিবার পূর্ণ।",
        ja="子どもがいる親で、家族は完成しています。",
        ko="부모이며 가족이 완성되었습니다.",
        ar="أنت أب/أم وعائلتك مكتملة.",
        sw="Wewe ni mzazi na familia yako imekamilika.",
        ha="Kana iyali kuma iyalinka cika cikali.",
        am="ወላጆች አለዎት፣ ቤተሰብልህም ተሟል ነው።",
        tl="Ikaw ay isang magulang at kumpleto na ang iyong pamilya.",
        ms="Anda adalah ibu/bapa dan keluarga anda sudah lengkap.",
        mi="He whāonga koe, ā kua tino katoa tōu whānau.",
    ),
    text(
        "family.option.undecided.label", 98,
        es="Aún no lo sé", en="I am not sure yet",
        pt="Ainda não sei", fr="Je ne sais pas encore",
        de="Ich weiß es noch nicht", it="Non lo so ancora",
        ru="Пока не знаю", sv="Jag vet inte än", nl="Ik weet het nog niet",
        zh="我还不确定", hi="मुझे अभी पता नहीं", bn="আমি এখনো জানি না",
        ja="まだわかりません", ko="아직 모르겠어요", ar="لست متأكدًا بعد",
        sw="Bado sijui", ha="Ban sani ba",
        am="እስካሁን አላወቅኩም", tl="Hindi ko alam pa",
        ms="Saya belum tahu", mi="Kāore anō ahau e mōhio",
    ),
    text(
        "family.option.undecided.desc", 99,
        es="Todavía estás reflexionando sobre este tema.",
        en="You are still reflecting on this topic.",
        pt="Você ainda está refletindo sobre este tema.",
        fr="Vous réfléchissez encore à ce sujet.",
        de="Sie reflektieren noch über dieses Thema.",
        it="Stai ancora riflettendo su questo tema.",
        ru="Вы всё ещё размышляете об этом.",
        sv="Du funderar fortfarande på detta ämne.",
        nl="Je nadenkt nog na over dit onderwerp.",
        zh="你仍在思考这个问题。",
        hi="आप अभी भी इस विषय पर विचार कर रहे हैं।",
        bn="আপনি এখনো এই বিষয়ে ভাবছেন।",
        ja="まだこのテーマについて考えています。",
        ko="아직 이 주제에 대해 생각하고 있습니다.",
        ar="لا تزال تفكر في هذا الموضوع.",
        sw="Bado unafikiri kuhusu mada hii.",
        ha="Kana har yana tunani wannan batun.",
        am="እስካሁን በዚህ ርዕስ ላይ እየገለግሉ ነዎት።",
        tl="Iniisip mo pa ang paksa na ito.",
        ms="Anda masih merenung tentang topik ini.",
        mi="Ka mahi tonu koe e whakaaro mō tēnei kaupapa.",
    ),
    text(
        "family.childAccept.accepts.label", 100,
        es="Sí, no tengo problema", en="Yes, no problem",
        pt="Sim, sem problema", fr="Oui, pas de problème",
        de="Ja, kein Problem", it="Sì, nessun problema",
        ru="Да, без проблем", sv="Ja, inget problem",
        nl="Ja, geen probleem",
        zh="没问题", hi="हाँ, कोई समस्या नहीं", bn="হ্যাঁ, সমস্যা নেই",
        ja="問題ありません", ko="네, 문제없어요",
        ar="نعم، لا مشكلة",
        sw="Ndiyo, hakuna tatizo", ha="Eh, babu matsala",
        am="አዎ፣ ችግር የለም", tl="Oo, walang problema",
        ms="Ya, tiada masalah", mi="Ā, kāore rongo",
    ),
    text(
        "family.childAccept.accepts.desc", 101,
        es="Estás abierto/a a conectar con personas que ya tengan hijos.",
        en="You are open to connecting with people who already have children.",
        pt="Você está aberto a conectar com pessoas que já tenham filhos.",
        fr="Vous êtes ouvert à rencontrer des personnes qui ont déjà des enfants.",
        de="Sie sind offen für Verbindungen mit Menschen, die bereits Kinder haben.",
        it="Sei aperto a connetterti con chi ha già dei figli.",
        ru="Вы готовы общаться с людьми, у которых уже есть дети.",
        sv="Du är öppen för kontakter med personer som redan har barn.",
        nl="Je staat open voor verbindingen met mensen die al kinderen hebben.",
        zh="你愿意与已有孩子的人建立联结。",
        hi="आप उन लोगों से जुड़ना चाहते हैं जिनके पहले से बच्चे हैं।",
        bn="আপনি এমন ব্যক্তিদের সাথে সংযুক্ত হতে উন্মুক্ত যাদের সন্তান আছে।",
        ja="子どもがいる人とつながることに協力的です。",
        ko="이미 자녀가 있는 사람들과 연결하는 데 열려 있습니다.",
        ar="أنت منفتح على التواصل مع أشخاص لديهم أطفال بالفعل.",
        sw="Umeweka kuwa tayari kuunganisha na watu wenye watoto tayari.",
        ha="Ka buɗe kowane gani da mutane da ke da yaro.",
        am="ልጆች ያላቸው ሰዎች ጋር እንደመገናኘት ተስማሚ ነዎት።",
        tl="Handa ka makipag-ugnayan sa mga taong may anak na.",
        ms="Anda terbuka untuk berhubung dengan mereka yang sudah mempunyai anak.",
        mi="Ka tuwhera ana koe ki te here ki te hunga kua whai tamariki nei.",
    ),
    text(
        "family.childAccept.depends.label", 102,
        es="Depende del contexto", en="Depends on the context",
        pt="Depende do contexto", fr="Dépend du contexte",
        de="Kontextabhängig", it="Dipende dal contesto",
        ru="Зависит от ситуации", sv="Beror på sammanhang",
        nl="Contextafhankelijk",
        zh="视情况而定", hi="परिस्थिति पर निर्भर", bn="পরিস্থিতির উপর নির্ভর করে",
        ja="状況によります", ko="상황에 따라 달라요", ar="حسب السياق",
        sw="Inategemea hali", ha="Ya doge ne",
        am="ሁኔታውን ያስቀምጣል", tl="Nakadepende sa konteksto",
        ms="Bergantung pada konteks", mi="Ka whakatau ki te taunga",
    ),
    text(
        "family.childAccept.depends.desc", 103,
        es="Evaluarías caso por caso según la situación.",
        en="You would assess it case by case depending on the situation.",
        pt="Você avaliaria caso a caso conforme a situação.",
        fr="Vous l'évalueriez au cas par cas selon la situation.",
        de="Sie würden je nach Situation von Fall zu Fall entscheiden.",
        it="Valuteresti caso per caso a seconda della situazione.",
        ru="Вы бы оценивали это в каждом конкретном случае.",
        sv="Du skulle bedöma det fall för fall beroende på situationen.",
        nl="Je zou het per geval beoordelen, afhankelijk van de situatie.",
        zh="你会根据具体情况逐一评估。",
        hi="आप स्थिति के अनुसार हर मामले पर अलग से निर्णय लेंगे।",
        bn="আপনি পরিস্থিতি অনুযায়ী প্রতিটি ক্ষেত্রে আলাদাভাবে বিচার করবেন।",
        ja="状況に応じて一つずつ判断します。",
        ko="상황에 따라 각 경우를 따로 판단하실 것입니다.",
        ar="ستقيّم الحالة حالة حسب الموقف.",
        sw="Ungependa kutathmini kila hali kwa kujitegemea.",
        ha="Za ka gwada kowane lokaci gwanda.",
        am="እንደሁኔታው በየየየት ይገምገማሉ።",
        tl="Sususuriin mo ito ayon sa bawat sitwasyon.",
        ms="Anda akan menilai setiap kes berdasarkan situasi.",
        mi="Ka whakawari koe mō ia.take i runga i te taunga.",
    ),
    text(
        "family.childAccept.no_acceptance.label", 104,
        es="No, prefiero que no tenga hijos",
        en="No, I prefer they do not have children",
        pt="Não, prefiro que não tenha filhos",
        fr="Non, je préfère qu'ils n'aient pas d'enfants",
        de="Nein, ich bevorzuge ohne Kinder",
        it="No, preferisco che non abbia figli",
        ru="Нет, предпочитаю без детей",
        sv="Nej, jag föredrar utan barn",
        nl="Nee, ik prefereer zonder kinderen",
        zh="不，我更希望对方没有孩子",
        hi="नहीं, मैं बिना बच्चों को पसंद करता/करती हूं",
        bn="না, আমি বিনা সন্তান পছন্দ করি",
        ja="いいえ、子どもがいない人を希望します",
        ko="아니요, 자녀가 없는 분을 선호해요",
        ar="لا، أفضّل ألا يكون لديه أطفال",
        sw="Hapana, napenda bila watoto", ha="A'a, ina son kuma babu yaro",
        am="አይደለም፣ ልጆች የማይኖሩትን እፈልጋለሁ",
        tl="Hindi, mas gusto ko ang walang anak",
        ms="Tidak, saya lebih suka tanpa anak",
        mi="Kāore, ka hiahia koe kia rerehua te tangata kāore he tamariki",
    ),
    text(
        "family.childAccept.no_acceptance.desc", 105,
        es="Prefieres conectar con personas sin hijos.",
        en="You prefer connecting with people without children.",
        pt="Você prefere conectar com pessoas sem filhos.",
        fr="Vous préférez rencontrer des personnes sans enfants.",
        de="Sie bevorzugen Verbindungen zu Menschen ohne Kinder.",
        it="Preferisci connetterti con chi non ha figli.",
        ru="Вы предпочитаете общаться с теми, у кого нет детей.",
        sv="Du föredrar kontakter med personer utan barn.",
        nl="Je verbindt je liever met mensen zonder kinderen.",
        zh="你更愿意与没有孩子的人建立联结。",
        hi="आप बिना बच्चों वाले लोगों से जुड़ना पसंद करते हैं।",
        bn="আপনি বিনা সন্তানের ব্যক্তিদের সাথে সংযুক্ত হতে পছন্দ করেন।",
        ja="子どもがいない人とつながることを希望します。",
        ko="자녀가 없는 사람과 연결하는 것을 선호합니다.",
        ar="تفضّل التواصل مع أشخاص ليس لديهم أطفال.",
        sw="Unapenda kuunganisha na watu bila watoto.",
        ha="Kana son sani da mutane da babu yaro.",
        am="ያለ ልጆች ሰዎችን ለመገናኘት ይፈልጋለህ።",
        tl="Mas gusto mo ang mga taong walang anak.",
        ms="Anda lebih suka berhubung dengan mereka yang tiada anak.",
        mi="Ka hiahia koe ki te here ki te hunga kāore anō he tamariki.",
    ),
]