"""UI texts for the "Tu Estatura" (Height) subsection."""

from .common import text

TEXTS = [
    text(
        "height.title", 10,
        es="Tu Estatura", en="Your Height",
        pt="Sua Altura", fr="Votre Taille",
        de="Ihre Größe", it="La tua Altezza",
        ru="Ваш рост", sv="Din Längd", nl="Je Lengte",
        zh="你的身高", hi="आपका कद", bn="আপনার উচ্চতা",
        ja="身長", ko="키", ar="طولك",
        sw="Urefu wako", ha="Tsaadarinka", am="ብራት", tl="Ang iyong taas",
        ms="Tinggi anda", mi="Te tōpūtanga",
    ),
    text(
        "height.label", 11,
        es="Tu Altura", en="Your Height",
        pt="Sua Altura", fr="Votre Taille",
        de="Ihre Größe", it="La tua Altezza",
        ru="Ваш рост", sv="Din längd", nl="Je lengte",
        zh="你的身高", hi="आपकी ऊँचाई", bn="আপনার উচ্চতা",
        ja="身長", ko="키", ar="الطول",
        sw="Urefu wako", ha="Tsaadarinka", am="ብራት", tl="Ang iyong taas",
        ms="Tinggi anda", mi="Te tōpūtanga",
    ),
    text(
        "height.placeholder", 12,
        es="Ej: 170", en="E.g.: 170",
        pt="Ex.: 170", fr="Ex. : 170",
        de="Z. B.: 170", it="Es.: 170",
        ru="Например: 170", sv="T.ex.: 170", nl="Bijv.: 170",
        zh="例如：170", hi="उदा.: 170", bn="যেমন: 170",
        ja="例: 170", ko="예: 170", ar="مثال: 170",
        sw="K.m.: 170", ha="Misali: 170", am="ምሳሌ: 170", tl="Hal.: 170",
        ms="Cthn.: 170", mi="Tē taiao: 170",
    ),
    text(
        "height.helper", 13,
        es="Tu altura se mostrará en tu perfil si lo deseas.",
        en="Your height will be shown on your profile if you want.",
        pt="Sua altura será exibida no seu perfil se você quiser.",
        fr="Votre taille sera affichée sur votre profil si vous le souhaitez.",
        de="Ihre Größe wird in Ihrem Profil angezeigt, wenn Sie möchten.",
        it="La tua altezza verrà mostrata sul tuo profilo se lo desideri.",
        ru="Ваш рост будет показан в профиле, если вы этого захотите.",
        sv="Din längd visas i din profil om du vill.",
        nl="Je lengte wordt op je profiel getoond als je dat wilt.",
        zh="如果你愿意，你的身高将显示在资料中。",
        hi="यदि आप चाहें तो आपका कद आपकी प्रोफ़ाइल में दिखाया जाएगा।",
        bn="চাইলে আপনার উচ্চতা আপনার প্রোফাইলে দেখানো হবে।",
        ja="希望すれば身長はプロフィールに表示されます。",
        ko="원하시면 키가 프로필에 표시됩니다.",
        ar="سيُعرض طولك في ملفك الشخصي إن رغبت.",
        sw="Urefu wako utaonyeshwa kwenye wasifu yako ukitaka.",
        ha="Za a cika tsaadarinka a nuna ba tare da idan kana so.",
        am="ከፈለግኝ ብራትህ በመገለጫዎ ውስጥ ይታያል።",
        tl="Ipapakita ang iyong taas sa iyong profile kung gusto mo.",
        ms="Tinggi anda akan dipaparkan pada profil anda jika anda mahu.",
        mi="Ka whakaatu tō te tōpūtanga ki tōua kōtuitanga mā te hiahia.",
    ),
    text(
        "height.relevantLabel", 14,
        es="¿Quieres que la estatura influya en tu compatibilidad?",
        en="Do you want height to influence your compatibility?",
        pt="Você quer que a altura influencie sua compatibilidade?",
        fr="Souhaitez-vous que la taille influence votre compatibilité ?",
        de="Soll Ihre Größe Ihre Kompatibilität beeinflussen?",
        it="Vuoi che l'altezza influenzi la tua compatibilità?",
        ru="Хотите, чтобы рост влиял на вашу совместимость?",
        sv="Vill du att din längd påverkar din kompatibilitet?",
        nl="Wil je dat je lengte je compatibiliteit beïnvloedt?",
        zh="你希望身高影响你的匹配度吗？",
        hi="क्या आप चाहते हैं कि आपका कद आपकी अनुकूलता को प्रभावित करे?",
        bn="আপনি কি চান যে আপনার উচ্চতা আপনার সামঞ্জস্যতাকে প্রভাবিত করুক?",
        ja="身長をマッチの考慮に入れたいですか？",
        ko="키가 당신의 궁합에 영향을 주기를 원하시나요?",
        ar="هل تريد أن يؤثر طولك على توافقك؟",
        sw="Ungependa kwamba urefu wako unaathirini uoendana wako?",
        ha="Kana sona cewa tsaadarinka ta yi daɗawa da mutammaninka?",
        am="ብራትህ ማስማሚነትህን እንወስድ ያስገንድህ?",
        tl="Gusto mo bang ang iyong taas ay makapagpabago sa compatibility mo?",
        ms="Adakah anda mahu tinggi mempengaruhi keserasian anda?",
        mi="E hiahia ana koe kia whakatau kōtū te tōpūtanga?",
    ),
    text(
        "height.relevantTooltip", 15,
        es="Los rangos se adaptan a tu país. Puedes elegir lo que te atrae sin preocuparte por etiquetas.",
        en="Ranges adapt to your country. You can choose what appeals to you without worrying about labels.",
        pt="As faixas se adaptam ao seu país. Você pode escolher o que te atrai sem se preocupar com rótulos.",
        fr="Les plages s'adaptent à votre pays. Vous pouvez choisir ce qui vous attire sans vous soucier des étiquettes.",
        de="Die Bereiche passen sich Ihrem Land an. Sie können wählen, was Sie anzieht, ohne auf Bezeichnungen zu achten.",
        it="Le fasce si adattano al tuo paese. Puoi scegliere ciò che ti attira senza preoccuparti delle etichette.",
        ru="Диапазоны адаптируются к вашей стране. Вы можете выбрать то, что вам нравится, не думая о ярлыках.",
        sv="Intervallen anpassas efter ditt land. Du kan välja vad som tilltalar dig utan att bry dig om etiketter.",
        nl="De bereiken passen zich aan je land aan. Je kunt kiezen wat je aantrekt zonder je druk te maken over labels.",
        zh="范围会根据你所在的国家调整。你可以选择吸引你的类型，无需在意标签。",
        hi="रेंज आपके देश के अनुसार समायोजित होती हैं। आप लेबल की चिंता किए बिना जो आकर्षक लगे वह चुन सकते हैं।",
        bn="পরিসর আপনার দেশ অনুযায়ী মানিয়ে নেওয়া হয়। লেবেল নিয়ে চিন্তা না করে আপনি যা পছন্দ তা বেছে নিতে পারেন।",
        ja="範囲は国に合わせて調整されます。ラベルを気にせず、惹かれるものを選べます。",
        ko="범위는 국가에 맞게 조정됩니다. 라벨을 신경 쓰지 않고 끌리는 대로 선택할 수 있습니다.",
        ar="تتكيف النطاقات مع بلدك. يمكنك اختيار ما يجذبك دون الانشغال بالمسميات.",
        sw="Masafa hubadilishwa kwa nchi yako. Unaweza kuchagua kinachokuvutia bila kujali majina.",
        ha="Ƙayyooda suna daidaita da ƙasarka. Za ka iya zaɓi abin da kake ɗauke hankali ba tare da damar alamar kowane abu.",
        am="ክልሎቹ ከሀገርህ ጋር ይስማማሉ። መለያዎችን ሳትጨምር የሚያስቀርህን መምረጥ ትችላለህ።",
        tl="Iniaangkop sa bansa mo. Maaari kang pumili ng nakagandahan sa iyo nang hindi nag-aalala sa mga label.",
        ms="Julat disesuaikan dengan negara anda. Anda boleh memilih apa yang menarik tanpa melihat label.",
        mi="Ka whakaritea nga awa ki tō whenua. Ka taea e koe te kōwhiri i te mea e tino ana ki aoe, me te wareware ki ngā ingoa.",
    ),
    text(
        "height.prefsTitle", 16,
        es="¿Qué estaturas te atraen?", en="What heights appeal to you?",
        pt="Que alturas te atraem?", fr="Quelles tailles vous attirent ?",
        de="Welche Größen sprechen Sie an?", it="Quali altezze ti attirano?",
        ru="Какой рост вас привлекает?", sv="Vilka längder tilltalar dig?",
        nl="Welke lengtes spreken je aan?", zh="什么身高吸引你？",
        hi="कौन-सा कद आपको आकर्षित करता है?", bn="কোন উচ্চতা আপনাকে আকর্ষণ করে?",
        ja="どのような身長に惹かれますか？", ko="어떤 키가 끌리나요?", ar="أي طول يجذبك؟",
        sw="Urefu gani unauvutia?", ha="Ƙin tsaadarinka ke ɗauke hankali?",
        am="ትክክል ብራት ብራስህን ያስቀስብልሃል?",
        tl="Anong taas ang kinasabihan mo?", ms="Tinggi mana yang menarik perhatian anda?",
        mi="He aha te tōpūtanga e tino ana ki aou?",
    ),
    text(
        "height.inRegion", 17,
        es="en tu región.", en="in your region.",
        pt="na sua região.", fr="dans votre région.",
        de="in Ihrer Region.", it="nella tua regione.",
        ru="в вашем регионе.", sv="i din region.", nl="in je regio.",
        zh="在你的地区。", hi="आपके क्षेत्र में।", bn="আপনার অঞ্চলে।",
        ja="あなたの地域で。", ko="당신의 지역에서.", ar="في منطقتك.",
        sw="katika eneo lako.", ha="a cikin yankinka.", am="በክልልህ ውስጥ።",
        tl="sa rehiyong mo.", ms="di wilayah anda.", mi="i tō rohe.",
    ),
    text(
        "height.disabled", 18,
        es="Preferencia desactivada", en="Preference disabled",
        pt="Preferência desativada", fr="Préférence désactivée",
        de="Einstellung deaktiviert", it="Preferenza disattivata",
        ru="Настройка отключена", sv="Inställning avstängd", nl="Voorkeur uitgeschakeld",
        zh="偏好已关闭", hi="प्राथमिकता बंद है", bn="পছন্দ বন্ধ করা আছে",
        ja="この設定は無効です", ko="선호가 꺼져 있습니다", ar="تم تعطيل التفضيل",
        sw="Mapendeleo yamezimwa", ha="Za a kashe zaɗi", am="ቅንብር ጠፍቷል",
        tl="Naka-off ang preference", ms="Keutamaan dinyahikan",
        mi="Kua kore whiringa",
    ),
    text(
        "height.quoteOn", 19,
        es="“La estatura es solo un dato. Tu esencia es lo que buscamos.”",
        en="“Height is just a detail. What we look for is your essence.”",
        pt="“A altura é apenas um dado. O que buscamos é a sua essência.”",
        fr="“La taille n'est qu'une donnée. C'est votre essence que nous recherchons.”",
        de="„Die Größe ist nur ein Datum. Wir suchen Ihre Wesensart.“",
        it="“L'altezza è solo un dato. Cerchiamo la tua essenza.”",
        ru="«Рост — это лишь деталь. Мы ищем вашу суть.»",
        sv="”Längden är bara en uppgift. Det är din kärna vi söker.”",
        nl="“Lengte is slechts een gegeven. Wat we zoeken is jouw essentie.”",
        zh="“身高只是一个数据。我们寻找的是你的本质。”",
        hi="“कद तो बस एक जानकारी है। हम आपकी असली पहचान खोजते हैं।",
        bn="“উচ্চতা কেবল একটি তথ্য। আমরা আপনার মূল পরিচয় খুঁজি।”",
        ja="“身長はただ一つのデータです。私たちが求めるのはあなたの本質です。”",
        ko="“키는 그저 하나의 정보일 뿐입니다. 우리가 찾는 것은 당신의 본질입니다.”",
        ar="“الطول مجرّد رقم. ما نبحث عنه هو جوهرك.”",
        sw="“Urefu ni taarifa tu. Tunachotafika asili yako.”",
        ha="“Tsaadarinka ce kawai. Ainihinka ne kuma mu nema.”",
        am="“ብራት በመጠን ላይ ብቻ ነው። አካልህን እንፈልጋለን።”",
        tl="“Ang taas ay datos lamang. Hinahanap namin ang tunay mong pagkatao.”",
        ms="“Tinggi hanyalah satu maklumat. Yang kami cari ialah esen anda.”",
        mi="“He māramatanga te tōpūtanga. Ka e rapu ana mātou i tōu mauri.”",
    ),
    text(
        "height.quoteOff", 20,
        es="“La estatura no influirá en tu compatibilidad.”",
        en="“Height will not influence your compatibility.”",
        pt="“A altura não influenciará sua compatibilidade.”",
        fr="“La taille n'influencera pas votre compatibilité.”",
        de="„Die Größe wird Ihre Kompatibilität nicht beeinflussen.“",
        it="“L'altezza non influenzerà la tua compatibilità.”",
        ru="«Рост не будет влиять на вашу совместимость.»",
        sv="”Längden kommer inte att påverka din kompatibilitet.”",
        nl="“Lengte zal je compatibiliteit niet beïnvloeden.”",
        zh="“身高将不会影响你的匹配度。”",
        hi="“कद आपकी अनुकूलता को नहीं प्रभावित करेगा।”",
        bn="“উচ্চতা আপনার সামঞ্জস্যতায় প্রভাব ফেলবে না।”",
        ja="“身長はあなたのマッチに影響しません。”",
        ko="“키는 당신의 궁합에 영향을 주지 않습니다.”",
        ar="“لن يؤثر طولك على توافقك.”",
        sw="“Urefu hautathirini kwenye uoendana wako.”",
        ha="“Tsaadarinka ba ta yi daɗawa da mutammaninka.”",
        am="“ብራት ማስማሚነትህን አይጎዳም።”",
        tl="“Hindi maaaring maging impluwensya ang taas sa compatibility mo.”",
        ms="“Tinggi tidak akan mempengaruhi keserasian anda.”",
        mi="“Kāore te tōpūtanga e pāngai tō te whakatau kōtū.”",
    ),
    text(
        "height.pref.short", 21,
        es="Bajitos/as", en="Short",
        pt="Baixos/as", fr="Petits",
        de="Klein", it="Bassi",
        ru="Невысокие", sv="Korta", nl="Kort",
        zh="个子小的", hi="छोटे", bn="ছোট",
        ja="低め", ko="작은", ar="قصار",
        sw="Wafu", ha="Karami", am="ዝቅ", tl="Mababa",
        ms="Pendek", mi="Poto",
    ),
    text(
        "height.pref.average", 22,
        es="Promedio", en="Average",
        pt="Médio", fr="Moyen",
        de="Durchschnitt", it="Medio",
        ru="Средний", sv="Genomsnitt", nl="Gemiddeld",
        zh="中等", hi="औसत", bn="সাধারণ",
        ja="普通", ko="보통", ar="متوسط",
        sw="Wastani", ha="Al'ada", am="አጋራሽ", tl="Katamtaman",
        ms="Sederhana", mi="Wherawhera",
    ),
    text(
        "height.pref.tall", 23,
        es="Altos/as", en="Tall",
        pt="Altos/as", fr="Grands",
        de="Groß", it="Alti",
        ru="Высокие", sv="Långa", nl="Lang",
        zh="个子高的", hi="लंबे", bn="উঁচু",
        ja="高め", ko="큰", ar="طوال",
        sw="Warefu", ha="Karfi", am="ትልቅ", tl="Mataas",
        ms="Tinggi", mi="Roa",
    ),
    text(
        "height.pref.giant", 24,
        es="Muy altos/as", en="Very tall",
        pt="Muito altos/as", fr="Très grands",
        de="Sehr groß", it="Molto alti",
        ru="Очень высокие", sv="Mycket långa", nl="Zeer lang",
        zh="非常高的", hi="बहुत लंबे", bn="খুব উঁচু",
        ja="とても高め", ko="아주 큰", ar="طوال جدًا",
        sw="Warefu sana", ha="Karfi sosai", am="በጣም ትልቅ", tl="Napaka-mataas",
        ms="Sangat tinggi", mi="Tino roa",
    ),
    text(
        "height.pref.none", 25,
        es="Todas las alturas", en="All heights",
        pt="Todas as alturas", fr="Toutes les tailles",
        de="Alle Größen", it="Tutte le altezze",
        ru="Любой рост", sv="Alla längder", nl="Alle lengtes",
        zh="所有身高", hi="सभी कद", bn="সব উচ্চতা",
        ja="すべての身長", ko="모든 키", ar="جميع الطول",
        sw="Urefu wowote", ha="Kowane tsaadarinka", am="ሁሉም ብራት", tl="Lahat ng taas",
        ms="Semua tinggi", mi="Nga katoa te tōpūtanga",
    ),
]