"""UI texts for the "Lenguaje del amor" (Love Language) subsection."""

from .common import text

TEXTS = [
    text(
        "love.title", 140,
        es="Lenguaje del amor", en="Love language",
        pt="Linguagem do amor", fr="Langage de l'amour",
        de="Liebes Sprache", it="Linguaggio dell'amore",
        ru="Язык любви", sv="Kärlekens språk", nl="Taal van de liefde",
        zh="爱的语言", hi="प्रेम की भाषा", bn="ভালোবাসার ভাষা",
        ja="ラブの言葉", ko="사랑의 언어", ar="لغة الحب",
        sw="Lugha ya upendo", ha="Harshe ta ƙauna",
        am="የፍቅርት ቋንቋ", tl="Wika ng pagmamahal",
        ms="Bahasa cinta", mi="Te reo o te aroha",
    ),
    text(
        "love.question", 141,
        es="¿Cómo das y recibes afecto?",
        en="How do you give and receive affection?",
        pt="Como você dá e recebe afeto?",
        fr="Comment donnez-vous et recevez-vous de l'affection ?",
        de="Wie geben und empfangen Sie Zuneigung?",
        it="Come dai e ricevi affetto?",
        ru="Как вы дарите и принимаете нежность?",
        sv="Hur ger och tar du emot kärlek?",
        nl="Hoe geef en ontvang je affectie?",
        zh="你如何给予和接收爱意？",
        hi="आप प्यार कैसे देते और पाते हैं?",
        bn="আপনি কীভাবে ভালোবাসা দেন এবং পান?",
        ja="あなたはどのように愛を表現しますか？",
        ko="어떻게 애정을 주고받으시나요?",
        ar="كيف تمنح الحب وتستقبله؟",
        sw="Unapenda jinsi kunavyotumia na kupokea upendo?",
        ha="Kana bai da kuma karɗi ƙauna?",
        am="ፍቅርትን እንዴት ይሰጣሉህና ይቀበላለህ?",
        tl="Paano mo ibinibigay at tinatanggap ang pagmamahal?",
        ms="Bagaimana anda memberi dan menerima kasih saying?",
        mi="Me pēhea koe e hoatu ai, e riro ai i te aroha?",
    ),
    text(
        "love.whyTitle", 142,
        es="¿Por qué es importante definir el lenguaje del amor?",
        en="Why is it important to define your love language?",
        pt="Por que é importante definir a linguagem do amor?",
        fr="Pourquoi est-il important de définir le langage de l'amour ?",
        de="Warum ist es wichtig, die Liebes Sprache zu definieren?",
        it="Perché è importante definire il linguaggio dell'amore?",
        ru="Почему важно определить язык любви?",
        sv="Varför är det viktigt att definiera kärlekens språk?",
        nl="Waarom is het belangrijk je taal van de liefde te bepalen?",
        zh="为什么定义爱的语言很重要？",
        hi="प्रेम की भाषा को परिभाषित करना क्यों महत्वपूर्ण है?",
        bn="ভালোবাসার ভাষা নির্ধারণ করা কেন গুরুত্বপূর্ণ?",
        ja="ラブの言葉を定義するのはなぜですか？",
        ko="사랑의 언어를 정의하는 것이 왜 중요한가요?",
        ar="لماذا من المهم تحديد لغة الحب؟",
        sw="Kwa nini ni muhimu kufafanua lugha ya upendo?",
        ha="Me ya sa ka muhimu tantanta harshe ta ƙauna?",
        am="የፍቅርት ቋንቋን መግለጽ ለምን አስፈላጊ ነው?",
        tl="Bakit mahalaga ang pag-define ng wika ng pagmamahal?",
        ms="Mengapa penting menentukan bahasa cinta anda?",
        mi="He aha i tino hiahia koe ki te whakatau i te reo o te aroha?",
    ),
    text(
        "love.why1", 143,
        es="Evita malentendidos afectivos",
        en="It avoids emotional misunderstandings",
        pt="Evita mal-entendidos afetivos",
        fr="Évite les malentendus affectifs",
        de="Vermeidet emotionales Missverständnis",
        it="Evita i fraintendimenti affettivi",
        ru="Предотвращает эмоциональные недопонимания",
        sv="Undviker känslomässiga missförstånd",
        nl="Voorkomt emotionele misverstanden",
        zh="避免情感误解",
        hi="भावनात्मक गलतफहमियों से बचाता है",
        bn="আবেগের ভুল বোঝাবুঝি এড়ায়",
        ja="気持ちのすれ違いを避ける",
        ko="감정적 오해를 피하게 합니다",
        ar="يتجنب سوء الفهم العاطفي",
        sw="Inapunguza misunderstanding za hisa",
        ha="Yana kuma fahimkar hujayi mai kuskure",
        am="የስሜት ማስረጃ ያስቀራርባል",
        tl="Pinipigilan ang mga maling pag-unawa sa damdamin",
        ms="Mengelakkan salah faham emosiional",
        mi="Ka waho i te rorenga o te māuiro",
    ),
    text(
        "love.why2", 144,
        es="Alinea formas de expresión emocional",
        en="It aligns ways of expressing emotion",
        pt="Alinha formas de expressão emocional",
        fr="Aligne les formes d'expression émotionnelle",
        de="Stimmt die Arten des emotionalen Ausdrucks ab",
        it="Allinea le forme di espressione emotiva",
        ru="Согласует способы выражения эмоций",
        sv="Justerar sätt att uttrycka känslor",
        nl="Stemt manieren om emoties te uiten af",
        zh="对齐情感表达方式",
        hi="भावनाओं को व्यक्त करने के तरीकों को मेल खाता है",
        bn="আবেগ প্রকাশের ধরন সমন্বয় করে",
        ja="気持ちを伝える方法をそろえる",
        ko="감정을 표현하는 방식을 맞춰줍니다",
        ar="يوائم طرائق التعبير عن المشاعر",
        sw="Inalingisha njia za kuelezea hisa",
        ha="Yana daidaita hanyoyin bayanai",
        am="የስሜት መግለጽ ዘዴዎችን ያስተካክላል",
        tl="Inii-align ang mga paraan ng pagpapahayag ng damdamin",
        ms="Menyelaraskan cara anda untuk menyampaikan emosi.",
        mi="Ka whakatau i ngā huarahi mō te whakaatu i te māuiro",
    ),
    text(
        "love.why3", 145,
        es="Refleja compatibilidad energética y emocional",
        en="It reflects energy and emotional compatibility",
        pt="Reflete a compatibilidade energética e emocional",
        fr="Reflète la compatibilité énergétique et émotionnelle",
        de="Spiegelt die Energie- und Gefühlskompatibilität wider",
        it="Riflette la compatibilità energetica ed emotiva",
        ru="Отражает энергетическую и эмоциональную совместимость",
        sv="Speglar energi- och känslokompatibilitet",
        nl="Weerspiegelt energie- en emotionele compatibiliteit",
        zh="体现能量与情感匹配度",
        hi="ऊर्जा और भावनात्मक अनुकूलता को दर्शाता है",
        bn="শক্তি ও আবেগের সামঞ্জস্য প্রতিফলিত করে",
        ja="気と心の相性を表す",
        ko="에너지와 감정의 궁합을 반영합니다",
        ar="يعكس التوافق الطاقي والعاطفي",
        sw="Inaakisi utayari wa nguvu na hisa",
        ha="Yana nuna mutane da kuma da zuciya",
        am="የኃይልና የስሜት ስምምነትን ያሳያል",
        tl="Ipinapakita ang pagkaangkop ng enerhiya at damdamin",
        ms="Mencerminkan keserasian tenaga dan emosi",
        mi="Ka whakaatu i te ōrite o te kaha me te māuiro",
    ),
    text(
        "love.why4", 146,
        es="CARE puede adaptar el tono del vínculo",
        en="CARE can adapt the tone of the bond",
        pt="O CARE pode adaptar o tom do vínculo",
        fr="CARE peut adapter le ton du lien",
        de="CARE kann den Ton der Verbindung anpassen",
        it="CARE può adattare il tono del legame",
        ru="CARE может адаптировать тон связи",
        sv="CARE kan anpassa relationens ton",
        nl="CARE kan de toon van de band aanpassen",
        zh="CARE 可以调节关系的基调",
        hi="CARE रिश्ते का स्वर समायोजित कर सकता है",
        bn="CARE সম্পর্কের সুর মানিয়ে নিতে পারে",
        ja="CARE は関係のトーンを調整できます",
        ko="CARE는 관계의 분위기를 조정할 수 있습니다",
        ar="يمكن لـ CARE تكييف نبرة العلاقة",
        sw="CARE inaweza kubadilisha toni ya uhusiano",
        ha="CARE na iya canza mita na alamar",
        am="CARE ምስጫውን ማስተካከል ይችላል",
        tl="Maaaring i-adjust ng CARE ang tono ng ugnayan",
        ms="CARE boleh menyesuaikan nada hubungan",
        mi="Ka taea e CARE te whakarite i te reo o te here",
    ),
    text(
        "love.careImpactTitle", 147,
        es="🔄 Cómo afecta al algoritmo CARE:",
        en="🔄 How it affects the CARE algorithm:",
        pt="🔄 Como isso afeta o algoritmo CARE:",
        fr="🔄 Comment cela affecte-t-il l'algorithme CARE ?",
        de="🔄 Wie es den CARE-Algorithmus beeinflusst:",
        it="🔄 Come influenza l'algoritmo CARE:",
        ru="🔄 Как это влияет на алгоритм CARE:",
        sv="🔄 Så påverkar det CARE-algoritmen:",
        nl="🔄 Hoe dit het CARE-algoritme beïnvloedt:",
        zh="🔄 它如何影响 CARE 算法：",
        hi="🔄 यह CARE एल्गोरिदम को कैसे प्रभावित करता है:",
        bn="🔄 এটি CARE অ্যালগরিদমকে কীভাবে প্রভাবিত করে:",
        ja="🔄 CAREアルゴリズムへの影響：",
        ko="🔄 CARE 알고리즘에 미치는 영향:",
        ar="🔄 كيف يؤثر في خوارزمية CARE:",
        sw="🔄 Jinsi inavyohudhu kwa algoridimu ya CARE:",
        ha="🔄 Yana nuna yadda take shafi na CARE",
        am="🔄 CARE አልጎሪዝሙን መቅረበት።",
        tl="🔄 Paano ito nakakaapekto sa CARE algorithm:",
        ms="🔄 Bagaimana ia mempengaruhi algoritma CARE:",
        mi="🔄 Me pēhea tēnei e pāngai ki te tikara CARE:",
    ),
    text(
        "love.careNote", 148,
        es="Tu lenguaje del amor define cómo das y recibes afecto. CARE lo usa para crear vínculos que te hagan sentir visto.",
        en="Your love language defines how you give and receive affection. CARE uses it to create bonds that make you feel seen.",
        pt="Sua linguagem do amor define como você dá e recebe afeto. O CARE usa para criar vínculos que façam você se sentir visto.",
        fr="Votre langage de l'amour définit comment vous donnez et recevez de l'affection. CARE l'utilise pour créer des liens qui vous font vous sentir vu.",
        de="Ihre Liebes Sprache bestimmt, wie Sie Zuneigung geben und empfangen. CARE nutzt sie, um Verbindungen zu schaffen, in denen Sie sich gesehen fühlen.",
        it="Il tuo linguaggio dell'amore definisce come dai e ricevi affetto. CARE lo usa per creare legami che ti facciano sentire visto.",
        ru="Ваш язык любви определяет, как вы дарите и принимаете нежность. CARE использует его, чтобы создавать связи, в которых вы чувствуете себя замеченным.",
        sv="Din kärlekens språk bestämmer hur du ger och tar emot kärlek. CARE använder det för att skapa band där du känner dig sedd.",
        nl="Je taal van de liefde bepaalt hoe je affectie geeft en ontvangt. CARE gebruikt die om verbindingen te creëren waarin je je gezien voelt.",
        zh="你的爱的语言定义了你如何给予和接收爱意。CARE 用它来建立让你感到被看见的联结。",
        hi="आपकी प्रेम की भाषा तय करती है कि आप प्यार कैसे देते और पाते हैं। CARE इसका उपयोग ऐसे जुड़ाव बनाने के लिए करता है जहाँ आपको देखा जाता है।",
        bn="আপনার ভালোবাসার ভাষা নির্ধারণ করে আপনি কীভাবে ভালোবাসা দেন ও পান। CARE এটি ব্যবহার করে এমন সম্পর্ক তৈরি করে যেখানে আপনাকে দেখা হয়।",
        ja="ラブの言葉とは、あなたがどのように愛的表达をするかです。CARE はそれを使って、自分を見られるような関係をつくります。",
        ko="사랑의 언어는 애정을 주고받는 방식을 결정합니다. CARE는 이를 사용해 당신이 존중받는다고 느끼는 관계를 만들어요.",
        ar="لغة الحب تحدد كيف تمنح الحب وتستقبله. يستخدمها CARE لبناء روابط تشعر فيها بأنك مرئي.",
        sw="Lugha yako ya upendo inaeleza jinsi unavyotumia na kupokea upendo. CARE inatumia hiyo kutengeneza mihawulo unaofahamu kuwa unazingatiwa.",
        ha="Harshe ta ƙauna tana tantanta yadda kake bai da karɗi ƙauna. CARE tana amfani da ita don ƙirƙiri mahaɗuwa da ke sa ka cika cika.",
        am="የፍቅርት ቋንቋህ ፍቅርትን እንዴት የምትሰጥ እንዴት የምትቀበል ያስቀምጣል። CARE ይህን በመጠቀሙ እርስህ የተመለከት ስሜን የሚያሳት ግንኙነቶችን ይፈጥራል።",
        tl="Ang wika ng pagmamahal mo ang nagtatakda kung paano mo ibinibigay at tinatanggap ang pagmamahal. Ginagamit ito ng CARE para makagawa ng mga ugnayang makakaramdam na nakikita ka.",
        ms="Bahasa cinta anda menentukan bagaimana anda memberi dan menerima kasih. CARE menggunakannya untuk membina hubungan yang membuat anda merasa dihargai.",
        mi="Ka whakatau tōu reo aroha i te huarahi e hoatu ai, e riro ai koe i te aroha. Ka whakamahi a CARE i tei ki te hanga here e hanga ai koe ki te mārama.",
    ),
    text(
        "love.option.acts_of_service.label", 150,
        es="Actos de servicio", en="Acts of service",
        pt="Atos de serviço", fr="Actes de service",
        de="Dienste", it="Atti di servizio",
        ru="Помощь и забота", sv="Handlingstjänster",
        nl="Daden van dienst",
        zh="服务的行动", hi="सेवा के कार्य", bn="সেবার কাজ",
        ja="奉仕の行動",
        ko="돌봄의 행동", ar="أفعال الخدمة",
        sw="Huduma za mkasa", ha="Ayyuka da ba da gargaɗi",
        am="የአገልግሎት ሥራዎች", tl="Mga akto ng paglilingkod",
        ms="Tindakan perkhidmatan", mi="Ngā mahi tautoko",
    ),
    text(
        "love.option.acts_of_service.desc", 151,
        es="Expresa amor a través de ayuda, cuidado y acciones concretas.",
        en="You express love through help, care and concrete actions.",
        pt="Você expressa amor através de ajuda, cuidado e ações concretas.",
        fr="Vous exprimez l'amour par de l'aide, des soins et des actions concrètes.",
        de="Du zeigst Liebe durch Hilfe, Fürsorge und konkrete Taten.",
        it="Esprimi amore attraverso aiuto, cura e azioni concrete.",
        ru="Вы выражаете любовь через помощь, заботу и конкретные поступки.",
        sv="Du visar kärlek genom hjälp, omsorg och konkreta handlingar.",
        nl="Je toont liefde via hulp, zorg en concrete acties.",
        zh="你通过帮助、照顾和实际行动表达爱。",
        hi="आप मदद, देखभाल और ठोस कार्यों से प्यार व्यक्त करते हैं।",
        bn="আপনি সাহায্য, যত্ন ও নির্দিষ্ট করণীয় দিয়ে ভালোবাসা প্রকাশ করেন।",
        ja="助けや心配、具体的な行動で愛情を表します。",
        ko="도움과 돌봄, 구체적인 행동으로 사랑을 표현해요.",
        ar="تُعبّر عن الحب بالمساعدة والعناية والأفعال الملموسة.",
        sw="Unaoonyesha upendo kwa msaada, hurudali na hatua za kweli.",
        ha="Kana nuna ƙauna ta taimako, girma da ayyuka masu ma'ana.",
        am="በእርዳታ፣ አስተዳደር እና ተግባራዊ እርሃዎች ፍቅርትህን ያሳያለህ።",
        tl="Ipinapakita ang pagmamahal sa pamamagitan ng tulong, pangangalaga at mga konkretong aksyon.",
        ms="Anda menyatakan cinta melalui bantuan, penjagaan dan tindakan konkrit.",
        mi="Ka whakaatu koe i te aroha mā te āwhina, te tiaki, me ngā mahi tangata",
    ),
    text(
        "love.option.acts_of_service.careImpact", 152,
        es="CARE sugiere gestos y rituales de apoyo. Matching por estilo de cuidado.",
        en="CARE suggests gestures and rituals of support. Matching by care style.",
        pt="O CARE sugere gestos e rituais de apoio. Compatibilidade por estilo de cuidado.",
        fr="CARE suggère des gestes et des rituels de soutien. Compatibilité par style de soin.",
        de="CARE schlägt Gesten und Rituale der Unterstützung vor. Zuordnung nach Fürsorge-Stil.",
        it="CARE suggerisce gesti e rituali di supporto. Affinità per stile di cura.",
        ru="CARE предлагает жесты и ритуалы поддержки. Подбор по стилю заботы.",
        sv="CARE föreslår gester och omsorgsritualer. Matchning efter omsorgsstil.",
        nl="CARE stelt gebaren en steunrituelen voor. Koppeling op zorgstijl.",
        zh="CARE 会建议支持性的举动和仪式。按照顾风格匹配。",
        hi="CARE सहायता के इशारे और अनुष्ठान सुझाएगा। देखभाल की शैली के अनुसार मिलान।",
        bn="CARE সহায়তার ইঙ্গিত ও অনুষ্ঠান প্রস্তাব করবে। যত্নের ধরন অনুযায়ী মিলান।",
        ja="CARE は支えの表現と儀式を提案し、介護のスタイルでマッチングします",
        ko="CARE는 돌봄의表现在 제안해요. 돌봄 스타일로 매칭해요.",
        ar="يقترح CARE إشارات وطقوسًا للدعم. المطابقة حسب أسلوب العناية.",
        sw="CARE inapendekeza ishara na mila za msaada. Kuoanisha kwa mtindo wa hurudali.",
        ha="CARE tana ba da shawara game na ayyuka na al'ada na goyon bayan da.",
        am="CARE ድጋፍ ምልክቶችንና ልማቶችን ያቀርጣል። በአገልግሎት አቀራረብ መሠረት ጥምረት።",
        tl="Magrerekomenda ng CARE ang mga tanda at ritwal ng suporta. Paghah-match ayon sa estilo ng pangangalaga.",
        ms="CARE mencadangkan isyarat dan ritual sokongan. Padanan mengikut gaya penjagaan.",
        mi="Ka tohutohu a CARE i ngā tohu me ngā tikara tautoko. Ka whakapiri ki te tikara tiaki.",
    ),
    text(
        "love.option.gifts.label", 153,
        es="Regalos", en="Gifts",
        pt="Presentes", fr="Cadeaux",
        de="Geschenke", it="Regali",
        ru="Подарки", sv="Presenter",
        nl="Cadeaus",
        zh="礼物", hi="उपहार", bn="উপহার",
        ja="贈り物",
        ko="선물", ar="هدايا",
        sw="Zawadi", ha="Kyautuka",
        am="ስጦታዎች", tl="Mga regalo",
        ms="Hadiah", mi="Ngā koha",
    ),
    text(
        "love.option.gifts.desc", 154,
        es="Expresa amor mediante detalles y objetos significativos.",
        en="You express love through meaningful details and objects.",
        pt="Você expressa amor por meio de detalhes e objetos significativos.",
        fr="Vous exprimez l'amour par des détails et des objets significatifs.",
        de="Du zeigst Liebe durch bedeutsame Details und Gegenstände.",
        it="Esprimi amore tramite dettagli e oggetti significativi.",
        ru="Вы выражаете любовь через значимые детали и предметы.",
        sv="Du visar kärlek genom meningsfulla detaljer och föremål.",
        nl="Je toont liefde via betekenisvolle details en voorwerpen.",
        zh="你通过有意义的细节和物品表达爱。",
        hi="आप अर्थपूर्ण विवरणों और वस्तुओं से प्यार व्यक्त करते हैं।",
        bn="আপনি অর্থবহ বিবরণ ও বস্তু দিয়ে ভালোবাসা প্রকাশ করেন।",
        ja="意味のある細部や品で愛情を表します",
        ko="의미 있는 디테일과 선물로 사랑을 표현해요.",
        ar="تُعبّر عن الحب بالتفاصيل والأغراض ذات الدلالة.",
        sw="Unaoonyesha upendo kwa maelezo na vitu vyenye maana.",
        ha="Kana nuna ƙauna ta cikakun bayanai da abin da ke da ma'ana.",
        am="በትርጅታዊ ዝርዝርና በትርጅት ዕቃዎች ፍቅርትህን ያሳያለህ።",
        tl="Ipinapakita ang pagmamahal sa pamamagitan ng mga detalye at bagay na makabuluhan.",
        ms="Anda menyatakan cinta melalui butiran dan benda yang bermakna.",
        mi="Ka whakaatu koe i te aroha mā ngā taipuo me ngā taonga he whai tikanga.",
    ),
    text(
        "love.option.gifts.careImpact", 155,
        es="CARE sugiere sorpresas y momentos simbólicos. Matching por estilo de expresión material.",
        en="CARE suggests surprises and symbolic moments. Matching by material expression style.",
        pt="O CARE sugere surpresas e momentos simbólicos. Compatibilidade por estilo de expressão material.",
        fr="CARE suggère des surprises et des moments symboliques. Compatibilité par style d'expression matérielle.",
        de="CARE schlägt Überraschungen und symbolische Momente vor. Zuordnung nach materiellem Ausdrucksstil.",
        it="CARE suggerisce sorprese e momenti simbolici. Affinità per stile di espressione materiale.",
        ru="CARE предлагает сюрпризы и символические моменты. Подбор по материальному стилю выражения.",
        sv="CARE föreslår överraskningar och symboliska stunder. Matchning efter materiellt uttryckssätt.",
        nl="CARE stelt verrassingen en symbolische momenten voor. Koppeling op materiële expressiestijl.",
        zh="CARE 会建议惊喜和象征性时刻。按物质表达风格匹配。",
        hi="CARE आश्चर्य और प्रतीकात्मक क्षणों का सुझाव देगा। भौतिक अभिव्यक्ति शैली के अनुसार मिलान।",
        bn="CARE অপ্রত্যাশিত ও প্রতীকীয় মুহূর্ত প্রস্তাব করবে। উপাদান ব্যক্তিকরণের ধরন অনুযায়ী মিলান।",
        ja="CARE はサプライズと象徴的な瞬間を提案し、物の表現のスタイルでマッチングします",
        ko="CARE는 서프라이즈와 상징적인 순간을 제안해요. 물질적 표현 스타일로 매칭해요.",
        ar="يقترح CARE مفاجآت ولحظات رمزية. المطابقة حسب أسلوب التعبير المادي.",
        sw="CARE inapendekeza mshangao na nyakati za ishara. Kuoanisha kwa mtindo wa ushiriki wa kiambato.",
        ha="CARE tana ba da shawara kan surprise da lokutan da alamar. Matching yana ta yadda nuna abin da ke",
        am="CARE አስገርመቶችንና ምልክታዊ ጊዜዎችን ያቀርጣል። በቁሳቁ መግለጽ አቀራረብ መሠረት ጥምረት።",
        tl="Magrerekomenda ng CARE ang mga surpresa at simbolikong sandali. Paghah-match ayon sa estilo ng materyal na pagpapahayag.",
        ms="CARE mencadangkan kejutan dan momen simbolik. Padanan mengikut gaya ungkapan material.",
        mi="Ka tohutohu a CARE i ngā oha me ngā wā tohu. Ka whakapiri ki te tikara tohu rawa.",
    ),
    text(
        "love.option.physical_touch.label", 156,
        es="Contacto físico", en="Physical touch",
        pt="Contacto físico", fr="Contact physique",
        de="Körperlicher Kontakt", it="Contatto fisico",
        ru="Физический контакт", sv="Fysisk kontakt",
        nl="Fysiek contact",
        zh="身体接触", hi="शारीरिक स्पर्श", bn="শারীরিক স্পর্শ",
        ja="物理的な接触", ko="신체 접촉", ar="اللمس الجسدي",
        sw="Mgusanyiko wa mwili", ha="Tuntuɗi na jiki",
        am="የሰው አካል ንክኪክ", tl="Physical na contact",
        ms="Sentuhan fizikal", mi="Pāhoro tinana",
    ),
    text(
        "love.option.physical_touch.desc", 157,
        es="Expresa amor a través del tacto, cercanía y presencia corporal.",
        en="You express love through touch, closeness and physical presence.",
        pt="Você expressa amor por meio do toque, proximidade e presença corporal.",
        fr="Vous exprimez l'amour par le toucher, la proximité et la présence corporelle.",
        de="Du zeigst Liebe durch Berührung, Nähe und körperliche Präsenz.",
        it="Esprimi amore attraverso il contatto, la vicinanza e la presenza corporea.",
        ru="Вы выражаете любовь через прикосновение, близость и физическое присутствие.",
        sv="Du visar kärlek genom beröring, närhet och kroppslig närvaro.",
        nl="Je toont liefde via aanraking, nabijheid en fysieke aanwezigheid.",
        zh="你通过触碰、亲近和身体在场表达爱。",
        hi="आप स्पर्श, निकटता और शारीरिक उपस्थिति से प्यार व्यक्त करते हैं।",
        bn="আপনি স্পর্শ, নিকটত্ব ও শারীরিক উপস্থিতি দিয়ে ভালোবাসা প্রকাশ করেন।",
        ja="触れ合い、距離感、身体的存在で愛情を表します。",
        ko="스침과 가까움, 신체적 존재감으로 사랑을 표현해요.",
        ar="تُعبّر عن الحب عبر اللمس والقرب والحضور الجسدي.",
        sw="Unaoonyesha upendo kwa mgusanyiko, ukaribu na uwepo wa mwili.",
        ha="Kana nuna ƙauna ta tuntuɗi, kusa da zuɗiya na kasance a jiki.",
        am="በመንክር፣ በቅርበትና በሰው አካል መገኘት ፍቅርትህን ያሳያለህ።",
        tl="Ipinapakita ang pagmamahal sa pamamagitan ng paghipo, paglapit at pagkakaroon ng katawan.",
        ms="Anda menyatakan cinta melalui sentuhan, kedekatan dan kehadiran fizikal.",
        mi="Ka whakaatu koe i te aroha mā te touch, te tata ki te tinana.",
    ),
    text(
        "love.option.physical_touch.careImpact", 158,
        es="CARE sugiere progresión visual y física. Matching por cercanía geográfica y estilo afectivo.",
        en="CARE suggests visual and physical progression. Matching by geographic proximity and affection style.",
        pt="O CARE sugere progressão visual e física. Compatibilidade por proximidade geográfica e estilo afetivo.",
        fr="CARE suggère une progression visuelle et physique. Compatibilité par proximité géographique et style affectif.",
        de="CARE schlägt visuelle und körperliche Entwicklung vor. Zuordnung nach geografischer Nähe und Zuneigungsstil.",
        it="CARE suggerisce progressione visiva e fisica. Affinità per vicinanza geografica e stile affettivo.",
        ru="CARE предлагает визуальное и физическое развитие. Подбор по географической близости и стилю привязанности.",
        sv="CARE föreslår visuell och fysisk utveckling. Matchning efter geografisk närhet och kärleksstil.",
        nl="CARE stelt visuele en fysieke vooruitgang voor. Koppeling op geografische nabijheid en affectiestijl.",
        zh="CARE 会建议视觉和身体上的进展。按地理接近度和情感风格匹配。",
        hi="CARE दृश्य और शारीरिक प्रगति का सुझाव देगा। भौगोलिक निकटता और भावनात्मक शैली के अनुसार मिलान।",
        bn="CARE দৃশ্যমান ও শারীরিক অগ্রগতি প্রস্তাব করবে। ভৌগোলিক কাছাকাছি ও আবেগের ধরন অনুযায়ী মিলান।",
        ja="CARE は視覚的・身体的な進展を提案します。地理的な近さと感情のスタイルでマッチングします。",
        ko="CARE는 시각적과 신체적 진행을 제안해요. 지리적 근접성과 애정 스타일로 매칭해요.",
        ar="يقترح CARE تقدمًا بصريًا وجسديًا. المطابقة حسب القرب الجغرافي وأسلوب المودة.",
        sw="CARE inapendekeza maendeleo ya macho na mwili. Kuoanisha kwa ukaribu wa kijiografia na mtindo wa hisa.",
        ha="CARE tana ba da shawara kan ganiya da jiki. Matching yana ta yadda wuri da kuma.",
        am="CARE የምስልና የሰው አካል መሻሻልን ያቀርጣል። በመልክር ቅርበትና በፍቅርት አቀራረብ መሠረት ጥምረት።",
        tl="Magrerekomenda ng CARE ang visual at pisikal na progreso. Paghah-match ayon sa kalakipang geograpiya at estilo ng pagmamahál.",
        ms="CARE mencadangkan kemajuan visual dan fizikal. Padanan mengikut kedekatan geografi dan gaya kasih.",
        mi="Ka tohutohu a CARE i te whainga kite me te tinana. Ka whakapiri ki te tata ā-whenua me te tikara aroha.",
    ),
    text(
        "love.option.words_of_affirmation.label", 159,
        es="Palabras de afirmación", en="Words of affirmation",
        pt="Palavras de afirmação", fr="Mots d'affirmation",
        de="Bestätigende Worte", it="Parole di conferma",
        ru="Слова поддержки", sv="Bekräftande ord",
        nl="Bevestigende woorden",
        zh="肯定的话语", hi="प्रशंसा के शब्द", bn="আত্মবিশ্বাসের কথা",
        ja="肯定の言葉", ko="인정의 말", ar="عبارات التأكيد",
        sw="Maneno ya uthibitishaji", ha="Kalma na tabbatarwa",
        am="የማረጋገጥ ቃላት", tl="Mga salitang pagpapakita",
        ms="Kata-kata pengesahan", mi="Ngā kupu whakamanua",
    ),
    text(
        "love.option.words_of_affirmation.desc", 160,
        es="Expresa amor mediante elogios, reconocimiento y comunicación verbal.",
        en="You express love through compliments, recognition and verbal communication.",
        pt="Você expressa amor por meio de elogios, reconhecimento e comunicação verbal.",
        fr="Vous exprimez l'amour par des compliments, de la reconnaissance et la communication verbale.",
        de="Du zeigst Liebe durch Komplimente, Anerkennung und verbale Kommunikation.",
        it="Esprimi amore tramite complimenti, riconoscimento e comunicazione verbale.",
        ru="Вы выражаете любовь через комплименты, признание и словесное общение.",
        sv="Du visar kärlek genom komplimanger, uppskattning och verbal kommunikation.",
        nl="Je toont liefde via complimenten, erkenning en verbale communicatie.",
        zh="你通过赞美、认可和言语交流表达爱。",
        hi="आप प्रशंसा, मान्यता और मौखिक संवाद से प्यार व्यक्त करते हैं।",
        bn="আপনি প্রশংসা, স্বীকৃতি ও মৌখিক যোগাযোগ দিয়ে ভালোবাসা প্রকাশ করেন।",
        ja="誉め言葉、理解、口頭でのやりとりで愛情を表します。",
        ko="칭찬과 인정, 말로 하는 소통으로 사랑을 표현해요.",
        ar="تُعبّر عن الحب عبر المديح والتقدير والتواصل اللفظي.",
        sw="Unaoonyesha upendo kwa sifa, utambuzi na mazungumzo ya moja kwa moja.",
        ha="Kana nuna ƙauna ta yabo, gaimi da magana da murya da baki.",
        am="በምስላት፣ በመረጃ እና በቃላዊ ግንኙነት ፍቅርትህን ያሳያለህ።",
        tl="Ipinapakita ang pagmamahal sa pamamagitan ng papuri, pagkilala at pakikipag-usap.",
        ms="Anda menyatakan cinta melalui pujian, pengiktirafan dan komunikasi lisan.",
        mi="Ka whakaatu koe i te aroha mā te mihi, te mihi hoki me te kōrero ā-waha.",
    ),
    text(
        "love.option.words_of_affirmation.careImpact", 161,
        es="CARE adapta microcopy y frecuencia de mensajes. Matching por estilo verbal.",
        en="CARE adapts microcopy and message frequency. Matching by verbal style.",
        pt="O CARE adapta o microcopy e a frequência de mensagens. Compatibilidade por estilo verbal.",
        fr="CARE adapte le microcopy et la fréquence des messages. Compatibilité par style verbal.",
        de="CARE passt Microcopy und Nachrichtenfrequenz an. Zuordnung nach verbalem Stil.",
        it="CARE adatta il microcopy e la frequenza dei messaggi. Affinità per stile verbale.",
        ru="CARE адаптирует микрокопи и частоту сообщений. Подбор по вербальному стилю.",
        sv="CARE anpassar mikrocopy och meddelandefrekvens. Matchning efter verbal stil.",
        nl="CARE past microcopy en berichtfrequentie aan. Koppeling op verbale stijl.",
        zh="CARE 会调整微文案和消息频率。按言语风格匹配。",
        hi="CARE माइक्रोकॉपी और संदेशों की आवृत्ति समायोजित करता है। मौखिक शैली के अनुसार मिलान।",
        bn="CARE মাইক্রোকপি ও বার্তার হার সমন্বয় করে। মৌখিক ধরন অনুযায়ী মিলান।",
        ja="CARE はマイクロコピーやメッセージ頻度を調整し、文章表現のスタイルでマッチングします",
        ko="CARE는 마이크로카피와 메시지 빈도를 맞춰요. 말투 스타일로 매칭해요.",
        ar="يكيّف CARE النسخ المصغّر وتكرار الرسائل. المطابقة حسب الأسلوب اللفظي.",
        sw="CARE hubadilisha mikrocopy na mzunguko wa ujumbe. Kuoanisha kwa mtindo wa maneno.",
        ha="CARE tana canza rubutun da mita na yawanin saƙo. Matching yana ta yadda magana da baki.",
        am="CARE አይሮራውንና የመልእክት ብዛትን ያስተካክላል። በቃላዊ አቀራረብ መሠረት ጥምረት።",
        tl="Iniaangkop ng CARE ang microcopy at dalas ng mensahe. Paghah-match ayon sa estilo ng salita.",
        ms="CARE menyesuaikan mikrocopy dan kerapuhan mesej. Padanan mengikut gaya verbal.",
        mi="Ka whakarite a CARE i te kupu iti me te maha o ngā karere. Ka whakapiri ki te tikara reo.",
    ),
    text(
        "love.option.quality_time.label", 162,
        es="Tiempo de calidad", en="Quality time",
        pt="Tempo de qualidade", fr="Temps de qualité",
        de="Hochwertige Zeit", it="Tempo di qualità",
        ru="Качественное время", sv="Kvalitetstid",
        nl="Qualitytijd",
        zh="高质量的相处时光", hi="गुणवत्ता समय", bn="মানসম্মত সময়",
        ja="質のある時間", ko="함께하는 소중한 시간", ar="وقت ذو جودة",
        sw="Wakati wa ubora", ha="Babban lokaci",
        am="ጥሩ ጊዜ", tl="Kalidad na oras",
        ms="Masa berkualiti", mi="Wā pai kounga",
    ),
    text(
        "love.option.quality_time.desc", 163,
        es="Expresa amor compartiendo momentos significativos y atención plena.",
        en="You express love by sharing meaningful moments and giving full attention.",
        pt="Você expressa amor compartilhando momentos significativos e atenção total.",
        fr="Vous exprimez l'amour en partageant des moments significatifs et une attention totale.",
        de="Du teilst Liebe, indem du bedeutungsvolle Momente und volle Aufmerksamkeit teilst.",
        it="Esprimi amore condividendo momenti significativi e piena attenzione.",
        ru="Вы выражаете любовь, делясь значимыми моментами и полным вниманием.",
        sv="Du visar kärlek genom att dela meningsfulla stunder och vara helt närvarande.",
        nl="Je toont liefde door betekenisvolle momenten te delen en volledig aandacht te geven.",
        zh="你通过分享重要时刻和全心陪伴表达爱。",
        hi="आप अर्थपूर्ण क्षण साझा करके और पूरा ध्यान देकर प्यार व्यक्त करते हैं।",
        bn="আপনি অর্থবহ মুহূর্ত ভাগ করে ও সম্পূর্ণ মনোযোগ দিয়ে ভালোবাসা প্রকাশ করেন।",
        ja="意味のある瞬間を共有し、心を込めて過ごすことで愛情を表します。",
        ko="의미 있는 순간을 나누고 온전히 집중하며 사랑을 표현해요.",
        ar="تُعبّر عن الحب بمشاركة اللحظات ذات المعنى وبإعطاء انتباهك الكامل.",
        sw="Unaoonyesha upendo kwa kushiriki nyakati zenye maana na kupeana kikamilifu.",
        ha="Kana nuna ƙauna ta raba lokutan da ke da ma'ana da kuma mayar da hankali cikakke.",
        am="በትርጅታዊ ጊዜዎችን በመጋራትና በሙሉ ትኩረት ፍቅርትህን ያሳያለህ።",
        tl="Ipinapakita ang pagmamahal sa pagbabahagi ng makabuluhang sandali at buong pagkakaiso.",
        ms="Anda menyatakan cinta dengan berkongsi momen bermakna dan memberi perhatian sepenuhnya.",
        mi="Ka whakaatu koe i te aroha mā te tiritiri wā tohu me te aroha katoa.",
    ),
    text(
        "love.option.quality_time.careImpact", 164,
        es="CARE sugiere rituales compartidos. Matching por disponibilidad emocional y estilo de vida.",
        en="CARE suggests shared rituals. Matching by emotional availability and lifestyle.",
        pt="O CARE sugere rituais compartilhados. Compatibilidade por disponibilidade emocional e estilo de vida.",
        fr="CARE suggère des rituels partagés. Compatibilité par disponibilité émotionnelle et style de vie.",
        de="CARE schlägt gemeinsame Rituale vor. Zuordnung nach emotionaler Verfügbarkeit und Lebensstil.",
        it="CARE suggerisce rituali condivisi. Affinità per disponibilità emotiva e stile di vita.",
        ru="CARE предлагает совместные ритуалы. Подбор по эмоциональной доступности и образу жизни.",
        sv="CARE föreslår delade ritualer. Matchning efter emotionell tillgänglighet och livsstil.",
        nl="CARE stelt gedeelde rituelen voor. Koppeling op emotionele beschikbaarheid en levensstijl.",
        zh="CARE 会建议共同的仪式。按情感投入度和生活方式匹配。",
        hi="CARE साझा अनुष्ठान सुझाएगा। भावनात्मक उपलब्धता और जीवनशैली के अनुसार मिलान।",
        bn="CARE ভাগ করে নেওয়া অনুষ্ঠান প্রস্তাব করবে। আবেগের প্রাপ্যতা ও জীবনযাত্রার ধরন অনুযায়ী মিলান।",
        ja="CARE は共通の儀式を提案し、感情のゆとりや生活スタイルの考え方でマッチングします。",
        ko="CARE는 함께 하는 의식을 제안해요. 감정적 여유와 생활방식으로 매칭해요.",
        ar="يقترح CARE طقوسًا مشتركة. المطابقة حسب التوافر العاطفي وأسلوب الحياة.",
        sw="CARE inapendekeza mila zinazoshirikiwa. Kuoanisha kwa utayari wa hisa na mtindo wa maisha.",
        ha="CARE tana ba da shawara kan al'ada da gode. Matching ta yadda zuciya da yadda rayuwa take.",
        am="CARE የተጋራ ልማቶችን ያቀርጣል። በስሜታዊ ክህሎትና በየእርስ አመለካከት ጥምረት።",
        tl="Magrerekomenda ng CARE ang mga ritwal na magkasama. Paghah-match ayon sa availability ng damdamin at lifestyle.",
        ms="CARE mencadangkan ritual bersama. Padanan mengikut ketersediaan emosi dan gaya hidup.",
        mi="Ka tohutohu a CARE i ngā tikara tiritiri. Ka whakapiri ki te māraratanga o te māuiro me te ahupū.",
    ),
]