"""UI texts for the "Tipo de Relación" (Relationship Type) subsection.

`tipType` / `tipGoal` are rendered inside <strong> and composed with
`tipTypeMid` / `tipGoalMid`, so those four values must stay short fragments that
read correctly in the order the component assembles them.
"""

from .common import text

TEXTS = [
    text(
        "relationship.title", 30,
        es="Tipo de relación", en="Relationship type",
        pt="Tipo de relação", fr="Type de relation",
        de="Beziehungsart", it="Tipo di relazione",
        ru="Тип отношений", sv="Relationstyp", nl="Relatietype",
        zh="关系类型", hi="रिश्ते का प्रकार", bn="সম্পর্কের ধরন",
        ja="関係タイプ", ko="관계 유형", ar="نوع العلاقة",
        sw="Aina ya uhusiano", ha="Irin mu'amala", am="የግንኙነት አይነት",
        tl="Uri ng relasyon", ms="Jenis hubungan", mi="Mō te whakawhanaunga",
    ),
    text(
        "relationship.question", 31,
        es="¿Cómo te vinculas emocional y sexualmente?",
        en="How do you connect emotionally and sexually?",
        pt="Como você se vincula emocional e sexualmente?",
        fr="Comment vous liez-vous émotionnellement et sexuellement ?",
        de="Wie verbinden Sie sich emotional und sexuell?",
        it="Come ti leghi emotivamente e sessualmente?",
        ru="Как вы связываетесь эмоционально и сексуально?",
        sv="Hur binds du känslomässigt och sexuellt?",
        nl="Hoe verbind je je emotioneel en seksueel?",
        zh="你在情感和身体上如何建立联结？",
        hi="आप भावनात्मक और यौन रूप से कैसे जुड़ते हैं?",
        bn="আপনি আবেগ এবং যৌনভাবে কীভাবে সংযুক্ত হন?",
        ja="精神的に、身体的にどう結びつきますか？",
        ko="감정적으로 그리고 성적으로 어떻게 연결되시나요?",
        ar="كيف تتواصل عاطفيًا وجسديًا؟",
        sw="Unavyounganisha kwa hisa na mwili vipi?",
        ha="Yaya kake kaibi ka gani kuma jiki?",
        am="በስሜና እና በሰራር እንዴት ይገናኛላለሁ?",
        tl="Paano ka nakikipag-ugnayan emosyonal at sexuwal?",
        ms="Bagaimana anda berhubung secara emosi dan seksual?",
        mi="Me pēhea koe e here ai ki te māhi me te tinana?",
    ),
    text(
        "relationship.tipType", 32,
        es="Tu tipo de relación", en="Your relationship type",
        pt="Seu tipo de relação", fr="Votre type de relation",
        de="Ihre Beziehungsart", it="Il tuo tipo di relazione",
        ru="Ваш тип отношений", sv="Din relationstyp", nl="Je relatietype",
        zh="你的关系类型", hi="आपका रिश्ते का प्रकार", bn="আপনার সম্পর্কের ধরন",
        ja="あなたの関係タイプ", ko="당신의 관계 유형", ar="نوع علاقتك",
        sw="Aina ya uhusiano wako", ha="Irin mu'amalarka", am="የግንኙነት አይነትህ",
        tl="Ang uri ng iyong relasyon", ms="Jenis hubungan anda",
        mi="Tō mō te whakawhanaunga",
    ),
    text(
        "relationship.tipTypeMid", 33,
        es="define cómo te vinculas.", en="defines how you connect.",
        pt="define como você se vincula.", fr="définit la façon dont vous vous liez.",
        de="bestimmt, wie Sie sich verbinden.",
        it="definisce come ti leghi.",
        ru="определяет, как вы связываетесь.",
        sv="bestämmer hur du binder dig.", nl="bepaalt hoe je je verbindt.",
        zh="决定你如何建立联结。", hi="यह तय करता है कि आप कैसे जुड़ते हैं।",
        bn="আপনি কীভাবে সংযুক্ত হন তা নির্ধারণ করে।",
        ja="結びつき方を決めます。", ko="연결 방식을 결정합니다.",
        ar="يحدد كيف تتواصل.",
        sw="inabainisha jinsi unavyounganisha.",
        ha="yana nuna yadda kake kaibi.",
        am="እንዴት ስለሚገናኙ ያስቀምጣል።",
        tl="tinutukoy kung paano ka nakikipag-ugnayan.",
        ms="menentukan cara anda berhubung.",
        mi="Ka whakatau me pēhea koe e here ai.",
    ),
    text(
        "relationship.tipGoal", 34,
        es="Tu objetivo", en="Your goal",
        pt="Seu objetivo", fr="Votre objectif",
        de="Ihr Ziel", it="Il tuo obiettivo",
        ru="Ваша цель", sv="Ditt mål", nl="Je doel",
        zh="你的目标", hi="आपका लक्ष्य", bn="আপনার লক্ষ্য",
        ja="あなたの目標", ko="당신의 목표", ar="هدفك",
        sw="Lengo lako", ha="Manufa'inka", am="ግብ",
        tl="Ang iyong layunin", ms="Matlamat anda", mi="Tō whāinga",
    ),
    text(
        "relationship.tipGoalMid", 35,
        es="define qué buscas ahora.", en="defines what you are looking for now.",
        pt="define o que você busca agora.", fr="définit ce que vous cherchez maintenant.",
        de="bestimmt, was Sie jetzt suchen.",
        it="definisce cosa cerchi adesso.",
        ru="определяет, что вы ищете сейчас.",
        sv="bestämmer vad du letar efter nu.", nl="bepaalt wat je nu zoekt.",
        zh="决定你现在寻找什么。", hi="यह तय करता है कि आप अभी क्या खोज रहे हैं।",
        bn="আপনি এখন কী খুঁজছেন তা নির্ধারণ করে।",
        ja="今は何を求めているかを決めます。", ko="지금 무엇을 찾고 있는지 결정합니다.",
        ar="يحدد ما تبحث عنه الآن.",
        sw="inabainisha unachotafuta sasa.",
        ha="yana nuna abin da kake nema yanzu.",
        am="አሁን ምን እየፈለግክ እንደሆነ ያስቀምጣል።",
        tl="tinutukoy kung ano ang hinahanap mo ngayon.",
        ms="menentukan apa yang anda cari sekarang.",
        mi="Ka whakatau me pēhea koe e kimi ana ināianei.",
    ),
    text(
        "relationship.groupExclusive", 36,
        es="Exclusividad", en="Exclusivity",
        pt="Exclusividade", fr="Exclusivité",
        de="Exklusivität", it="Esclusività",
        ru="Исключительность", sv="Exklusivitet", nl="Exclusiviteit",
        zh="排他性", hi="अनन्यता", bn="একগুড়িভাব",
        ja="独占性", ko="배타성", ar="الحصرية",
        sw="Upekufu", ha="Kalone", am="አናውጥ",
        tl="Pagkakaisa", ms="Kekhususan", mi="Te māori",
    ),
    text(
        "relationship.groupOpen", 37,
        es="Apertura y Flexibilidad", en="Openness and Flexibility",
        pt="Abertura e Flexibilidade", fr="Ouverture et Flexibilité",
        de="Offenheit und Flexibilität", it="Apertura e Flessibilità",
        ru="Открытость и гибкость", sv="Öppenhet och flexibilitet",
        nl="Openheid en flexibiliteit",
        zh="开放与灵活", hi="खुलेपन और लचीलापन", bn="উন্মুক্ততা ও নমনীয়তা",
        ja="オープンさと柔軟性", ko="개방성과 유연성", ar="الانفتاح والمرونة",
        sw="Ufufuaji na unyumbufu", ha="Buɗewa da sassauƙe",
        am="ክፍትነትና ተለጋጋጭነት",
        tl="Pagkakabukas at Kasunodan", ms="Keterbukaan dan Fleksibiliti",
        mi="Te tuwhera me te ngāwari",
    ),
    text(
        "relationship.opt.monogamy.label", 38,
        es="Monógama", en="Monogamous",
        pt="Monógama", fr="Monogame",
        de="Monogam", it="Monogamo",
        ru="Моногамия", sv="Monogam", nl="Monogaam",
        zh="一夫一妻制", hi="एकनिष्ठ", bn="একক বিবাহ",
        ja="モノガミー", ko="단일 파트너", ar="أحادية",
        sw="Monogamia", ha="Ƙuna daya", am="አንድ ትክክል",
        tl="Monogamy", ms="Monogami", mi="Takitoki",
    ),
    text(
        "relationship.opt.monogamy.desc", 39,
        es="Buscas exclusividad emocional y sexual con una sola persona.",
        en="You are looking for emotional and sexual exclusivity with one person.",
        pt="Você busca exclusividade emocional e sexual com uma única pessoa.",
        fr="Vous recherchez une exclusivité émotionnelle et sexuelle avec une seule personne.",
        de="Sie suchen emotionale und sexuelle Exklusivität mit einer einzigen Person.",
        it="Cerchi esclusività emotiva e sessuale con una sola persona.",
        ru="Вы ищете эмоциональную и сексуальную исключительность с одним человеком.",
        sv="Du söker emotionell och sexuell exklusivitet med en enda person.",
        nl="Je zoekt emotionele en seksuele exclusiviteit met één persoon.",
        zh="你寻求与一个人建立情感和身体上的专一关系。",
        hi="आप एक ही व्यक्ति के साथ भावनात्मक और यौन अनन्यता खोजते हैं।",
        bn="আপনি এক ব্যক্তির সাথে আবেগ ও যৌন একগুড়িভাব খুঁজছেন।",
        ja="一人の人と精神的にも性的にも独占的な関係を求めています。",
        ko="한 사람과 정서적·성적으로 독점적인 관계를 찾고 있습니다.",
        ar="تبحث عن حصرية عاطفية وجنسية مع شخص واحد.",
        sw="Unatafuta kipekee cha hisa na mwili na mtu mmoja.",
        ha="Kana neman ƙanciyar ƙwaɗi da jiki da mutum daya.",
        am="አንድ ሰዎች ጋር የስሜናና የሰራር ስምነትን ታልማላለሁ።",
        tl="Hinahanap mo ang emosyonal at sexuwal na pagkakaisa sa isang tao.",
        ms="Anda mencari keeksklusifan emosi dan seksual dengan satu orang.",
        mi="Ke rapu ana koe i te māhi me te tinana mō te tangata kotahi.",
    ),
    text(
        "relationship.opt.polyamory.label", 40,
        es="Poliamor", en="Polyamory",
        pt="Poliamoria", fr="Polyamour",
        de="Polyamorie", it="Poliamoria",
        ru="Полиамия", sv="Polyamori", nl="Polyamorie",
        zh="多重之爱", hi="बहुसंबंध प्रेम", bn="বহুপ্রেম",
        ja="ポリアモリー", ko="다중 연애", ar="تعدد الأزواج",
        sw="Upendo wa watu wengi", ha="Ƙaƙoƙarin ƙoyaushe",
        am="ብዙ ሰዎችን መፈቀድ", tl="Polyamory", ms="Poliamori",
        mi="Te aroha mō te maha",
    ),
    text(
        "relationship.opt.polyamory.desc", 41,
        es="Puedes amar a más de una persona, con acuerdos claros.",
        en="You can love more than one person, with clear agreements.",
        pt="Você pode amar mais de uma pessoa, com acordos claros.",
        fr="Vous pouvez aimer plus d'une personne, avec des accords clairs.",
        de="Sie können mehr als eine Person lieben, mit klaren Vereinbarungen.",
        it="Puoi amare più di una persona, con accordi chiari.",
        ru="Вы можете любить больше одного человека, при чётких договорённостях.",
        sv="Du kan älska mer än en person, med tydliga överenskommelser.",
        nl="Je kunt van meer dan één persoon houden, met duidelijke afspraken.",
        zh="你可以爱不止一个人，前提是有清晰的约定。",
        hi="आप एक से अधिक व्यक्ति से प्रेम कर सकते हैं, स्पष्ट सहमति के साथ।",
        bn="আপনি একাধিক ব্যক্তিকে ভালোবাসতে পারেন, স্পষ্ট চুক্তির সাথে।",
        ja="明確な合意のもとに、複数人を愛せます。",
        ko="분명한 합의 아래 여러 사람을 사랑할 수 있습니다.",
        ar="يمكنك أن تحب أكثر من شخص واحد، باتفاقيات واضحة.",
        sw="Unaweza kupenda watu zaidi ya mmoja, kwa makubaliano mazuri.",
        ha="Za ka iya ƙauna fiye da mutum daya, tare da yarjejeni bayan.",
        am="ብዙ ሰዎችን መፈቀድ ይችላለሁ፣ በግልጽ ስምምነት።",
        tl="Maaari kang mahalin ang higit sa isang tao, may malinaw na kasunduan.",
        ms="Anda boleh sayang lebih daripada seorang dengan perjanjian yang jelas.",
        mi="Ka taea te aroha i te kotahi runga ake, ma te whakatū mārama.",
    ),
    text(
        "relationship.opt.open.label", 42,
        es="Relación abierta", en="Open relationship",
        pt="Relação aberta", fr="Relation ouverte",
        de="Offene Beziehung", it="Relazione aperta",
        ru="Открытые отношения", sv="Öppet förhållande", nl="Open relatie",
        zh="开放性关系", hi="मुक्त संबंध", bn="উন্মুক্ত সম্পর্ক",
        ja="オープン関係", ko="열린 관계", ar="علاقة مفتوحة",
        sw="Uhusiano huria", ha="Yanayi da budewa", am="ክፍት ግንኙነት",
        tl="Bukas na relasyon", ms="Hubungan terbuka",
        mi="Te whakawhanaunga tuwhera",
    ),
    text(
        "relationship.opt.open.desc", 43,
        es="Tienes un vínculo principal, pero con apertura sexual consensuada.",
        en="You have a primary bond, but with consensual sexual openness.",
        pt="Você tem um vínculo principal, mas com abertura sexual consentida.",
        fr="Vous avez un lien principal, mais avec une ouverture sexuelle consentie.",
        de="Sie haben eine Hauptbindung, aber mit einvernehmlicher sexueller Offenheit.",
        it="Hai un legame principale, ma con apertura sessuale consensuale.",
        ru="У вас есть основная связь, но с взаимным согласием на сексуальную открытость.",
        sv="Du har en huvudsrelation, men med ömsesamt sexuellt öppande.",
        nl="Je hebt een hoofdrelatie, maar met wederzijdse seksuele openheid.",
        zh="你有一段主要关系，但双方同意保持性开放。",
        hi="आपका एक मुख्य संबंध है, लेकिन सहमति से यौन खुलेपन के साथ।",
        bn="আপনার একটি প্রধান সম্পর্ক আছে, তবে সম্মতিতে যৌন উন্মুক্ততা সহ।",
        ja="主要な関係がありつつ、合意のもとで性が開かれています。",
        ko="주된 관계가 있지만 상호 동의 하에 성적 개방성이 있습니다.",
        ar="لديك علاقة رئيسية، لكن بانفتاح جنسي بالاتفاق المتبادل.",
        sw="Una mbali yenye kujitolea, lakini kwa kufunguliwa kingiro kwa makubaliano.",
        ha="Kana da maysara mai bambanta, amma tare da budewa na jiki da yardar mutuwa.",
        am="ዋና ሪያን አለዎት፣ ግን በተመለስተኛ የሰራር ክፍትነት።",
        tl="Mayroon kang pangunahing ugnayan, ngunit may konsenswal na pagbubukas sa seks.",
        ms="Anda mempunyai hubungan utama, tetapi dengan keterbukaan seksual yang dipersetujui.",
        mi="He oha tō mō te here nui, engari ma te tuwhera tō te tinana i te whakaae.",
    ),
    text(
        "relationship.opt.swinger.label", 44,
        es="Swinger", en="Swinger",
        pt="Swinger", fr="Swinger",
        de="Swinger", it="Swinger",
        ru="Свингеры", sv="Swinger", nl="Swinger",
        zh="换伴", hi="स्विंगर", bn="সোয়িঙার",
        ja="スウィンガー", ko="교제 교환", ar="سوينجر",
        sw="Swinger", ha="Swinger", am="ፓርትናዊ",
        tl="Swinger", ms="Swinger", mi="Pariha tauhapere",
    ),
    text(
        "relationship.opt.swinger.desc", 45,
        es="Buscas experiencias compartidas en pareja, sin vínculo romántico.",
        en="You are looking for shared couple experiences, without a romantic bond.",
        pt="Você busca experiências compartilhadas em casal, sem vínculo romântico.",
        fr="Vous recherchez des expériences partagées en couple, sans lien romantique.",
        de="Sie suchen gemeinsame Erfahrungen zu zweit, ohne romantische Bindung.",
        it="Cerchi esperienze condivise in coppia, senza legame romantico.",
        ru="Вы ищете совместный опыт в паре, без романтических отношений.",
        sv="Du söker delade upplevelser i par, utan romantiskt band.",
        nl="Je zoekt gedeelde ervaringen als paar, zonder romantische band.",
        zh="你寻找伴侣之间的共享体验，但不要浪漫关系。",
        hi="आप जोड़े में साझा अनुभव खोजते हैं, रोमांसिक बंधन के बिना।",
        bn="আপনি জোড়ায় একসাথে অভিজ্ঞতা খুঁজছেন, রোমান্টিক বন্ধন ছাড়া।",
        ja="恋愛関係を持たず、二人で過ごす体験を求めています。",
        ko="러맨틱한 관계 없이 커플로 함께하는 경험을 찾고 있습니다.",
        ar="تبحث عن تجارب مشتركة كزوجين دون علاقة رومانسية.",
        sw="Unatafuta uzoefu wa pamoja kama mpenzi bila uhusiano wa hurumani.",
        ha="Kana neman al'ada mai ɗauke da mutane da ke tare da su, ba tare da ƙauna ba.",
        am="የሮማንቲክ ስምምነት ሳይኖር በጥምረት የተጋራ ውጤት ይፈልጋለሁ።",
        tl="Hinahanap mo ang mga karanasan na ibinabahagi ng mag-asawa nang walang romantikong ugnayan.",
        ms="Anda mencari pengalaman bersama sebagai pasangan tanpa hubungan romantis.",
        mi="Ke rapu ana koe i te māhi tahi ai runga ake he hoa tapere, kāore he here aroha.",
    ),
]