"""UI texts for the "Signo Zodiacal" (Zodiac Sign) subsection."""

from .common import text

TEXTS = [
    text(
        "zodiac.title", 50,
        es="Signo Zodiacal", en="Zodiac Sign",
        pt="Signo Zodiacal", fr="Signe zodiacal",
        de="Tierkreiszeichen", it="Segno zodiacale",
        ru="Знак зодиака", sv="Stjärntecken", nl="Zodiac-teken",
        zh="星座", hi="राशि", bn="রাশি",
        ja="星座", ko="별자리", ar="برجك",
        sw="Nyakati ya zodiaco", ha="Alama ta burj",
        am="የአሮሌክ ምልክት", tl="Pang-araw ng zodiaco",
        ms="Tanda zodiak", mi="Mō te tōpūtanga",
    ),
    text(
        "zodiac.question", 51,
        es="¿Quieres que influya en tu compatibilidad?",
        en="Do you want it to influence your compatibility?",
        pt="Você quer que ele influencie sua compatibilidade?",
        fr="Souhaitez-vous qu'il influence votre compatibilité ?",
        de="Soll es Ihre Kompatibilität beeinflussen?",
        it="Vuoi che influenzi la tua compatibilità?",
        ru="Хотите, чтобы он влиял на вашу совместимость?",
        sv="Vill du att det påverkar din kompatibilitet?",
        nl="Wil je dat het je compatibiliteit beïnvloedt?",
        zh="你希望它影响你的匹配度吗？",
        hi="क्या आप चाहते हैं कि यह आपकी अनुकूलता को प्रभावित करे?",
        bn="আপনি কি চান যে এটি আপনার সামঞ্জস্যতাকে প্রভাবিত করুক?",
        ja="あなたのマッチに影響を与えたいですか？",
        ko="당신의 궁합에 영향을 주기를 원하시나요?",
        ar="هل تريد أن يؤثر في توافقك؟",
        sw="Ungependa kwamba iathirini uoendana wako?",
        ha="Kana sona cewa ta yi daɗawa da mutammaninka?",
        am="ማስማሚነትህን እንወስድ ይፈልጋለህ?",
        tl="Gusto mo bang makapagpabago ito sa compatibility mo?",
        ms="Adakah anda mahu ia mempengaruhi keserasian anda?",
        mi="E hiahia ana koe kia whakatau kōtū?",
    ),
    text(
        "zodiac.optOut", 52,
        es="No me interesa responder", en="I'm not interested in answering",
        pt="Não tenho interesse em responder", fr="Je ne souhaite pas répondre",
        de="Mich interessiert die Antwort nicht", it="Non mi interessa rispondere",
        ru="Я не хочу отвечать", sv="Jag är inte intresserad av att svara",
        nl="Ik heb geen interesse om te antwoorden",
        zh="我不想回答", hi="मुझे जवाब देने में रुचि नहीं है",
        bn="আমার উত্তর দিতে আগ্রহ নেই",
        ja="回答したくない", ko="답변하고 싶지 않아요", ar="لا أريد الرد",
        sw="Sina interest kujibu", ha="Ban sha'awar amsa",
        am="መልስ መስጠትን አይፈልግምም",
        tl="Hindi ako interestedeng sumagot", ms="Saya tidak|datum menjawab",
        mi="Kāore au e hiahia ki te whakautu",
    ),
    text(
        "zodiac.optOutTooltip", 53,
        es="No todos creen en la astrología. Tú decides si tu signo debe influir en tus conexiones.",
        en="Not everyone believes in astrology. You decide if your sign should influence your connections.",
        pt="Nem todos acreditam na astrologia. Você decide se o seu signo deve influenciar suas conexões.",
        fr="Tout le monde ne croit pas à l'astrologie. Vous décidez si votre signe doit influencer vos connexions.",
        de="Nicht alle glauben an Astrologie. Sie entscheiden, ob Ihr Zeichen Ihre Verbindungen beeinflussen soll.",
        it="Non tutti credono all'astrologia. Decidi tu se il tuo segno deve influenzare le tue connessioni.",
        ru="Не все верят в астрологию. Вы решаете, должен ли ваш знак влиять на ваши связи.",
        sv="Inte alla tror på astrologi. Du bestämmer om ditt tecken ska påverka dina kontakter.",
        nl="Niet iedereen gelooft in astrologie. Jij bepaalt of je teken je connecties mag beïnvloeden.",
        zh="不是所有人都相信星座。是否让你的星座影响你的连接，由你决定。",
        hi="सभी राशि शास्त्र में विश्वास नहीं करते। यह आप तय करते हैं कि आपकी राशि आपके जुड़ाव को प्रभावित करे या नहीं।",
        bn="সবাই জ্যোতিশাস্ত্রে বিশ্বাস করেন না। আপনার রাশি আপনার সম্পর্ককে প্রভাবিত করবে কি না তা আপনি ঠিক করবেন।",
        ja="所有人都占星術を信じているわけではありません。あなたのサインが関係に影響を与えるかどうかは、あなたが決めます。",
        ko="모두가 점술을 믿지는 않습니다. 당신의 별자리가 관계에 영향을 줄지 말지는 당신이 결정합니다.",
        ar="لا الجميع يؤمن بعلم الفلك. أنت تقرر هل يجب أن يؤثر برجك في علاقاتك.",
        sw="Sio wote hawamini astrologia. Unaamua kama ishara yako inathiri miungo yako.",
        ha="Ba duk sun yi imani da astrology. Kana yanke ko alamarinka ta yi daɗawa da mahaɗuwa.",
        am="ሁሉም አስተማርን ማክበር አይችሉም። ኮከልህ ምልክትህ ግንኙነትህን እንወስድ አለ ወይስ አይሆን ነው ታደርጋለህ።",
        tl="Hindi lahat ang naniniwala sa astrology. Ikaw ang nagpapasiya kung dapat bang impluwensyahan ng iyong sign ang iyong mga koneksyon.",
        ms="Tidak semua percaya pada astrologi. Anda yang memutuskan sama ada tanda anda-pat seperti memberi kesan kepada hubungan anda.",
        mi="Kāore mō te katoa e whakapono ki te horoscope. Ka koe e whakatau mē runga anō tōu tohu.",
    ),
    text(
        "zodiac.visible", 54,
        es="✅ Tu signo está visible. Influye en tus matches.",
        en="✅ Your sign is visible. It influences your matches.",
        pt="✅ Seu signo está visível. Influencia suas combinações.",
        fr="✅ Votre signe est visible. Il influence vos matchs.",
        de="✅ Ihr Zeichen ist sichtbar. Es beeinflusst Ihre Matches.",
        it="✅ Il tuo segno è visibile. Influenza i tuoi match.",
        ru="✅ Ваш знак виден. Он влияет на ваши совпадения.",
        sv="✅ Ditt tecken är synligt. Det påverkar dina träffar.",
        nl="✅ Je teken is zichtbaar. Het beïnvloedt je matches.",
        zh="✅ 你的星座是可见的。它会影响你的匹配。",
        hi="✅ आपकी राशि दिखती है। यह आपके मेच को प्रभावित करती है।",
        bn="✅ আপনার রাশি দৃশ্যমান। এটি আপনার মেচকে প্রভাবিত করে।",
        ja="✅ あなたのサインは公開されています。マッチに影響します。",
        ko="✅ 당신의 별자리가 공개되어 있습니다. 매치에 영향을 줍니다.",
        ar="✅ برجك مرئي. يؤثر في توافقاتك.",
        sw="✅ Ishara yako inaonekana. Inaathirini mila yako.",
        ha="✅ Alamarinka tana nuna. Tana daɗawa da mutammane dukata.",
        am="✅ ምልክትህ ታይቷል። የመስተዋቅቶችህን ይጎዳል።",
        tl="✅ Nakikita ang iyong sign. Nakaaalam sa iyong matches.",
        ms="✅ Tanda anda kelihatan. Ia mempengaruhi padanan anda.",
        mi="✅ Ke te mārama tōu tohu. Ka whakatau i ō rangi hī.",
    ),
    text(
        "zodiac.hidden", 55,
        es="🚫 Tu signo está oculto. No influye en la compatibilidad.",
        en="🚫 Your sign is hidden. It does not affect compatibility.",
        pt="🚫 Seu signo está oculto. Não influencia a compatibilidade.",
        fr="🚫 Votre signe est masqué. Il n'influence pas la compatibilité.",
        de="🚫 Ihr Zeichen ist verborgen. Es beeinflusst die Kompatibilität nicht.",
        it="🚫 Il tuo segno è nascosto. Non influenza la compatibilità.",
        ru="🚫 Ваш знак скрыт. Он не влияет на совместимость.",
        sv="🚫 Ditt tecken är dolt. Det påverkar inte kompatibiliteten.",
        nl="🚫 Je teken is verborgen. Het beïnvloedt de compatibiliteit niet.",
        zh="🚫 你的星座已隐藏。它不会影响匹配度。",
        hi="🚫 आपकी राशि छिपी है। यह अनुकूलता को प्रभावित नहीं करती।",
        bn="🚫 আপনার রাশি লুকানো। এটি সামঞ্জস্যতাকে প্রভাবিত করে না।",
        ja="🚫 あなたのサインは非公開です。マッチには影響しません。",
        ko="🚫 당신의 별자리는 숨겨져 있습니다. 궁합에 영향을 주지 않습니다.",
        ar="🚫 برجك مخفي. لا يؤثر في التوافق.",
        sw="🚫 Ishara yako imefichwa. Haionyeshi kwenye uoendana.",
        ha="🚫 Alamarinka tana ɓoye. Ba ta daɗawa da mutammanci.",
        am="🚫 ምልክትህ ተደብቋል። ማስማሚነትን አያጎዳም።",
        tl="🚫 Nakakatago ang iyong sign. Hindi nito binabago ang compatibility.",
        ms="🚫 Tanda anda tersembunyi. Ia tidak mempengaruhi keserasian.",
        mi="🚫 Ke huna tōu tohu. Kāore e pāngai te whakatau kōtū.",
    ),
    text(
        "zodiac.compatQuote", 56,
        es="“Tu compatibilidad será guiada por lo que realmente te importa.”",
        en="“Your compatibility will be guided by what you really care about.”",
        pt="“Sua compatibilidade será guiada pelo que realmente importa para você.”",
        fr="“Votre compatibilité sera guidée par ce qui compte vraiment pour vous.”",
        de="„Ihre Kompatibilität richtet sich nach dem, was Ihnen wirklich wichtig ist.“",
        it="“La tua compatibilità sarà guidata da ciò che conta davvero per te.”",
        ru="«Ваша совместимость будет определяться тем, что действительно важно для вас.»",
        sv="”Din kompatibilitet vägleds av det som verkligen betyder något för dig.”",
        nl="“Je compatibiliteit wordt bepaald door wat je echt belangrijk vindt.”",
        zh="“你的匹配将由你真正看重的事情来决定。”",
        hi="“आपकी अनुकूलता उससे निर्देशित होगी जो आपके लिए सचमुच मायने रखता है।",
        bn="“আপনার সামঞ্জস্যতা আপনার কাছে সত্যিই গুরুত্বপূর্ণ যা দিয়ে নির্দেশিত হবে।”",
        ja="“あなたのマッチは、あなたが本当に大切にしているもので導かれます。”",
        ko="“당신의 궁합은 당신이 정말로 중요하게 여기는 것으로 결정됩니다.”",
        ar="“سيُوجَّه توافقك بما يهمك فعلًا.”",
        sw="“Uoendana wako utaongozwa na kile unachopenda kweli.”",
        ha="“Mutammaninka za a jagorantar da abin da kake ƙauna da gaske.”",
        am="“ስምምነትህ በለት ያለው አንድ ይመራል።”",
        tl="“Ang iyong compatibility ay gagabinan ng tunay mong mahalaga.”",
        ms="“Keserasian anda akan dipandu oleh apa yang benar-benar penting bagi anda.”",
        mi="“Ka āta whakatau tō te whakapono kōtū i ngā mea nui mō te koe.”",
    ),
    text(
        "zodiac.disabled", 57,
        es="Selección desactivada", en="Selection disabled",
        pt="Seleção desativada", fr="Sélection désactivée",
        de="Auswahl deaktiviert", it="Selezione disattivata",
        ru="Выбор отключён", sv="Val avstängd", nl="Selectie uitgeschakeld",
        zh="选择已关闭", hi="चयन बंद है", bn="নির্বাচন বন্ধ",
        ja="選択は無効です", ko="선택이 비활성화되어 있습니다", ar="التعطيل معطّل",
        sw="Uchaguzi umezimwa", ha="Za a kashe zaɗi",
        am="ምርጫ ጠፍቷል", tl="Naka-off ang pagpili",
        ms="Pilihan dinyahikan", mi="Kua kore whiringa",
    ),
    text(
        "zodiac.sign.aries", 60,
        es="Aries", en="Aries", pt="Áries", fr="Bélier",
        de="Widder", it="Ariete", ru="Овен", sv="Väduren", nl="Ram",
        zh="白羊座", hi="मेष", bn="মেষ",
        ja="牡羊座", ko="양자리", ar="الحمل",
        sw="Kondowe", ha="Aries", am="አሪስ", tl="Aries",
        ms="Aries", mi="Aries",
    ),
    text(
        "zodiac.sign.tauro", 61,
        es="Tauro", en="Taurus", pt="Touro", fr="Taureau",
        de="Stier", it="Toro", ru="Телец", sv="Oxen", nl="Stier",
        zh="金牛座", hi="वृषभ", bn="বৃষ",
        ja="牡牛座", ko="황소자리", ar="الثور",
        sw="Ng'ombe", ha="Taurus", am="ታውሮ", tl="Taurus",
        ms="Taurus", mi="Taurus",
    ),
    text(
        "zodiac.sign.geminis", 62,
        es="Géminis", en="Gemini", pt="Gêmeos", fr="Gémeaux",
        de="Zwilling", it="Gemelli", ru="Близнецы", sv="Tvillingar", nl="Tweeling",
        zh="双子座", hi="मिथुन", bn="মিথুন",
        ja="双子座", ko="쌍둥이자리", ar="الجوزاء",
        sw="Kishoto", ha="Gemini", am="ጌሚኒ", tl="Gemini",
        ms="Gemini", mi="Gemini",
    ),
    text(
        "zodiac.sign.cancer", 63,
        es="Cáncer", en="Cancer", pt="Câncer", fr="Cancer",
        de="Krebs", it="Cancro", ru="Рак", sv="Kräftan", nl="Kreeft",
        zh="巨蟹座", hi="कर्क", bn="কর্কট",
        ja="蟹座", ko="게자리", ar="السرطان",
        sw="Kansa", ha="Cancer", am="ካንሰር", tl="Cancer",
        ms="Cancer", mi="Cancer",
    ),
    text(
        "zodiac.sign.leo", 64,
        es="Leo", en="Leo", pt="Leão", fr="Lion",
        de="Löwe", it="Leone", ru="Лев", sv="Lejonet", nl="Leeuw",
        zh="狮子座", hi="सिंह", bn="সিংহ",
        ja="獅子座", ko="사자자리", ar="الأسد",
        sw="Simba", ha="Leo", am="ሊዎ", tl="Leo",
        ms="Leo", mi="Leo",
    ),
    text(
        "zodiac.sign.virgo", 65,
        es="Virgo", en="Virgo", pt="Virgem", fr="Vierge",
        de="Jungfrau", it="Vergine", ru="Дева", sv="Jungfrun", nl="Maagd",
        zh="处女座", hi="कन्या", bn="কন্যা",
        ja="乙女座", ko="처녀자리", ar="العذراء",
        sw="Hudhudi", ha="Virgo", am="ቭርጎ", tl="Virgo",
        ms="Virgo", mi="Virgo",
    ),
    text(
        "zodiac.sign.libra", 66,
        es="Libra", en="Libra", pt="Libra", fr="Balance",
        de="Waage", it="Bilancia", ru="Весы", sv="Vågen", nl="Weegschaal",
        zh="天秤座", hi="तुला", bn="তুলা",
        ja="天秤座", ko="천칭자리", ar="الميزان",
        sw="Mizani", ha="Libra", am="ሊብራ", tl="Libra",
        ms="Libra", mi="Libra",
    ),
    text(
        "zodiac.sign.escorpio", 67,
        es="Escorpio", en="Scorpio", pt="Escorpião", fr="Scorpion",
        de="Skorpion", it="Scorpione", ru="Скорпион", sv="Skorpionen",
        nl="Schorpioen",
        zh="天蝎座", hi="वृश्चिक", bn="বৃশ্চিক",
        ja="蠍座", ko="전갈자리", ar="العقرب",
        sw="Scarpio", ha="Scorpio", am="ስክርፒዎ", tl="Scorpio",
        ms="Scorpio", mi="Scorpio",
    ),
    text(
        "zodiac.sign.sagitario", 68,
        es="Sagitario", en="Sagittarius", pt="Sagitário", fr="Sagittaire",
        de="Schütze", it="Sagittario", ru="Стрелец", sv="Skytten",
        nl="Boogschutter",
        zh="射手座", hi="धनु", bn="ধনু",
        ja="射手座", ko="사수자리", ar="القوس",
        sw="Mshahara", ha="Sagittarius", am="ሳጅታሪ", tl="Sagittarius",
        ms="Sagittarius", mi="Sagittarius",
    ),
    text(
        "zodiac.sign.capricornio", 69,
        es="Capricornio", en="Capricorn", pt="Capricórnio",
        fr="Capricorne",
        de="Steinbock", it="Capricorno", ru="Козерог", sv="Stenbocken",
        nl="Steenbok",
        zh="摩羯座", hi="मकर", bn="মকর",
        ja="山羊座", ko="염소자리", ar="جدري",
        sw="Mbuzi", ha="Capricorn", am="ካፕሪክርን", tl="Capricorn",
        ms="Capricorn", mi="Capricorn",
    ),
    text(
        "zodiac.sign.acuario", 70,
        es="Acuario", en="Aquarius", pt="Aquário", fr="Verseau",
        de="Wassermann", it="Acquario", ru="Водолей", sv="Vattumannen",
        nl="Waterman",
        zh="水瓶座", hi="कुंभ", bn="কুম্ভ",
        ja="水瓶座", ko="물병자리", ar="الدلو",
        sw="Bahari", ha="Aquarius", am="አኩወሪያስ", tl="Aquarius",
        ms="Aquarius", mi="Aquarius",
    ),
    text(
        "zodiac.sign.piscis", 71,
        es="Piscis", en="Pisces", pt="Peixes", fr="Poissons",
        de="Fische", it="Pesci", ru="Рыбы", sv="Fiskarna", nl="Vissen",
        zh="双鱼座", hi="मीन", bn="মীন",
        ja="魚座", ko="물고기자리", ar="الحوت",
        sw="Samaki", ha="Pisces", am="ፒስስ", tl="Pisces",
        ms="Pisces", mi="Pisces",
    ),
]